--CONSULTA GLOBAL
SELECT * FROM EDSR.WMS_ORDER_HDR_ENVIO
WHERE FEC_REG <= SYSDATE
	AND FEC_REG >= SYSDATE - 5
ORDER BY FEC_REG DESC
;

SELECT TRF_NUMBER FROM EDSR.WMS_ORDER_HDR_ENVIO
--UPDATE EDSR.WMS_ORDER_HDR_ENVIO SET WMS_REIMPULSE_FLG = 0
WHERE WMS_REIMPULSE_FLG = 1;
COMMIT;

--HORARIO DE EJECUCION DEL ORDENES
SELECT ID_TIPO,
             TIPO_INTEGRACION,
             HORA_INICIO,
             HORA_FINAL
      FROM WMS_TIPO_INTEGRACION;

--CONSULTA MONITOR
SELECT 
id_wms,hdr.TRF_NUMBER,hdr.ORDER_NBR,hdr.FACILITY_CODE,DEST_FACILITY_CODE AS DEST,FEC_REG ,FLG_ERROR, ID_TIPO, hdr.fec_procesado--,RETRIGGERED,RETRIGGERED_AT,WMS_ORIG_PROCESSED_AT
,WMS_HDR_EXISTS,WMS_DTL_EXISTS,WMS_DTL_COUNT,WMS_ID_LAST_CHECK_AT,WMS_LAST_CHECK_AT,WMS_ERR_CODE,WMS_ERR_MSG,RETRY_COUNT,WMS_REIMPULSE_FLG,WMS_CHECK_STATUS
--hdr.json_response,hdr.mensaje,hdr.flg_error,hdr.text_request,hdr.*
FROM EDSR.wms_order_hdr_envio hdr
 --UPDATE EDSR.WMS_ORDER_HDR_ENVIO SET FEC_PROCESADO = null
WHERE 
	--TRF_NUMBER IN (233313,233323,234270,235159,236098)
	ID_WMS IN (154161540,154161407,154159799) --
	--WMS_CHECK_STATUS = 'NOT_FOUND'
ORDER BY FEC_PROCESADO DESC
; COMMIT;
-- Esta TRF 234270 se coonsidero para las pruebas en las que la API fallara.

--CONSULTA SOLO UNA ORDEN
SELECT * FROM edsr.wms_order_hdr_envio WHERE WMS_ORDER_HDR_ENVIO.ID_WMS = 154108853;

--************************************************************
--CONSULTA DE CUANTOS ESTAN PENDIENTES A REIMPULSAR
--************************************************************
SELECT
ID_ORDER_HDR,ID_WMS_OLD,id_wms,hdr.TRF_NUMBER,hdr.ORDER_NBR,hdr.FACILITY_CODE AS T,DEST_FACILITY_CODE AS DEST,FEC_REG ,FLG_ERROR, ID_TIPO, hdr.fec_procesado,RETRIGGERED,RETRIGGERED_AT,WMS_ORIG_PROCESSED_AT
,WMS_HDR_EXISTS,WMS_DTL_EXISTS,WMS_DTL_COUNT,WMS_ID_LAST_CHECK_AT,WMS_LAST_CHECK_AT,WMS_ERR_CODE,WMS_ERR_MSG,RETRY_COUNT,WMS_REIMPULSE_FLG,WMS_CHECK_STATUS
--hdr.json_response,hdr.mensaje,hdr.flg_error,hdr.text_request,hdr.*
FROM EDSR.wms_order_hdr_envio hdr
WHERE WMS_REIMPULSE_FLG = 1
ORDER BY FEC_REG DESC
;

--ERRORES CON CONSULTA EN LA DETALLE
SELECT COUNT(*) FROM EDSR.WMS_ORDER_HDR_ENVIO WHERE WMS_CHECK_STATUS  = 'ERROR';
SELECT COUNT(*) FROM EDSR.WMS_ORDER_HDR_ENVIO WHERE WMS_CHECK_STATUS  = 'NOT_FOUND';
SELECT COUNT(*) FROM EDSR.WMS_ORDER_HDR_ENVIO WHERE WMS_CHECK_STATUS  = 'OK';

SELECT * FROM EDSR.WMS_ORDER_HDR_ENVIO WHERE WMS_CHECK_STATUS  = 'NOT_FOUND';

--ERRORES CON CONSULTA EN LA CABECERA
SELECT COUNT(*) FROM EDSR.WMS_ORDER_HDR_ENVIO WHERE ID_WMS_OLD IS NULL; --21921
SELECT COUNT(*) FROM EDSR.WMS_ORDER_HDR_ENVIO WHERE WMS_HEADER_EXISTS IS NULL;
SELECT COUNT(*) FROM EDSR.WMS_ORDER_HDR_ENVIO WHERE WMS_CHECK_STATUS  = 'HDR_NOT_FOUND';



--CONSULTAS 
SELECT FEC_REG,TRF_NUMBER,ORDER_NBR,WMS_CHECK_STATUS,ID_WMS,ID_WMS_OLD, WMS_ID_LAST_CHECK_AT,WMS_DTL_EXISTS,RETRY_COUNT AS RETRY,WMS_LAST_CHECK_AT
FROM (
    SELECT FEC_REG,TRF_NUMBER,ORDER_NBR,WMS_CHECK_STATUS, ID_WMS,ID_WMS_OLD, WMS_ID_LAST_CHECK_AT,WMS_DTL_EXISTS,RETRY_COUNT,WMS_LAST_CHECK_AT
    FROM EDSR.WMS_ORDER_HDR_ENVIO
    WHERE
        ORDER_NBR IS NOT NULL
        AND ID_WMS IS NOT NULL
        AND FEC_REG BETWEEN SYSDATE - :1 AND SYSDATE
        AND NVL(WMS_DTL_EXISTS, -1) <> 1
        AND NVL(RETRY_COUNT, 0) < :2
    ORDER BY ORD_DATE DESC, ID_ORDER_HDR DESC
)
WHERE ROWNUM <= :3
ORDER BY FEC_REG DESC

;

/*
 * 20210
 * 20190
 * 20195
 */
--Nueva consulta
      SELECT
     -- COUNT(1)
     --DISTINCT id_wms
     -- *
      	ID_ORDER_HDR, ID_WMS,TRF_NUMBER
      FROM EDSR.WMS_ORDER_HDR_ENVIO
      WHERE 
      	ID_WMS IS NOT NULL 
        AND ORD_DATE BETWEEN SYSDATE - 5 AND SYSDATE
        AND NVL(WMS_DTL_EXISTS, -1) <> 1
        AND NVL(RETRY_COUNT, 0) < 3
        --AND ( (WMS_LAST_CHECK_AT IS NULL) OR (WMS_CHECK_STATUS = 'ERROR' AND NVL(RETRY_COUNT, 0) < :2 ) )
      ORDER BY
        --CASE WHEN WMS_LAST_CHECK_AT IS NULL THEN 0 ELSE 1 END,
        ORD_DATE DESC,
        ID_ORDER_HDR DESC
   -- FOR UPDATE SKIP LOCKED
   ;

SELECT	ID_ORDER_HDR, ID_WMS
FROM EDSR.WMS_ORDER_HDR_ENVIO
WHERE 
	ID_WMS IS NOT NULL 
    AND NVL(WMS_DTL_EXISTS, -1) <> 1
    AND NVL(RETRY_COUNT, 0) < 3
ORDER BY
	ORD_DATE DESC,
    ID_ORDER_HDR DESC
FOR UPDATE SKIP LOCKED;

--consulta antigua
SELECT ID_ORDER_HDR, ID_WMS
FROM EDSR.WMS_ORDER_HDR_ENVIO
WHERE ID_WMS IS NOT NULL
    AND NVL(WMS_DTL_EXISTS, -1) <> 1
    AND (WMS_REIMPULSE_FLG IS NULL OR WMS_REIMPULSE_FLG = 0)
    AND (WMS_LAST_CHECK_AT IS NULL OR WMS_LAST_CHECK_AT < SYSTIMESTAMP - INTERVAL '5' MINUTE)
	AND NVL(RETRY_COUNT, 0) < 3
	AND ROWNUM <= 200
FOR UPDATE SKIP LOCKED