-- DOCUMENTOS PENDIENTES
SELECT
    HEAD.HEADID AS headId,
    CASE
        WHEN HEAD.DOCUMENTTYPE = 'TFC' THEN 1
        WHEN HEAD.DOCUMENTTYPE = 'NCR' THEN 4
    END AS documentType
FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
WHERE HEAD.FLGPPL = 0
    AND HEAD.STATUS IN ('P') -- ('P', 'V')
    AND HEAD.DOCUMENTTYPE IN ('TFC','NCR');

-- DOCUMENTOS PENDIENTES ENVIAR SOVOS
SELECT  HEAD.HEADID AS headid,
        HEAD.PPL_RET_CODE,
        COM.RUC AS RucEmpresa,
        CASE
            WHEN HEAD.DOCUMENTTYPE = 'TFC' THEN '01'
            WHEN HEAD.DOCUMENTTYPE = 'NCR' THEN '04'
        END AS TipoDocumento,
        REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,1) AS Establecimiento,
        REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,2) AS PtoEmision,
        REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,3) AS Secuencial
FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
    INNER JOIN EDSR.PIVOT_COMPANY COM ON HEAD.COMPANY = COM.COD_COMPANY
--UPDATE EDSRCT2.PIV_TRX_BCT_HEAD HEAD SET HEAD.PPL_RET_CODE = '6'
WHERE HEAD.PPL_RET_CODE IN ('1','3','8','9');

/*
-1  =>  No se ha recibido
0   =>  Errado e-billing
1   =>  iniciado
2   =>  Rechazado
3   =>  Recibido
4   =>  Negado
5   =>  Autorizado
6   =>  Anulado
8   =>  Sin Respuesta del SRI
9   =>  En procesamiento
*/


SELECT HEAD.DOCUMENTTYPE,HEAD.FLGPPL, HEAD.* FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
--UPDATE EDSRCT2.PIV_TRX_BCT_HEAD SET FLGPPL = 0
WHERE HEADID = 363;

-- OBTENER EL ID_IVA mediante SKU
DECLARE
    V_ID_IVA NUMBER(5);
BEGIN

    SELECT ID_IVA
    INTO V_ID_IVA
    FROM EDSRCT2.SRI_IVA_PORCENTAJE
    WHERE PORC_IVA = (
            SELECT FNU_GET_PRODUCTO_IVA(PRD_LVL_CHILD)
            FROM TPPRDMST
            WHERE PRD_LVL_NUMBER = '32137'
        );

    DBMS_OUTPUT.PUT_LINE('V_ID_IVA: ' || V_ID_IVA);
END;


-- OBTENER EL PORCENTAJE IVA mediante SKU
DECLARE
    V_PORCENTAJE NUMBER(12,2);
BEGIN
    BEGIN
        SELECT FNU_GET_PRODUCTO_IVA(PRD_LVL_CHILD)
        INTO V_PORCENTAJE
        FROM TPPRDMST
        WHERE PRD_LVL_NUMBER = '32454';
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL SKU');
    END;

    DBMS_OUTPUT.PUT_LINE('V_PORCENTAJE: ' || V_PORCENTAJE);
END;


--Listar Documentos pendientes
SELECT HEAD.PPLSERIALNUMBER, HEAD.FLGPPL, HEAD.STATUS,    HEAD.DOCUMENTTYPE , HEAD.*
FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
WHERE HEAD.FLGPPL = 0
         AND HEAD.STATUS IN ('P') -- ('P', 'V')
         AND HEAD.DOCUMENTTYPE IN ('TFC','NCR');

SELECT HEAD.FLGPPL, HEAD.STATUS,    HEAD.DOCUMENTTYPE , HEAD.* FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
--UPDATE EDSRCT2.PIV_TRX_BCT_HEAD HEAD SET HEAD.FLGPPL = 1
 WHERE HEAD.HEADID = 350;
--WHERE HEAD.FLGPPL = 0 AND HEAD.STATUS IN ('P') AND HEAD.DOCUMENTTYPE IN ('TFC','NCR') ORDER BY HEAD.HEADID DESC;

-- PRUEBAS
SELECT HEAD.PPLSERIALNUMBER,HEAD.FLGPPL,HEAD.STATUS,HEAD.DOCUMENTTYPE , HEAD.* FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
--UPDATE EDSRCT2.PIV_TRX_BCT_HEAD HEAD SET HEAD.FLGPPL = 1
WHERE HEADID <= 301 ORDER BY HEAD.HEADID DESC;

SELECT HEAD.PPLSERIALNUMBER,HEAD.FLGPPL,HEAD.STATUS,HEAD.DOCUMENTTYPE , HEAD.* FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
--UPDATE EDSRCT2.PIV_TRX_BCT_HEAD HEAD SET HEAD.FLGPPL = 1
WHERE HEADID >= 292 AND HEADID <= 293 ORDER BY HEAD.HEADID DESC;


SELECT  HEAD.* FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD ORDER BY HEAD.HEADID DESC;
SELECT * FROM EDSRCT2.PIV_TRX_BCT_ITEM ITEM;

SELECT * FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD WHERE HEADID = 284; -- 15% 5%
SELECT HEAD.FLGPPL,HEAD.STATUS,HEAD.DOCUMENTTYPE , HEAD.* FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD WHERE HEADID >= 281 AND HEADID <= 286 ORDER BY HEAD.HEADID DESC;
SELECT * FROM EDSRCT2.PIV_TRX_BCT_ITEM ITEM WHERE ITEM.HEADID >= 281 ORDER BY ITEM.HEADID DESC;
SELECT * FROM EDSRCT2.PIV_TRX_BCT_DSCTO DSCTO WHERE DSCTO.HEADID >= 281 ORDER BY DSCTO.HEADID DESC;

SELECT HEAD.PPLSERIALNUMBER, HEAD.DOCUMENTTYPE,HEAD.FLGPPL,HEAD.PPL_RET_CODE,HEAD.AMOUNT,HEAD.AFFECTEDTOTALAMOUNT, HEAD.UNAFFECTEDTOTALAMOUNT, HEAD.* FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD WHERE HEADID = 367;
SELECT ITEM.ID_IVA, ITEM.* FROM EDSRCT2.PIV_TRX_BCT_ITEM ITEM WHERE HEADID = 367;
SELECT * FROM EDSRCT2.PIV_TRX_BCT_DSCTO DSCTO WHERE HEADID = 367;

SELECT * FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD WHERE HEADID = 303;
SELECT * FROM EDSRCT2.PIV_TRX_BCT_ITEM ITEM WHERE HEADID = 303;
SELECT * FROM EDSRCT2.PIV_TRX_BCT_DSCTO DSCTO WHERE HEADID = 303;

DELETE FROM EDSRCT2.PIV_TRX_BCT_DSCTO
WHERE ITEMSEQUENCE IN (1,2,3,4);

SELECT * FROM EDSRCT2.SRI_IVA_PORCENTAJE IVA;

 --QA 21
SELECT  *  FROM EDSRCT2.PIV_TRX_BCT_DSCTO DSCTO WHERE HEADID = 72; --PRD

SELECT  ROUND(NVL(SUM(DSCTO.AMOUNT)/( (12/100) + 1 ),0.00),2)  FROM EDSRCT2.PIV_TRX_BCT_DSCTO DSCTO WHERE HEADID = 72;
select txs_rate from txsratee;
-- CHILD PARAMETRO, RETORNA EL PORCENTAJE EN DECIMAL
-- FNU_GET_PRODUCTO_IVA()

/*      ID_IVA  CODIGOPORCENTAJE    PORCENTAJE  PRICE(IVA)  PRECIO(SIN IVA) DSCTO
30943 -> 1          0                0%         100.00      100             10.00
32137 -> 6          5                5%         105.00      100             20.00
10196 -> 5          4                15%        115.00      100             30.00
---------------------------
TOTAL:              55.14
 */

INSERT INTO EDSRCT2.PIV_TRX_BCT_DSCTO (HEADID, CODE, NAME, ITEMSEQUENCE, ITEMEAN, ITEMSKU, AMOUNT, GROUPCODE) VALUES (17, '67890', 'DSCTO_CEXP', 1, '2800014513712', '30943', 10.00, 1);
INSERT INTO EDSRCT2.PIV_TRX_BCT_DSCTO (HEADID, CODE, NAME, ITEMSEQUENCE, ITEMEAN, ITEMSKU, AMOUNT, GROUPCODE) VALUES (17, '67890', 'DSCTO_CEXP', 2, '2800014513712', '32137', 20.00, 1);
INSERT INTO EDSRCT2.PIV_TRX_BCT_DSCTO (HEADID, CODE, NAME, ITEMSEQUENCE, ITEMEAN, ITEMSKU, AMOUNT, GROUPCODE) VALUES (17, '67890', 'DSCTO_CEXP', 3, '2800014513712', '10196', 30.00, 1);

INSERT INTO EDSRCT2.PIV_TRX_BCT_ITEM (HEADID, SEQUENCE, SKU, EAN, PRODUCTNAME, PRCDEPAR, UNITEDNATIONSCODE, TYPE, QUANTITY, WEIGHT, TAXAMOUNT, PRICE, ISIGVAFFECTED, WEIGHTUNITS, WEIGHTDECIMALS, ID_IVA)
VALUES (17, 2, '32137', '2800014513712', 'PV20 AMC BLMC PANAL TP V5 COL ROSAS', '11', '53101604', 'U', 1, 0, 5.00, 105.00, '1', 0, 0, 6);

INSERT INTO EDSRCT2.PIV_TRX_BCT_ITEM (HEADID, SEQUENCE, SKU, EAN, PRODUCTNAME, PRCDEPAR, UNITEDNATIONSCODE, TYPE, QUANTITY, WEIGHT, TAXAMOUNT, PRICE, ISIGVAFFECTED, WEIGHTUNITS, WEIGHTDECIMALS, ID_IVA)
VALUES (17, 3, '32137', '2800014513712', 'PV20 AMC BLMC PANAL TP V5 COL ROSAS', '11', '53101604', 'U', 1, 0, 15.00, 115.00, '1', 0, 0, 5);


DECLARE
    v_HeadId NUMBER := 17;
    V_COUNT_DSCT NUMBER(10);
    V_TOTALDESCUENTO NUMBER(12,2); -- sin IVA
BEGIN
    BEGIN
        SELECT  COUNT(1)
        INTO V_COUNT_DSCT
        FROM EDSRCT2.PIV_TRX_BCT_DSCTO DSCTO
        WHERE HEADID = v_HeadId;
    EXCEPTION
        WHEN OTHERS THEN
            V_COUNT_DSCT := 0;
            V_TOTALDESCUENTO := 0;
    END;

    IF V_COUNT_DSCT > 0 THEN
        --  (SELECT ROUND(NVL(SUM(AMOUNT)/( (HEAD.IGVPERCENTAGE/100) + 1 ),0.00),2) FROM EDSRCT2.PIV_TRX_BCT_DSCTO WHERE HEADID = HEAD.HEADID ) AS totalDescuento,
        BEGIN
            SELECT SUM( ROUND( NVL( AMOUNT/( (FNU_GET_PRODUCTO_IVA(PRD.PRD_LVL_CHILD)/100) + 1 ), 0.00),2) )
            INTO V_TOTALDESCUENTO
            FROM EDSRCT2.PIV_TRX_BCT_DSCTO DSCTO
                INNER JOIN EDSR.TPPRDMST PRD ON PRD.PRD_LVL_NUMBER = DSCTO.ITEMSKU;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('>>> EXCEPTION (calculo del descuento sin IVA): ' || sqlerrm);
        END;
    END IF;

    DBMS_OUTPUT.PUT_LINE('V_COUNT_DSCT: ' || V_COUNT_DSCT);
    DBMS_OUTPUT.PUT_LINE('V_TOTALDESCUENTO: ' || V_TOTALDESCUENTO);

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(sqlerrm);

END;

SELECT HEAD.AMOUNT, HEAD.AFFECTEDTOTALAMOUNT FROM  EDSRCT2.PIV_TRX_BCT_HEAD HEAD WHERE HEAD.HEADID IN (288,289,290,291,294);

-- FACTURA
SELECT
		    COM.RAZON_SOCIAL as razonSocial,
		    COM.RUC AS ruc,
		    '01' codDoc,
		    REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,1) AS estab,
		    REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,2) AS ptoEmi,
		    REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,3) AS secuencial,
		    COM.DIRECCION_MATRIZ AS dirMatriz,

		    TO_CHAR(HEAD.TRXDATE,'DD/MM/YYYY') AS fechaEmision,
		    EST.VC_DIRECCION AS dirEstablecimiento,
		    'SI' AS obligadoContabilidad,
		    CASE
		        WHEN HEAD.CUSTOMERBUSINESSDOCNUMBER IS NULL THEN '05'
		        WHEN LENGTH(HEAD.CUSTOMERBUSINESSDOCNUMBER) = 0 THEN '05'
		        ELSE '04'
		    END AS tipoIdentificacionComprador,
		    CASE
		        WHEN HEAD.CUSTOMERBUSINESSDOCNUMBER IS NULL THEN HEAD.CUSTOMERNAME || ' ' || HEAD.CUSTOMERSURNAME
		        WHEN LENGTH(HEAD.CUSTOMERBUSINESSDOCNUMBER) = 0 THEN  HEAD.CUSTOMERNAME || ' ' || HEAD.CUSTOMERSURNAME
		        ELSE HEAD.CUSTOMERBUSINESSNAME
		    END AS razonSocialComprador,
		    CASE
		        WHEN HEAD.CUSTOMERBUSINESSDOCNUMBER IS NULL THEN HEAD.CUSTOMERDOCUMENTNUMBER
		        WHEN LENGTH(HEAD.CUSTOMERBUSINESSDOCNUMBER) = 0 THEN HEAD.CUSTOMERDOCUMENTNUMBER
		        ELSE HEAD.CUSTOMERBUSINESSDOCNUMBER
		    END AS identificacionComprador,
		    nvl(pic.direccion, 'Guayaquil') AS direccionComprador,

		    HEAD.AFFECTEDTOTALAMOUNT + HEAD.UNAFFECTEDTOTALAMOUNT AS totalSinImpuestos,

		    'V_TOTALDESCUENTO' AS totalDescuento,

		    2 AS codigo,
		    2 AS codigoPorcentaje,
		    HEAD.AFFECTEDTOTALAMOUNT AS baseImponible,
		    HEAD.IGVPERCENTAGE AS tarifa,
		    HEAD.IGVTOTALAMOUNT AS valor,

		    '0.00' AS propina,
		    HEAD.AMOUNT AS importeTotal,
		    'DOLAR' AS moneda,

		    MEDIOPAGO.COD_SRI AS formaPago,
		    HEAD.AMOUNT AS total,
		    PAYMENT.CUOTAS*30 AS plazo,
		    'dias' AS unidadTiempo,

		    HEAD.CUSTOMEREMAIL AS email,
		    HEAD.CUSTOMERPHONE AS telefono

		FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
		INNER JOIN EDSR.PIVOT_COMPANY COM ON HEAD.COMPANY = COM.COD_COMPANY
		INNER JOIN EDSR.PIVOT_ESTABLECIMIENTO EST ON (HEAD.BRANCHID = EST.BRANCHID AND COM.COD_COMPANY = EST.COD_COMPANY)
		LEFT JOIN EDSRCT2.PIV_TRX_BCT_DSCTO  DSCTO  ON HEAD.HEADID = DSCTO.HEADID
		LEFT JOIN EDSRCT2.PIV_TRX_BCT_PAYMENT PAYMENT ON PAYMENT.HEADID = HEAD.HEADID
		LEFT JOIN EDSR.HP_VTEX_MEDIO_PAGO MEDIOPAGO ON MEDIOPAGO.IDVTEX = PAYMENT.PAYMENTMETHODCODE
    left join edsr.hp_vtex_picking pic on pic.id_picking = head.originid and head.origintrx = 1
		WHERE
		    COM.COD_COMPANY = 'HE'
		   -- AND PAYMENT.PAYMENTMETHODCODE IN (1,401,2,3,4,5)
		    AND HEAD.HEADID = 288;

-- DETALLE
SELECT
        ITEM.SKU AS codigoPrincipal,
        ITEM.PRODUCTNAME AS descripcion,
        TO_NUMBER(ITEM.QUANTITY,'9999.99') AS cantidad,
        ROUND(NVL(ITEM.PRICE/( (IVA.PORC_IVA/100) + 1 ),0.00),2) AS precioUnitario,
        ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2) AS descuento,
        ROUND(NVL( ITEM.QUANTITY*(ITEM.PRICE/( (IVA.PORC_IVA/100) + 1 )) - ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2), 0.00) ,2) AS precioTotalSinImpuesto,

        2 AS codigo,
        IVA.COD_IVA AS codigoPorcentaje,
        TO_CHAR(IVA.PORC_IVA,'999.99') AS tarifa,
        ROUND(NVL( ITEM.QUANTITY*(ITEM.PRICE/( (IVA.PORC_IVA/100) + 1 )) - ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2), 0.00) ,2) AS baseImponible,
        IVA.PORC_IVA AS valor

	FROM EDSRCT2.PIV_TRX_BCT_ITEM ITEM
	INNER JOIN EDSRCT2.SRI_IVA_PORCENTAJE IVA ON IVA.ID_IVA = ITEM.ID_IVA
	INNER JOIN  EDSRCT2.PIV_TRX_BCT_HEAD HEAD ON HEAD.HEADID = ITEM.HEADID
	INNER JOIN EDSR.PIVOT_COMPANY COM ON HEAD.COMPANY = COM.COD_COMPANY
	INNER JOIN EDSR.PIVOT_ESTABLECIMIENTO EST ON (HEAD. BRANCHID = EST.BRANCHID AND COM.COD_COMPANY = EST.COD_COMPANY)
	LEFT JOIN EDSRCT2.PIV_TRX_BCT_DSCTO  DSCTO  ON (HEAD.HEADID = DSCTO.HEADID AND ITEM.SEQUENCE = DSCTO.ITEMSEQUENCE)
	WHERE
	    COM.COD_COMPANY = 'HE'
	    AND HEAD.HEADID = 17;

-- TOTALIMPUESTOS
SELECT
    2 AS codigo,
    IVA.COD_IVA AS codigoPorcentaje,
    IVA.PORC_IVA AS tarifa,
    ROUND(NVL( SUM(ITEM.QUANTITY*(ITEM.PRICE/( (IVA.PORC_IVA/100) + 1 ))), 0.00) ,2) AS baseImponible,
    IVA.PORC_IVA AS valor

FROM EDSRCT2.PIV_TRX_BCT_ITEM ITEM
INNER JOIN EDSRCT2.SRI_IVA_PORCENTAJE IVA ON IVA.ID_IVA = ITEM.ID_IVA
INNER JOIN  EDSRCT2.PIV_TRX_BCT_HEAD HEAD ON HEAD.HEADID = ITEM.HEADID
INNER JOIN EDSR.PIVOT_COMPANY COM ON HEAD.COMPANY = COM.COD_COMPANY
INNER JOIN EDSR.PIVOT_ESTABLECIMIENTO EST ON (HEAD. BRANCHID = EST.BRANCHID AND COM.COD_COMPANY = EST.COD_COMPANY)
LEFT JOIN EDSRCT2.PIV_TRX_BCT_DSCTO  DSCTO  ON (HEAD.HEADID = DSCTO.HEADID AND ITEM.SEQUENCE = DSCTO.ITEMSEQUENCE)
WHERE
    COM.COD_COMPANY = 'HE'
    AND HEAD.HEADID = 17
GROUP BY IVA.COD_IVA,IVA.PORC_IVA;


-- AFTER
SELECT
        HEAD.HEADID,
        HEAD.IGVPERCENTAGE,
        ITEM.SKU AS codigoPrincipal,
        ITEM.PRODUCTNAME AS descripcion,
        TO_NUMBER(ITEM.QUANTITY,'9999.99') AS cantidad,
        ROUND(NVL(ITEM.PRICE/( (HEAD.IGVPERCENTAGE/100) + 1 ),0.00),2) AS precioUnitario,
        ROUND(NVL(DSCTO.AMOUNT/( (HEAD.IGVPERCENTAGE/100) + 1 ),0.00),2) AS descuento,
        ROUND(NVL( ITEM.QUANTITY*(ITEM.PRICE/( (HEAD.IGVPERCENTAGE/100) + 1 )) - ROUND(NVL(DSCTO.AMOUNT/( (HEAD.IGVPERCENTAGE/100) + 1 ),0.00),2), 0.00) ,2) AS precioTotalSinImpuesto,

        2 AS codigo,
        2 AS codigoPorcentaje,
        TO_CHAR(HEAD.IGVPERCENTAGE,'999.99') AS tarifa,
        ROUND(NVL( ITEM.QUANTITY*(ITEM.PRICE/( (HEAD.IGVPERCENTAGE/100) + 1 )) - ROUND(NVL(DSCTO.AMOUNT/( (HEAD.IGVPERCENTAGE/100) + 1 ),0.00),2), 0.00) ,2) AS baseImponible,
        ITEM.TAXAMOUNT AS valor

	FROM EDSRCT2.PIV_TRX_BCT_ITEM ITEM
	INNER JOIN EDSRCT2.SRI_IVA_PORCENTAJE IVA ON IVA.ID_IVA = ITEM.ID_IVA
	INNER JOIN  EDSRCT2.PIV_TRX_BCT_HEAD HEAD ON HEAD.HEADID = ITEM.HEADID
	INNER JOIN EDSR.PIVOT_COMPANY COM ON HEAD.COMPANY = COM.COD_COMPANY
	INNER JOIN EDSR.PIVOT_ESTABLECIMIENTO EST ON (HEAD. BRANCHID = EST.BRANCHID AND COM.COD_COMPANY = EST.COD_COMPANY)
	LEFT JOIN EDSRCT2.PIV_TRX_BCT_DSCTO  DSCTO  ON (HEAD.HEADID = DSCTO.HEADID AND ITEM.SEQUENCE = DSCTO.ITEMSEQUENCE)
	WHERE
	    COM.COD_COMPANY = 'HE'
	    AND HEAD.HEADID = 72;

SELECT
    HEAD.HEADID,
    COUNT(HEAD.HEADID) AS COUNT
FROM EDSRCT2.PIV_TRX_BCT_ITEM ITEM
	INNER JOIN EDSRCT2.SRI_IVA_PORCENTAJE IVA ON IVA.ID_IVA = ITEM.ID_IVA
	INNER JOIN  EDSRCT2.PIV_TRX_BCT_HEAD HEAD ON HEAD.HEADID = ITEM.HEADID
	INNER JOIN EDSR.PIVOT_COMPANY COM ON HEAD.COMPANY = COM.COD_COMPANY
	INNER JOIN EDSR.PIVOT_ESTABLECIMIENTO EST ON (HEAD. BRANCHID = EST.BRANCHID AND COM.COD_COMPANY = EST.COD_COMPANY)
	LEFT JOIN EDSRCT2.PIV_TRX_BCT_DSCTO  DSCTO  ON (HEAD.HEADID = DSCTO.HEADID AND ITEM.SEQUENCE = DSCTO.ITEMSEQUENCE)
WHERE
	COM.COD_COMPANY = 'HE'
GROUP BY HEAD.HEADID
HAVING COUNT(HEAD.HEADID) > 2
ORDER BY COUNT DESC



-- NOTA DE CREDITO


-- DETALLE
SELECT
    ITEM.SKU AS codigoInterno,
    ITEM.PRODUCTNAME AS descripcion,
    TO_NUMBER(ITEM.QUANTITY,'9999.99') AS cantidad,
    ROUND(NVL(ITEM.PRICE/( (IVA.PORC_IVA/100) + 1 ),0.00),2) AS precioUnitario,
    ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2) AS descuento,
    ROUND(NVL( ITEM.QUANTITY*(ITEM.PRICE/( (IVA.PORC_IVA/100) + 1 )) - ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2), 0.00) ,2) AS precioTotalSinImpuesto,

    2 AS codigo,
    IVA.COD_IVA AS codigoPorcentaje,
    TO_CHAR(IVA.PORC_IVA,'999.99') AS tarifa,
    TRIM(TO_CHAR(IVA.PORC_IVA,'999')) AS tarifa3,
    DECODE(IVA.PORC_IVA,0.00,'0.00',TRIM(TO_CHAR(IVA.PORC_IVA,'999.99'))) AS tarifa2,
    ROUND(NVL( ITEM.QUANTITY*(ITEM.PRICE/( (IVA.PORC_IVA/100) + 1 )) - ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2), 0.00) ,2) AS baseImponible,
    ROUND( (NVL( ITEM.QUANTITY*(ITEM.PRICE/( (IVA.PORC_IVA/100) + 1 )) - ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2), 0.00))*(IVA.PORC_IVA/100)  ,2) AS valor

FROM EDSRCT2.PIV_TRX_BCT_ITEM ITEM
INNER JOIN EDSRCT2.SRI_IVA_PORCENTAJE IVA ON IVA.ID_IVA = ITEM.ID_IVA
INNER JOIN EDSRCT2.PIV_TRX_BCT_HEAD HEAD ON HEAD.HEADID = ITEM.HEADID
INNER JOIN EDSR.PIVOT_COMPANY COM ON HEAD.COMPANY = COM.COD_COMPANY
INNER JOIN EDSR.PIVOT_ESTABLECIMIENTO EST ON (HEAD. BRANCHID = EST.BRANCHID AND COM.COD_COMPANY = EST.COD_COMPANY)
LEFT JOIN EDSRCT2.PIV_TRX_BCT_DSCTO  DSCTO  ON (HEAD.HEADID = DSCTO.HEADID AND ITEM.SEQUENCE = DSCTO.ITEMSEQUENCE)
WHERE
    COM.COD_COMPANY = 'HE'
    AND HEAD.HEADID = 351;


SELECT * FROM EDSR.HP_VTEX_PICKING WHERE ID_PICKING IN (533);
SELECT * FROM EDSR.HP_VTEX_PICKING WHERE ID_PICKING IN (584);

SELECT * FROM EDSR.HP_VTEX_PICKING_DET WHERE ID_PICKING IN (533)
UNION
SELECT * FROM EDSR.HP_VTEX_PICKING_DET WHERE ID_PICKING IN (584);