DECLARE
    TYPE t_cursor IS REF CURSOR;

    P_CURSOR t_cursor;
    V_MESSAGE VARCHAR2(150);
BEGIN
EDSR.TP_PKG_INTERFAZ_PMM2SAPFICO.SP_GEN_INTERFAZ_SAP_RSL(
        P_PERIODO => '202311',
        P_USUARIO => 'HP70436936',
        P_EMPRESA => '30',
        P_MESSAGE =>V_MESSAGE,
        P_CUR_RESULT => P_CURSOR);

DBMS_OUTPUT.PUT_LINE(V_MESSAGE);
END;



BEGIN
    EDSR.TP_PKG_INTERFAZ_PMM2SAPFICO.SP_DEL_INTERFAZ_SAP_RSL(P_PERIODO => '202311');
END;

--648
select COUNT(1) from ISR_REP_RSL;
select * from ISR_REP_RSL;

select COUNT(1) from edsr.ISR_F550911;
select * from edsr.ISR_F550911 WHERE PODGJ = '2023-11-30';
select PERIODO from edsr.ISR_F550911;

/*
SELECT VALOR FROM ISP_VALORES_SAP WHERE CODIGO='CPCO';
DELETE ISR_F550911
WHERE PERIODO='202311'
    AND ESTADO_ENVIO='P'
    AND POCO='A501';
*/