SELECT * FROM edsr.VTEX_STOCK_DIFF;

SELECT ORG_LVL_NUMBER,
             PRD_LVL_NUMBER,
             CANTIDAD
      FROM edsr.VTEX_STOCK_DIFF;

INSERT INTO EDSR.VTEX_STOCK_DIFF(ORG_LVL_NUMBER, PRD_LVL_NUMBER, CANTIDAD) VALUES ('101','11826',0);


SELECT NVL(ACT.ORG_LVL_NUMBER, ANT.ORG_LVL_NUMBER) AS ORG_LVL_NUMBER,
             NVL(ACT.PRD_LVL_NUMBER, ANT.PRD_LVL_NUMBER) AS PRD_LVL_NUMBER,
             CASE WHEN NVL(ACT.CANTIDAD,0) <= 0 THEN 0 ELSE ACT.CANTIDAD END AS CANTIDAD
      FROM VTEX_STOCK_ACTUAL ACT
      FULL OUTER JOIN VTEX_STOCK_ANTERIOR ANT
        ON ACT.ORG_LVL_NUMBER = ANT.ORG_LVL_NUMBER
        AND ACT.PRD_LVL_NUMBER = ANT.PRD_LVL_NUMBER
      WHERE ACT.CANTIDAD IS NULL
        OR ANT.CANTIDAD IS NULL
        OR (NVL(ACT.CANTIDAD,0) <> NVL(ANT.CANTIDAD,0));