-- edsr.hp_pkg_mant_logistica.sp_upd_sobr_falt

/*
PROCEDURE SP_UPD_SOBR_FALT
  (
     P_CARGA_SOBRANTE      IN VARCHAR2,
     P_SUCURSAL_SOBRANTE   IN NUMBER,
     P_COMENTARIO          IN VARCHAR2,
     P_CARGA               IN VARCHAR2,
     P_CARTON              IN VARCHAR2,
     P_SKU                 IN NUMBER
  )
  IS
  BEGIN
    UPDATE SMS_DESCUADRE_ASN_CARGA
       SET ESTADO            = 'REVISADO',
           CARGA_SOBRANTE    = P_CARGA_SOBRANTE,
           SUCURSAL_SOBRANTE = P_SUCURSAL_SOBRANTE,
           DESCRIPCION       = P_COMENTARIO,
           FEC_REVISION      = SYSDATE,
           USU_REVISION      = 'SISTEMAS'
     WHERE LOAD_MANIFEST_NBR = P_CARGA
       AND CARTON = P_CARTON
       AND PRD_LVL_NUMBER = P_SKU;
  END;
*/

SELECT * FROM EDSR.SMS_DESCUADRE_ASN_CARGA;
SELECT LOAD_MANIFEST_NBR,CARTON,PRD_LVL_NUMBER,ESTADO,CARGA_SOBRANTE,SUCURSAL_SOBRANTE,DESCRIPCION,FEC_REVISION,USU_REVISION FROM EDSR.SMS_DESCUADRE_ASN_CARGA;

SELECT LOAD_MANIFEST_NBR,CARTON,PRD_LVL_NUMBER FROM EDSR.SMS_DESCUADRE_ASN_CARGA;