INSERT INTO EDSRCT2.PIV_TRX_BCT_HEAD
(HEADID, PPLSERIALNUMBER, ORIGINID, BRANCHID, POSID, TRXDATE, SEQUENCENUMBER, TYPETRX, ORIGINTRX, COMPANY, CURRENCY, BUDATE, STATUS, DATESAVED, DATEUPDATED, AMOUNT, AFFECTEDTOTALAMOUNT, UNAFFECTEDTOTALAMOUNT, IGVTOTALAMOUNT, ISCTOTALAMOUNT, ROUNDINGAMOUNT, FLGPPL, DOCUMENTTYPE, POSSERIALNUMBER, CASHIERCODE, IGVPERCENTAGE, TICKETNUMBER, CUSTOMERNAME, CUSTOMERSURNAME, CUSTOMERDOCUMENTTYPE, CUSTOMERDOCUMENTNUMBER, PURCHASEORDERNUMBER, SALESNOTENUMBER, CUSTOMERBUSINESSDOCNUMBER, CUSTOMERBUSINESSNAME, SALESMANFLG, SALESMANSTORE, SALESMANCODE, PPLSENDDATE, KIOSKFLG, PAYMENTORDERNUMBER, ISDETRACTION, DETRACTIONCODE, DETRACTIONPERCENTAGE, DETRACTIONAMOUNT, CUSTOMEREMAIL, ORI_TRXDATE, ORI_BRANCHID, ORI_POSID, ORI_SEQUENCENUMBER, ORI_PPLSERIALNUMBER, ORI_DOCUMENTTYPE, DONATION, REFERENCE, CUSTOMERPHONE)
VALUES(EDSRCT2.SEQ_PIV_TRX_BCT.NEXTVAL, '005-094-000000339', 903, 103, 94, SYSDATE, 136, 1, 2, 'HE', 'USD', SYSDATE, 'P', SYSDATE, SYSDATE, 22.3, 19.39, 0, 2.91, 0, 0, 0, 'TFC', '9aa18c4395e0b737', '9524006', 0, '0', 'Yolanda', ' ', 'RUC', '0123456789012', '0', '0', '0123456789012', 'Yolanda', 0, 0, '0000000000', TIMESTAMP '2025-12-02 12:07:41.000000', NULL, NULL, '0', NULL, NULL, NULL, 'yolanda.gonzalez@promart.ec', NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, '0985230025');
COMMIT;


--buscando la SEQUENCE para el HEADID
--SEQUENCE: SEQ_PIV_TRX_BCT
SELECT sequence_name
     , min_value
     , max_value
     , increment_by
     , last_number
FROM   all_sequences
WHERE  sequence_owner = 'EDSRCT2'
AND    (
          sequence_name LIKE '%PIV_TRX_BCT_HEAD%'
       OR sequence_name LIKE '%PIV_TRX%'
       OR sequence_name LIKE '%HEAD%'
       );


