SELECT * FROM edsr.GRE_EMPRESA;
SELECT * FROM edsr.B2BACKEE2 ORDER BY B2B_ID DESC;

SELECT RCV.FEC_PROC_FIN, RCV.* FROM edsr.B2B_OC_RCV_ENVIO RCV
--UPDATE edsr.B2B_OC_RCV_ENVIO SET FEC_PROC_FIN = NULL
--WHERE pmg_po_number IN (10253,10274) AND impuesto_fin != '0';
WHERE pmg_po_number IN (121202) AND impuesto_fin != '0';
COMMIT;