SELECT hdr.TRF_NUMBER,hdr.text_request,FLG_ERROR, ID_TIPO, hdr.fec_procesado,hdr.json_response,hdr.mensaje,hdr.flg_error,hdr.*
FROM EDSR.wms_order_hdr_envio hdr
WHERE TRF_NUMBER IN (159024,159025,159023);
COMMIT;
--2025-05-27 03:03:21.000

SELECT TRF_NUMBER, FEC_PROCESADO FROM wms_order_hdr_envio bb 
ORDER BY FEC_PROCESADO DESC
FETCH FIRST 150 ROWS ONLY;

SELECT TRF_NUMBER, FEC_PROCESADO
	--,  bb.* 
FROM wms_order_hdr_envio bb 
WHERE TRF_NUMBER >=159000  AND TRF_NUMBER <=159050
ORDER BY TRF_NUMBER DESC FETCH FIRST 500 ROWS ONLY;