
--Usuarios
SELECT * FROM EDSR.PORTAL_B2B_USUARIO ;

--Proveedores
SELECT * FROM  edsr.VPCMSTEE WHERE vendor_name LIKE '%INDURAMA%';
SELECT * FROM  edsr.VPCMSTEE WHERE TRIM(VENDOR_NUMBER) = '1793039804001';

SELECT H.PMG_PO_NUMBER, H.MENSAJE,H.* 
From edsr.OC_HDR_LOAD H WHERE VENDOR_NUMBER = '1790476286001';
SELECT H.PMG_PO_NUMBER, H.MENSAJE,H.* From edsr.OC_HDR_LOAD H ORDER BY CREATED_ON DESC;
select * From edsr.OC_DTL_LOAD where ID_AUDIT_OC=247;

--GUIAS
SELECT * FROM EDSR.PORTAL_B2B_GUIA ORDER BY USR_CREACION DESC;
SELECT * FROM EPMM.PRDMSTEE;
SELECT t.COD_BAR  , t.* FROM EPMM.TPPRDMST t ;
--Consulta OC
SELECT
    PMG_DTL.PMG_PO_NUMBER AS PMG_PO_NUMBER,
    HDR.VENDOR_NUMBER AS VENDOR_NUMBER,
    PRD.PRD_LVL_NUMBER AS PRD_LVL_NUMBER,
    PRD.PRD_FULL_NAME AS DESCRIPTION,
    PRD.COD_BAR AS CODIGO_BARRAS,
    PRD.VPC_CASE_PACK_ID  AS CASE_PACK,
    DTL.QUANTITY AS QUANTITY,
    PMG_DTL.PMG_RCV_SQTY AS PMG_RCV_SQTY,
    PMG_DTL.PMG_STATUS AS PMG_STATUS
FROM EDSR.OC_HDR_LOAD HDR
INNER JOIN EDSR.OC_DTL_LOAD DTL
    ON HDR.ID_AUDIT_OC = DTL.ID_AUDIT_OC
INNER JOIN EPMM.TPPRDMST PRD
    ON TRIM(PRD.PRD_LVL_NUMBER) = TRIM(DTL.PRD_LVL_NUMBER)
INNER JOIN EPMM.PMGDTLEE PMG_DTL
    ON PMG_DTL.PMG_PO_NUMBER = '102503'
   AND PMG_DTL.PRD_LVL_CHILD = PRD.PRD_LVL_CHILD
WHERE INSTR(',' || HDR.PMG_PO_NUMBER || ',', ',' || '102503' || ',') > 0
  AND TRIM(HDR.VENDOR_NUMBER) = TRIM('1790476286001')
;

--Consultas Recepcion OC
SELECT * FROM EDSR.PORTAL_B2B_RECEPCION_OC_HDR ORDER BY ID_RECEPCION_OC_HDR desc;
SELECT * FROM EDSR.PORTAL_B2B_RECEPCION_OC_DTL;


select * From epmm.sdipmghdi WHERE AUDIT_NUMBER IN (SELECT AUDIT_NUMBER FROM edsr.tpimpocc oc WHERE oc.pmg_po_number  in (102271));
SELECT * FROM edsr.PMGHDREE WHERE PMG_PO_NUMBER in (102271);
SELECT * FROM edsr.tpimpocc oc WHERE  oc.pmg_po_number  in (102507);
SELECT * FROM EDSR.TPIMPOCD OC WHERE OC.AUDIT_NUMBER_CAB  IN (SELECT AUDIT_NUMBER FROM edsr.tpimpocc oc WHERE oc.pmg_po_number  in (102507));
select * from epmm.SDIHDIREJ h where h.pmg_po_number in (102271);
select * from epmm.sdirejcd where rej_code in( 456,715);
select * from epmm.PMGSTSCD;


WITH HDR_SPLIT AS (
    SELECT
        H.ROWID AS RID,
        H.VENDOR_NUMBER,
        H.NOTA_VENTA,
        H.PMG_PO_NUMBER AS PMG_PO_NUMBER_ORIGINAL,
        TRIM(REGEXP_SUBSTR(REPLACE(H.PMG_PO_NUMBER, ' ', ''), '[^,]+', 1, LEVEL)) AS NUMERO_OC,
        H.MENSAJE
    FROM EDSR.OC_HDR_LOAD H
    CONNECT BY REGEXP_SUBSTR(REPLACE(H.PMG_PO_NUMBER, ' ', ''), '[^,]+', 1, LEVEL) IS NOT NULL
       AND PRIOR H.ROWID = H.ROWID
       AND PRIOR SYS_GUID() IS NOT NULL
)
SELECT
    HS.VENDOR_NUMBER,
    HS.NOTA_VENTA,
    HS.PMG_PO_NUMBER_ORIGINAL,
    HS.NUMERO_OC,
    ES.PMG_STAT_NAME AS ESTADO,
    TO_CHAR(OC.PMG_ENTRY_DATE, 'DD/MM/YYYY HH24:MI:SS') AS FECHA_OC,
    HS.MENSAJE
FROM HDR_SPLIT HS
LEFT JOIN EDSR.PMGHDREE OC
       ON TRIM(OC.PMG_PO_NUMBER) = HS.NUMERO_OC
LEFT JOIN EDSR.PMGSTSCD ES
       ON ES.PMG_STAT_CODE = OC.PMG_STAT_CODE
ORDER BY /*HS.NOTA_VENTA, */HS.NUMERO_OC desc;    