CREATE SEQUENCE EDSR.SEQ_PORTAL_B2B_USUARIO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE EDSR.SEQ_PORTAL_B2B_GUIA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE EDSR.PORTAL_B2B_USUARIO (
    ID_USUARIO        NUMBER(18) DEFAULT EDSR.SEQ_PORTAL_B2B_USUARIO.NEXTVAL NOT NULL,
    CORREO            VARCHAR2(150 CHAR) NOT NULL,
    NOMBRE_COMPLETO   VARCHAR2(200 CHAR) NOT NULL,
    VENDOR_NUMBER     VARCHAR2(50 CHAR) NOT NULL,
    PASSWORD          VARCHAR2(200 CHAR) NOT NULL,
    ESTADO            CHAR(1) DEFAULT 'A' NOT NULL,
    INTENTOS_FALLIDOS NUMBER(3) DEFAULT 0 NOT NULL,
    FEC_ULTIMO_LOGIN  TIMESTAMP,
    FEC_BLOQUEO_HASTA TIMESTAMP,
    FEC_CREACION      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    USR_CREACION      VARCHAR2(50 CHAR) DEFAULT 'SYSTEM' NOT NULL,
    FEC_ACTUALIZACION TIMESTAMP,
    USR_ACTUALIZACION VARCHAR2(50 CHAR),
    CONSTRAINT PK_PORTAL_B2B_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT CK_PB2B_USR_ESTADO CHECK (ESTADO IN ('A','I','B'))
);

CREATE UNIQUE INDEX EDSR.UIX_PORTAL_B2B_USUARIO_CORREO
    ON EDSR.PORTAL_B2B_USUARIO (UPPER(CORREO));


/*
 * 
 * Guias asociadas a la RECEPCION OC
 * 
 */

CREATE TABLE EDSR.PORTAL_B2B_GUIA (
    ID_GUIA         NUMBER(18) DEFAULT EDSR.SEQ_PORTAL_B2B_GUIA.NEXTVAL NOT NULL,
    PMG_PO_NUMBER   VARCHAR2(50 CHAR) NOT NULL,
    VENDOR_NUMBER   VARCHAR2(50 CHAR) NOT NULL,
    GUIDE_NUMBER    VARCHAR2(50 CHAR) NOT NULL,
    FILE_NAME       VARCHAR2(255 CHAR) NOT NULL,
    BUCKET_NAME     VARCHAR2(150 CHAR) NOT NULL,
    STORAGE_PATH    VARCHAR2(500 CHAR) NOT NULL,
    CONTENT_TYPE    VARCHAR2(100 CHAR) NOT NULL,
    FILE_SIZE       NUMBER(18) DEFAULT 0 NOT NULL,
    ESTADO          CHAR(1) DEFAULT 'A' NOT NULL,
    FEC_CREACION    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    USR_CREACION    VARCHAR2(50 CHAR) DEFAULT 'SYSTEM' NOT NULL,
    FEC_ACTUALIZACION TIMESTAMP,
    USR_ACTUALIZACION VARCHAR2(50 CHAR),
    CONSTRAINT PK_PORTAL_B2B_GUIA PRIMARY KEY (ID_GUIA),
    CONSTRAINT CK_PB2B_GUIA_ESTADO CHECK (ESTADO IN ('A','I'))
);

--Indices
CREATE INDEX EDSR.IDX_PB2B_GUIA_01
    ON EDSR.PORTAL_B2B_GUIA (PMG_PO_NUMBER, VENDOR_NUMBER);

CREATE INDEX EDSR.IDX_PB2B_GUIA_02
    ON EDSR.PORTAL_B2B_GUIA (GUIDE_NUMBER);

--Restricciones
CREATE UNIQUE INDEX EDSR.UIX_PB2B_GUIA_01
    ON EDSR.PORTAL_B2B_GUIA (PMG_PO_NUMBER, VENDOR_NUMBER, GUIDE_NUMBER);

--Comentarios
COMMENT ON TABLE EDSR.PORTAL_B2B_GUIA IS 'Metadata de guías PDF cargadas desde el portal B2B';
COMMENT ON COLUMN EDSR.PORTAL_B2B_GUIA.PMG_PO_NUMBER IS 'Número de OC';
COMMENT ON COLUMN EDSR.PORTAL_B2B_GUIA.VENDOR_NUMBER IS 'Código de proveedor';
COMMENT ON COLUMN EDSR.PORTAL_B2B_GUIA.GUIDE_NUMBER IS 'Número de guía';
COMMENT ON COLUMN EDSR.PORTAL_B2B_GUIA.FILE_NAME IS 'Nombre del archivo';
COMMENT ON COLUMN EDSR.PORTAL_B2B_GUIA.BUCKET_NAME IS 'Nombre del bucket GCP';
COMMENT ON COLUMN EDSR.PORTAL_B2B_GUIA.STORAGE_PATH IS 'Ruta técnica del objeto dentro del bucket';
COMMENT ON COLUMN EDSR.PORTAL_B2B_GUIA.CONTENT_TYPE IS 'Tipo MIME del archivo';
COMMENT ON COLUMN EDSR.PORTAL_B2B_GUIA.FILE_SIZE IS 'Tamaño del archivo en bytes';
COMMENT ON COLUMN EDSR.PORTAL_B2B_GUIA.ESTADO IS 'A=Activo, I=Inactivo';

/*
*
*
* Recepcion de OC
*
*
**/


CREATE SEQUENCE EDSR.SEQ_PORTAL_B2B_RECEPCION_OC_HDR
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
/

CREATE TABLE EDSR.PORTAL_B2B_RECEPCION_OC_HDR (
    ID_RECEPCION_OC_HDR      NUMBER(18) DEFAULT EDSR.SEQ_PORTAL_B2B_RECEPCION_OC_HDR.NEXTVAL NOT NULL,
    PMG_PO_NUMBER            VARCHAR2(50 CHAR) NOT NULL,
    VENDOR_NUMBER            VARCHAR2(50 CHAR) NOT NULL,
    PMG_STAT_CODE            NUMBER(1) NOT NULL,
    SUPPLIER_DELIVERY_DATE   TIMESTAMP NOT NULL,
    IS_LATEST                CHAR(1) DEFAULT 'S' NOT NULL,
    OBSERVATION              VARCHAR2(500 CHAR),
    FEC_CREACION             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    USR_CREACION             VARCHAR2(50 CHAR) DEFAULT 'SYSTEM' NOT NULL,
    CONSTRAINT PK_PB2B_RECEPCION_OC_HDR PRIMARY KEY (ID_RECEPCION_OC_HDR),
    CONSTRAINT CK_PB2B_RECEP_OC_HDR_STAT CHECK (PMG_STAT_CODE IN (5, 6)),
    CONSTRAINT CK_PB2B_RECEP_OC_HDR_LAST CHECK (IS_LATEST IN ('S', 'N'))
);
/

CREATE INDEX EDSR.IDX_PB2B_RECEPCION_OC_HDR_01
    ON EDSR.PORTAL_B2B_RECEPCION_OC_HDR (PMG_PO_NUMBER, VENDOR_NUMBER, IS_LATEST);
/

CREATE SEQUENCE EDSR.SEQ_PORTAL_B2B_RECEPCION_OC_DTL
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
/

CREATE TABLE EDSR.PORTAL_B2B_RECEPCION_OC_DTL (
    ID_RECEPCION_OC_DTL      NUMBER(18) DEFAULT EDSR.SEQ_PORTAL_B2B_RECEPCION_OC_DTL.NEXTVAL NOT NULL,
    ID_RECEPCION_OC_HDR      NUMBER(18) NOT NULL,
    PRD_LVL_NUMBER           VARCHAR2(12 CHAR) NOT NULL,
    REQUESTED_QTY            NUMBER(12,0) NOT NULL,
    RECEIVED_QTY             NUMBER(12,0) NOT NULL,
    CONFIRMED_QTY            NUMBER(12,0) NOT NULL,
    CONSTRAINT PK_PB2B_RECEPCION_OC_DTL PRIMARY KEY (ID_RECEPCION_OC_DTL),
    CONSTRAINT FK_PB2B_RECEP_OC_DTL_HDR FOREIGN KEY (ID_RECEPCION_OC_HDR)
        REFERENCES EDSR.PORTAL_B2B_RECEPCION_OC_HDR (ID_RECEPCION_OC_HDR),
    CONSTRAINT CK_PB2B_RECEP_OC_DTL_REQ CHECK (REQUESTED_QTY >= 0),
    CONSTRAINT CK_PB2B_RECEP_OC_DTL_REC CHECK (RECEIVED_QTY >= 0),
    CONSTRAINT CK_PB2B_RECEP_OC_DTL_CONF CHECK (CONFIRMED_QTY >= 0),
    CONSTRAINT CK_PB2B_RECEP_OC_DTL_CONF_REC CHECK (CONFIRMED_QTY <= RECEIVED_QTY),
    CONSTRAINT CK_PB2B_RECEP_OC_DTL_CONF_REQ CHECK (CONFIRMED_QTY <= REQUESTED_QTY)
);
/

CREATE INDEX EDSR.IDX_PB2B_RECEPCION_OC_DTL_01
    ON EDSR.PORTAL_B2B_RECEPCION_OC_DTL (ID_RECEPCION_OC_HDR);
/

CREATE INDEX EDSR.IDX_PB2B_RECEPCION_OC_DTL_02
    ON EDSR.PORTAL_B2B_RECEPCION_OC_DTL (PRD_LVL_NUMBER);
/

COMMENT ON TABLE EDSR.PORTAL_B2B_RECEPCION_OC_HDR IS 'Cabecera de cargas de recepción OC desde portal B2B';
COMMENT ON COLUMN EDSR.PORTAL_B2B_RECEPCION_OC_HDR.PMG_PO_NUMBER IS 'Número de OC';
COMMENT ON COLUMN EDSR.PORTAL_B2B_RECEPCION_OC_HDR.PMG_STAT_CODE IS '5 parcial, 6 completo';
COMMENT ON COLUMN EDSR.PORTAL_B2B_RECEPCION_OC_HDR.SUPPLIER_DELIVERY_DATE IS 'Fecha de entrega informada por proveedor';
COMMENT ON COLUMN EDSR.PORTAL_B2B_RECEPCION_OC_HDR.IS_LATEST IS 'S = última recepción registrada para la OC y proveedor';

COMMENT ON TABLE EDSR.PORTAL_B2B_RECEPCION_OC_DTL IS 'Detalle de carga de recepción OC desde portal B2B';
COMMENT ON COLUMN EDSR.PORTAL_B2B_RECEPCION_OC_DTL.PRD_LVL_NUMBER IS 'SKU';
COMMENT ON COLUMN EDSR.PORTAL_B2B_RECEPCION_OC_DTL.REQUESTED_QTY IS 'Cantidad solicitada al proveedor';
COMMENT ON COLUMN EDSR.PORTAL_B2B_RECEPCION_OC_DTL.RECEIVED_QTY IS 'Cantidad recepcionada en la carga';
COMMENT ON COLUMN EDSR.PORTAL_B2B_RECEPCION_OC_DTL.CONFIRMED_QTY IS 'Cantidad confirmada para usar en PMM';
