SELECT count(1) FROM TPEPRDAE; --59 156
SELECT DISTINCT prd_lvl_child FROM TPEPRDAE; --29 581
SELECT DISTINCT TRAN_TYPE FROM TPEPRDAE; --29 581
SELECT DISTINCT ESTADO FROM TPEPRDAE; --29 581
SELECT * FROM TPEPRDAE WHERE TPEPRDAE.TRAN_TYPE  = 'D'; --29 581

SELECT * FROM TPEPRDAE ORDER BY DOWNLOAD_DATE_1  DESC;





SELECT * FROM DBA_SOURCE WHERE UPPER(TEXT) LIKE '%TPEPRDAE%';

--Listar pendientes
SELECT A.PRD_LVL_CHILD, MIN(A.TRAN_TYPE) AS TRAN_TYPE
FROM TPEPRDAE A
WHERE A.ESTADO in (0)
	AND TRAN_TYPE IN ('A', 'C')
GROUP BY A.PRD_LVL_CHILD;