
SELECT R.SUCURSAL,
       R.AREA,
       R.COD_DPTO                  "COD.DPTO",
       R.DEPARTAMENTO,
       R.LINEA,
       R.PROVEEDOR,
       R.SKU,
        R.MIN,
       R.MAX,
       R.DESCRIPCION,
       R.ESTADO,
       R.PROCEDENCIA,
       R.SUR_SUC                   "SUR.SUC",
       R.SUR_SKU                   "SUR.SKU",
       R.FEC_INICIO                "FEC.INICIO",
       R.FEC_FIN                   "FEC.FIN",
       R.ESTADO_MATRIZ,
       R.COSTO_MEDIO_VARIABLE_MV   "Costo Medio Variable MV",
       R.FECHA_INGRESO_SURTIDO_SAS "FECHA INGRESO SURTIDO SAS",
       R.UND_SEM1                  "UND.SEM1",
       R.UND_SEM2                  "UND.SEM2",
       R.UND_SEM3                  "UND.SEM3",
       R.UND_SEM4                  "UND.SEM4",
       R.UND_SEM5                  "UND.SEM5",
       R.UND_SEM6                  "UND.SEM6",
       R.UND_SEM7                  "UND.SEM7",
       R.UND_SEM8                  "UND.SEM8",
       (R.TOT_VTA_UNID - R.UND_ORI_DIF_8S) / 8 "Prom.Vta.Unid.Tda",
       R.TOT_VTA_UNID  "Tot.Vta.Unid",
       R.TOT_VTA_DOLARES "Tot.Vta.Dolares",
       R.STOCK,
       R.OC,
       R.TRANSF,
       R.MP,
       R.DIAS_REV      "Dias Rev",
       R.DIAS_PROCESO  "Dias Proceso",
       R.RPL_DESC      "RPL DESC",
       R.DMT_DESC      "DMT DESC",
       R.DISPONIBLE_CD_851 "Disponible CD 851",
       R.OC_CD_851      "OC CD 851",
       R.TIPO_REP            "TIPO REP",
       R.EXHIBICION,
       R.FACTOR,
       R.INICIO,
       R.FIN,
       R.ATRIBUTO_BIG_TICKET "Atributo Big Ticket",
       R.TIPO_REDONDEO_RPL   "Tipo Redondeo RPL",
       R.PROM_VTA_UNID "Prom.Vta.Unid",
       R.FLAG_INFALTABLE "Infaltable",
       R.DES_ATR_TOP_2K "TOP 2K",
       R.SKU_ANTIGUO,
       R.DES_SKU_ANTIGUO,
       R.MP_CD PACK_CD,
       TO_CHAR(R.FEC_ACT_REPORTE, 'DD/MM/YYYY HH24:MI:SS') "Fec.Act.Reporte"
  FROM EDSR.HPREP8SEMANAS_FULL R
 INNER JOIN EDSR.tpprdmst P
    ON P.PRD_LVL_NUMBER = r.sku
 WHERE R.SUCURSAL = '101'
	AND R.SKU = '10535'
;
