SELECT P.PRD_LVL_NUMBER SKU,
       P.PRD_FULL_NAME DECRIPCION,
       P.COD_DIV || ' - ' || P.DES_DIV DIVISION,
       P.COD_AREA || ' - ' || P.DES_AREA AREA,
       P.COD_DPTO || ' - ' || P.DES_DPTO DEPARTAMENTO,
       P.COD_LIN || ' - ' || P.DES_LIN LINEA,
       O.ORG_LVL_NUMBER SUCURSAL,
       O.ORG_NAME_FULL DESCRIPCION,
       T.INV_TYPE_CODE || ' - ' || T.INV_TYPE_DESC "TIPO INV",
       I.ON_HAND_QTY,
       I.ON_HAND_COST,
       I.PO_ORD_QTY,
       I.PO_ORD_COST,
       I.PO_INTRN_QTY,
       I.PO_INTRN_COST
  FROM EPMM.INVBALEE I
 INNER JOIN EDSR.TPPRDMST P
    ON I.PRD_LVL_CHILD = P.PRD_LVL_CHILD
 INNER JOIN EPMM.INVTYPEE T
    ON I.INV_TYPE_CODE = T.INV_TYPE_CODE
 INNER JOIN EPMM.ORGMSTEE O
    ON I.ORG_LVL_CHILD = O.ORG_LVL_CHILD
 WHERE P.COD_DIV = CASE WHEN '@DIV (0=TODAS)@' = '0' THEN P.COD_DIV ELSE '@DIV (0=TODAS)@' END
   AND P.COD_AREA = CASE WHEN '@AREA (0=TODAS)@' = '0' THEN P.COD_AREA ELSE '@AREA (0=TODAS)@' END
   AND P.COD_DPTO = CASE WHEN '@DPTO (0=TODAS)@' = '0' THEN P.COD_DPTO ELSE '@DPTO (0=TODAS)@' END
   AND P.COD_LIN = CASE WHEN '@LINEA (0=TODAS)@' = '0' THEN P.COD_LIN ELSE '@LINEA (0=TODAS)@' END
   AND P.PRD_LVL_NUMBER = CASE WHEN '@SKU (0=TODAS)@' = '0' THEN P.PRD_LVL_NUMBER ELSE '@SKU (0=TODAS)@' END
   AND O.ORG_LVL_NUMBER = CASE WHEN @SUCURSAL (0=TODAS)@ = 0 THEN O.ORG_LVL_NUMBER ELSE @SUCURSAL (0=TODAS)@ END
 ORDER BY P.PRD_LVL_NUMBER, O.ORG_LVL_NUMBER, T.INV_TYPE_CODE