/*

Se hace insert a las siguientes tablas:
En el siguiente orden: ya que hay un CONSTRAIN FK_GRE_PUNTO_EMISION_ESTAB de GRE_PUNTO_EMISION donde indica que el ORG_LVL_CHILD es FK de GRE_ESTABLECIMIENTO
GRE_ESTABLECIMIENTO
GRE_PUNTO_EMISION

*/
SELECT * FROM edsr.ORGMSTEE WHERE ORG_LVL_NUMBER IN (851,101,102,103,104);
SELECT * FROM edsr.ORGMSTEE WHERE ORG_LVL_CHILD IN (420,419,423,481,482);
SELECT * FROM edsr.GRE_ESTABLECIMIENTO;
SELECT * FROM edsr.GRE_PUNTO_EMISION;


--UIO GRANADOS
INSERT INTO EDSR.GRE_PUNTO_EMISION (ID_PUNTO_EMISION, ORG_LVL_CHILD, COD_PUNTO_EMISION, SECUENCIAL, FLG_DEFAULT, CH_ESTADO) 
VALUES (3, 423, '001', 0, '1', '1');
COMMIT;

--UIO CARAPUNGO
INSERT INTO EDSR.GRE_ESTABLECIMIENTO
(ORG_LVL_CHILD, COD_ESTABLECIMIENTO, VC_DIRECCION, NU_ID_EMPRESA, CH_RED_EXTERNA, VC_CANTON)
VALUES(481, '005', 'PICHINCHA / QUITO / CARAPUNGO/ CALLE PADRE LUIS VACCARI S/N Y RÍO AMAZONAS', 1, '0', 'QUITO');

INSERT INTO EDSR.GRE_PUNTO_EMISION (ID_PUNTO_EMISION, ORG_LVL_CHILD, COD_PUNTO_EMISION, SECUENCIAL, FLG_DEFAULT, CH_ESTADO) 
VALUES (4, 481, '001', 0, '1', '1');
COMMIT;

--UIO SAMBORONDON (Solo falta la direccion)
INSERT INTO EDSR.GRE_ESTABLECIMIENTO
(ORG_LVL_CHILD, COD_ESTABLECIMIENTO, VC_DIRECCION, NU_ID_EMPRESA, CH_RED_EXTERNA, VC_CANTON)
VALUES(482, '006', 'GUAYAS/ SAMBORONDON/ LA PUNTILLA/ KM. 9.5 VIA SAMBORONDON', 1, '0', 'SAMBORONDON');

INSERT INTO EDSR.GRE_PUNTO_EMISION (ID_PUNTO_EMISION, ORG_LVL_CHILD, COD_PUNTO_EMISION, SECUENCIAL, FLG_DEFAULT, CH_ESTADO) 
VALUES (5, 482, '001', 0, '1', '1');
COMMIT;

