--PERMISOS QA
GRANT SELECT ON EDSR.SEQ_inv_break TO USR_CHECK_STOCK_QA;
GRANT SELECT ON EDSR.SEQ_inv_location TO USR_CHECK_STOCK_QA;
GRANT SELECT ON EDSR.SEQ_inv_location_dtl TO USR_CHECK_STOCK_QA;
 
GRANT SELECT, INSERT, UPDATE ON EDSR.invbreak TO USR_CHECK_STOCK_QA;
GRANT SELECT, INSERT, UPDATE, DELETE ON EDSR.invlocation TO USR_CHECK_STOCK_QA;
GRANT SELECT, INSERT, UPDATE, DELETE ON EDSR.invlocationdtl TO USR_CHECK_STOCK_QA;
 
INSERT INTO EDSR.invbreak (prd_lvl_number,ORG_lvl_number,break) VALUES ('1001','101','Home');
SELECT * FROM EDSR.invbreak ORDER BY ID DESC;
SELECT * FROM EDSR.invbreak WHERE PRD_LVL_NUMBER = '21555';

SELECT * FROM PRDMSTEE WHERE PRD_LVL_NUMBER = '21555';
SELECT * FROM PRDMSTEE WHERE PRD_LVL_NUMBER = '21556';
SELECT * FROM ORGMSTEE;

--
SELECT * FROM EDSR.invbreak
-- UPDATE EDSR.invbreak SET PRD_LVL_NUMBER = ''
WHERE PRD_LVL_NUMBER = '21590';
COMMIT;




--API GETBREAK
SELECT PRD_LVL_NUMBER, ORG_LVL_NUMBER, BREAK
FROM INVBREAK
WHERE ORG_LVL_NUMBER = '101' AND PRD_LVL_NUMBER = '1001'
;

SELECT SEQ_inv_break.nextval AS SEC FROM dual;

-- CREATE OBJECTS
DROP SEQUENCE SEQ_inv_break;
DROP TABLE invbreak;

CREATE SEQUENCE EDSR.SEQ_inv_break
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE EDSR.invbreak (
    id NUMBER DEFAULT EDSR.SEQ_inv_break.NEXTVAL PRIMARY KEY NOT NULL,
    prd_lvl_number VARCHAR2(25) NOT NULL,
    ORG_lvl_number VARCHAR2(30) NOT NULL, 
    break VARCHAR2(15) NOT NULL,
    quantity NUMBER NOT NULL,
    registerDate DATE DEFAULT SYSDATE,
    modifyDate DATE,
    USERNAME VARCHAR2(120),
);

ALTER TABLE EDSR.invbreak ADD (quantity NUMBER);


