--PRODUCTO
SELECT P.PRD_LVL_NUMBER, UPC.PRD_UPC FROM EPMM.PRDMSTEE P
	INNER JOIN EPMM.PRDUPCEE UPC ON P.PRD_LVL_CHILD = UPC.PRD_LVL_CHILD
	LEFT JOIN EPMM.PRDUPCAE A ON UPC.PRD_UPC = A.PRD_UPC AND A.AUDIT_TYPE = 'A'
WHERE 	UPC.PRODUCT_UPC = 'T'
 		AND UPC.PRD_PRIMARY_FLAG = 'T'
		AND PRD_LVL_NUMBER IN ('21555');

--QUIEBRES
SELECT * FROM EDSR.invbreak BREAK
-- UPDATE EDSR.invbreak BREAK SET PRD_LVL_NUMBER = '10025', REGISTERDATE = SYSDATE
WHERE
	--BREAK.PRD_LVL_NUMBER = '21555' AND
	BREAK.REGISTERDATE < TRUNC(sysdate) + 1
	AND BREAK.REGISTERDATE >= TRUNC(sysdate)
ORDER BY registerdate DESC
;
COMMIT;

--UBICACIONES
SELECT DISTINCT L.PRD_LVL_NUMBER  FROM EDSR.invlocation L;
SELECT LDTL.ID, LDTL.LOCATION, LDTL.CURR_QTY
FROM EDSR.invlocation L
	INNER JOIN EDSR.invlocationdtl LDTL ON L.PRD_LVL_NUMBER = LDTL.PRD_LVL_NUMBER
WHERE L.org_lvl_number = '101' AND L.PRD_LVL_NUMBER = '21590';

DECLARE
    v_old_sku VARCHAR2(25) := '1002';  -- SKU actual
    v_new_sku VARCHAR2(25) := '10030';  -- Nuevo SKU
BEGIN
    UPDATE EDSR.invlocationdtl
    SET prd_lvl_number = v_new_sku,
        modifyDate = SYSDATE
    WHERE prd_lvl_number = v_old_sku;

    UPDATE EDSR.invlocation
    SET prd_lvl_number = v_new_sku,
        modifyDate = SYSDATE
    WHERE prd_lvl_number = v_old_sku;

    COMMIT;
END;
/

SELECT * FROM  EDSR.HPREP8SEMANAS_FULL FETCH FIRST 10 ROWS ONLY;
SELECT * FROM  EDSR.HPREP8SEMANAS_FULL WHERE SKU = '21555';
SELECT DISTINCT DES_ATR_TOP_2K FROM  EDSR.HPREP8SEMANAS_FULL;
SELECT SKU, STOCK FROM  EDSR.HPREP8SEMANAS_FULL WHERE STOCK > 0;
SELECT DISTINCT TOT_VTA_DOLARES FROM  EDSR.HPREP8SEMANAS_FULL;
SELECT DISTINCT TOT_VTA_UNID FROM  EDSR.HPREP8SEMANAS_FULL;

SELECT
	R.SUCURSAL,
    R.SKU,
    R.DESCRIPCION,
    R.AREA,
    R.LINEA,
    R.TOT_VTA_UNID "Total 8 semanas UND",
    R.TOT_VTA_DOLARES "Total 8 semanas $$$",
    R.STOCK "Stock Disponible OH",
    R.MP "MASTER PACK",
    R.ESTADO,
   R.PROCEDENCIA ,
   R.TIPO_REP "Tipo Reposición",
   R.DES_ATR_TOP_2K "Top 2k",
   R.PROVEEDOR,
    -- Quiebre
    BREAK.BREAK "Tipo Quiebre",
    BREAK.QUANTITY "Cantidad",
    BREAK.REGISTERDATE "Hora Quiebre",
    -- Ubicaciones WMS y Cantidades en ubicaciones
    MAX(CASE WHEN UB.rn = 1 THEN UB.LOCATION END) AS UBICACION1,
    MAX(CASE WHEN UB.rn = 1 THEN UB.CURR_QTY END) AS CANTIDAD1,
    MAX(CASE WHEN UB.rn = 2 THEN UB.LOCATION END) AS UBICACION2,
    MAX(CASE WHEN UB.rn = 2 THEN UB.CURR_QTY END) AS CANTIDAD2,
    MAX(CASE WHEN UB.rn = 3 THEN UB.LOCATION END) AS UBICACION3,
    MAX(CASE WHEN UB.rn = 3 THEN UB.CURR_QTY END) AS CANTIDAD3,
    MAX(CASE WHEN UB.rn = 4 THEN UB.LOCATION END) AS UBICACION4,
    MAX(CASE WHEN UB.rn = 4 THEN UB.CURR_QTY END) AS CANTIDAD4,
    MAX(CASE WHEN UB.rn = 5 THEN UB.LOCATION END) AS UBICACION5,
    MAX(CASE WHEN UB.rn = 5 THEN UB.CURR_QTY END) AS CANTIDAD5,
    MAX(CASE WHEN UB.rn = 6 THEN UB.LOCATION END) AS UBICACION6,
    MAX(CASE WHEN UB.rn = 6 THEN UB.CURR_QTY END) AS CANTIDAD6,
    MAX(CASE WHEN UB.rn = 7 THEN UB.LOCATION END) AS UBICACION7,
    MAX(CASE WHEN UB.rn = 7 THEN UB.CURR_QTY END) AS CANTIDAD7,
    MAX(CASE WHEN UB.rn = 8 THEN UB.LOCATION END) AS UBICACION8,
    MAX(CASE WHEN UB.rn = 8 THEN UB.CURR_QTY END) AS CANTIDAD8,
    MAX(CASE WHEN UB.rn = 9 THEN UB.LOCATION END) AS UBICACION9,
    MAX(CASE WHEN UB.rn = 9 THEN UB.CURR_QTY END) AS CANTIDAD9,
    MAX(CASE WHEN UB.rn = 10 THEN UB.LOCATION END) AS UBICACION10,
    MAX(CASE WHEN UB.rn = 10 THEN UB.CURR_QTY END) AS CANTIDAD10
FROM
    EDSR.HPREP8SEMANAS_FULL R
INNER JOIN EPMM.PRDMSTEE P ON R.SKU = TRIM(P.PRD_LVL_NUMBER)
INNER JOIN EPMM.ORGMSTEE O ON R.SUCURSAL = O.ORG_LVL_NUMBER
INNER JOIN EPMM.PRDUPCEE UPC ON UPC.PRD_LVL_CHILD = P.PRD_LVL_CHILD
LEFT JOIN EPMM.PRDUPCAE A ON UPC.PRD_UPC = A.PRD_UPC AND A.AUDIT_TYPE = 'A'
LEFT JOIN EDSR.invbreak BREAK ON BREAK.PRD_LVL_NUMBER = TRIM(P.PRD_LVL_NUMBER)  AND BREAK.ORG_LVL_NUMBER = R.SUCURSAL
/*LEFT JOIN EDSR.invlocation L ON L.PRD_LVL_NUMBER = TRIM(P.PRD_LVL_NUMBER)
LEFT JOIN EDSR.invlocationdtl LDTL ON L.PRD_LVL_NUMBER = LDTL.PRD_LVL_NUMBER*/
LEFT JOIN (
    SELECT 
        LDTL.PRD_LVL_NUMBER,
        LDTL.ORG_LVL_NUMBER,
        LDTL.LOCATION,
        LDTL.CURR_QTY,
        ROW_NUMBER() OVER (
            PARTITION BY LDTL.PRD_LVL_NUMBER, LDTL.ORG_LVL_NUMBER 
            ORDER BY LDTL.LOCATION
        ) AS rn
    FROM 
        EDSR.invlocationdtl LDTL
    WHERE
        LDTL.ORG_LVL_NUMBER IN ('101','102')
) UB 
ON UB.PRD_LVL_NUMBER = R.SKU AND UB.ORG_LVL_NUMBER = R.SUCURSAL
WHERE
    R.SUCURSAL IN ('101','102') --  ('@Sucursal (0=TODAS)@' = '0' OR TO_CHAR(R.SUCURSAL) = '@Sucursal (0=TODAS)@')
    AND UPC.PRD_UPC IN(6921041102970,7861041148761,7450119365997,7450119365928,7450119365850) --7861041148761,,7450119365997,7450119365928,7450119365850
    AND UPC.PRODUCT_UPC = 'T'
    AND UPC.PRD_PRIMARY_FLAG = 'T'
    --AND BREAK.REGISTERDATE >= TO_DATE('20250414','YYYYMMDD') --TO_DATE(@Fec.Ini (YYYYMMDD)@, 'YYYYMMDD')
    --AND BREAK.REGISTERDATE < TO_DATE('20250415','YYYYMMDD') + 1 --TO_DATE(@Fec.Fin (YYYYMMDD)@, 'YYYYMMDD') + 1
GROUP BY 
    R.SUCURSAL,
    R.SKU,
    R.DESCRIPCION,
    R.AREA,
    R.LINEA,
    R.TOT_VTA_UNID,
    R.TOT_VTA_DOLARES,
    R.STOCK,
    R.MP,
    R.ESTADO,
    R.PROCEDENCIA,
    R.TIPO_REP,
    R.DES_ATR_TOP_2K,
    R.PROVEEDOR,
    BREAK.BREAK,
    BREAK.QUANTITY,
    BREAK.REGISTERDATE
ORDER BY 
    R.SKU;

SELECT * FROM EDSR.HPREP8SEMANAS_FULL R WHERE SKU IN ('21555');
SELECT * FROM EDSR.invlocationdtl R WHERE prd_lvl_number IN ('21555');
SELECT * FROM EDSR.invbreak R WHERE prd_lvl_number IN ('21555');
SELECT * FROM EDSR.invbreak R WHERE org_lvl_number IN ('101','102');
----------------------------------------------
-- PROBAR PARAMETROS DEL JSATELITE
----------------------------------------------
--PROBANDO SUCURSALES
SELECT * FROM EPMM.ORGMSTEE WHERE '0' = '0' OR TO_CHAR(ORG_LVL_NUMBER) = '0';

SELECT * FROM EPMM.ORGMSTEE
WHERE ('@Sucursal (0=TODAS)@' = '0' OR TO_CHAR(ORG_LVL_NUMBER) = '@Sucursal (0=TODAS)@')

--PROBANDO FECHAS
SELECT * FROM EDSR.invbreak 
WHERE REGISTERDATE >= TO_DATE('20250416','YYYYMMDD') AND REGISTERDATE < TO_DATE('20250417','YYYYMMDD');

SELECT * FROM EDSR.invbreak
WHERE REGISTERDATE >= TO_DATE(@Fec.Ini (YYYYMMDD)@, 'YYYYMMDD')
    AND REGISTERDATE < TO_DATE(@Fec.Fin (YYYYMMDD)@, 'YYYYMMDD') + 1;
-----------------------
-- version JSATELITE
------------------------
SELECT
    R.SUCURSAL,
    R.SKU,
    R.DESCRIPCION,
    R.AREA,
    R.LINEA,
    R.TOT_VTA_UNID AS "Total 8 semanas UND",
    R.TOT_VTA_DOLARES AS "Total 8 semanas $$$",
    R.STOCK AS "Stock Disponible OH",
    R.MP AS "MASTER PACK",
    R.ESTADO,
    R.PROCEDENCIA,
    R.TIPO_REP AS "Tipo Reposición",
    R.DES_ATR_TOP_2K AS "Top 2k",
    R.PROVEEDOR,
    BREAK.BREAK AS "Tipo Quiebre", 
    BREAK.REGISTERDATE AS "Hora Quiebre",
    MAX(CASE WHEN UB.rn = 1 THEN UB.LOCATION END) AS UBICACION1,
    MAX(CASE WHEN UB.rn = 1 THEN UB.CURR_QTY END) AS CANTIDAD1,
    MAX(CASE WHEN UB.rn = 2 THEN UB.LOCATION END) AS UBICACION2,
    MAX(CASE WHEN UB.rn = 2 THEN UB.CURR_QTY END) AS CANTIDAD2,
    MAX(CASE WHEN UB.rn = 3 THEN UB.LOCATION END) AS UBICACION3,
    MAX(CASE WHEN UB.rn = 3 THEN UB.CURR_QTY END) AS CANTIDAD3,
    MAX(CASE WHEN UB.rn = 4 THEN UB.LOCATION END) AS UBICACION4,
    MAX(CASE WHEN UB.rn = 4 THEN UB.CURR_QTY END) AS CANTIDAD4,
    MAX(CASE WHEN UB.rn = 5 THEN UB.LOCATION END) AS UBICACION5,
    MAX(CASE WHEN UB.rn = 5 THEN UB.CURR_QTY END) AS CANTIDAD5,
    MAX(CASE WHEN UB.rn = 6 THEN UB.LOCATION END) AS UBICACION6,
    MAX(CASE WHEN UB.rn = 6 THEN UB.CURR_QTY END) AS CANTIDAD6,
    MAX(CASE WHEN UB.rn = 7 THEN UB.LOCATION END) AS UBICACION7,
    MAX(CASE WHEN UB.rn = 7 THEN UB.CURR_QTY END) AS CANTIDAD7,
    MAX(CASE WHEN UB.rn = 8 THEN UB.LOCATION END) AS UBICACION8,
    MAX(CASE WHEN UB.rn = 8 THEN UB.CURR_QTY END) AS CANTIDAD8,
    MAX(CASE WHEN UB.rn = 9 THEN UB.LOCATION END) AS UBICACION9,
    MAX(CASE WHEN UB.rn = 9 THEN UB.CURR_QTY END) AS CANTIDAD9,
    MAX(CASE WHEN UB.rn = 10 THEN UB.LOCATION END) AS UBICACION10,
    MAX(CASE WHEN UB.rn = 10 THEN UB.CURR_QTY END) AS CANTIDAD10
FROM
    EDSR.HPREP8SEMANAS_FULL R
INNER JOIN EPMM.PRDMSTEE P 
    ON R.SKU = TRIM(P.PRD_LVL_NUMBER)
INNER JOIN EPMM.ORGMSTEE O 
    ON R.SUCURSAL = O.ORG_LVL_NUMBER
INNER JOIN EPMM.PRDUPCEE UPC 
    ON UPC.PRD_LVL_CHILD = P.PRD_LVL_CHILD
LEFT JOIN EPMM.PRDUPCAE A 
    ON UPC.PRD_UPC = A.PRD_UPC AND A.AUDIT_TYPE = 'A'
LEFT JOIN EDSR.invbreak BREAK 
    ON BREAK.PRD_LVL_NUMBER = TRIM(P.PRD_LVL_NUMBER)
   AND BREAK.ORG_LVL_NUMBER = R.SUCURSAL
LEFT JOIN (
    SELECT 
        LDTL.PRD_LVL_NUMBER,
        LDTL.ORG_LVL_NUMBER,
        LDTL.LOCATION,
        LDTL.CURR_QTY,
        ROW_NUMBER() OVER (
            PARTITION BY LDTL.PRD_LVL_NUMBER, LDTL.ORG_LVL_NUMBER 
            ORDER BY LDTL.LOCATION
        ) AS rn
    FROM EDSR.invlocationdtl LDTL
    WHERE LDTL.ORG_LVL_NUMBER = '101'
) UB 
    ON UB.PRD_LVL_NUMBER = R.SKU 
   AND UB.ORG_LVL_NUMBER = R.SUCURSAL
WHERE
    UPC.PRODUCT_UPC = 'T'
    AND UPC.PRD_PRIMARY_FLAG = 'T'
    AND R.SUCURSAL = '101'
    AND BREAK.REGISTERDATE >= TO_DATE('20250414','YYYYMMDD')
    AND BREAK.REGISTERDATE < TO_DATE('20250416','YYYYMMDD')
GROUP BY 
    R.SUCURSAL,
    R.SKU,
    R.DESCRIPCION,
    R.AREA,
    R.LINEA,
    R.TOT_VTA_UNID,
    R.TOT_VTA_DOLARES,
    R.STOCK,
    R.MP,
    R.ESTADO,
    R.PROCEDENCIA,
    R.TIPO_REP,
    R.DES_ATR_TOP_2K,
    R.PROVEEDOR,
    BREAK.BREAK,
    BREAK.REGISTERDATE
ORDER BY R.SKU
;

----------------------------------------------
--VERSION OLD
----------------------------------------------
SELECT R.SKU,
	   R.DESCRIPCION,
  	   R.AREA,
  	   R.LINEA,
  	   R.TOT_VTA_UNID "Total 8 semanas UND",
  	   R.TOT_VTA_DOLARES "Total 8 semanas $$$",
  	   R.STOCK "Stock Disponible OH", --sila
  	   R.MP "MASTER PACK",
  	   'Ubicaciones WMS', --yala
	   'Cantidad en ubicación WMS', --yala
	   R.ESTADO,
	   R.PROCEDENCIA ,
	   R.TIPO_REP "Tipo Reposición",
	   R.DES_ATR_TOP_2K "Top 2k",
       R.PROVEEDOR,
	   BREAK.BREAK "Tipo Quiebre", 
	   BREAK.REGISTERDATE "Hora Quiebre"
FROM EDSR.HPREP8SEMANAS_FULL R
	INNER JOIN EPMM.PRDMSTEE P ON R.SKU = TRIM(P.PRD_LVL_NUMBER)
	INNER JOIN EPMM.ORGMSTEE O ON R.SUCURSAL = O.ORG_LVL_NUMBER
	INNER JOIN EPMM.PRDUPCEE UPC ON UPC.PRD_LVL_CHILD = P.PRD_LVL_CHILD
	LEFT JOIN EPMM.PRDUPCAE A ON UPC.PRD_UPC = A.PRD_UPC AND A.AUDIT_TYPE = 'A'
	LEFT JOIN EDSR.invbreak BREAK ON BREAK.PRD_LVL_NUMBER = TRIM(P.PRD_LVL_NUMBER)
	INNER JOIN EDSR.invlocationdtl LDTL ON L.PRD_LVL_NUMBER = LDTL.PRD_LVL_NUMBER
WHERE
  R.SUCURSAL = '101' --:sucursal
  AND UPC.PRD_UPC = 7861041148761 --:eanSku
  AND UPC.PRODUCT_UPC = 'T'
  AND UPC.PRD_PRIMARY_FLAG = 'T'
  AND BREAK.REGISTERDATE < TRUNC(SYSDATE) + 1 
  AND BREAK.REGISTERDATE >= TRUNC(SYSDATE)
;

 ;

 	      /*
	   'final',
		R.*
  	   EDSR.TP_PKG_GEN_FUNCIONES.FN_OBTIENE_PRC_VIGENTE(P.PRD_LVL_CHILD,O.ORG_LVL_CHILD) PVP,
       R.STOCK,
       R.TOT_VTA_UNID,
       R.UND_ORI_DIF_8S,
       (R.TOT_VTA_UNID - R.UND_ORI_DIF_8S) / 8 "Prom.Vta.Unid.Tda",
       R.TOT_VTA_UNID,
       R.MIN,
       R.MAX,
       R.MP,
       R.OC,
       R.TRANSF,
       R.DISPONIBLE_CD_851 "Disponible CD 851",
       UPC.PRD_UPC "FINAL",*/
 
 /*
  LEFT JOIN epmm.vpcprdee C
    ON c.vpc_prd_tech_key = P.vpc_prd_tech_key
   and c.vpc_tech_key = P.vpc_tech_key
 */
/*

21555 => 6921041102970
10006 => 2000001358481

21551 => 6921041102406
21552 => 6921041102383
21553 => 6921041101782
21557 => 6921041103724
21558 => 6921041103731
21559 => 6921041103748

 */

ALTER TABLE edsr.invbreak
ADD username VARCHAR2(120);

SELECT * FROM PRDMSTEE WHERE PRD_LVL_NUMBER = '21555'; --6921041102970
; --2000001358481
SELECT PRD.PRD_LVL_NUMBER , UPC.PRD_UPC
FROM edsr.PRDUPCEE UPC 
INNER JOIN edsr.PRDMSTEE PRD ON UPC.PRD_LVL_CHILD = PRD.PRD_LVL_CHILD
 WHERE UPC.PRD_PRIMARY_FLAG = 'T' AND
 		UPC.UPC_TYPE = '13  ' AND
	PRD.PRD_LVL_NUMBER IN ('21581','21582','21583','21584','21585','21586','21587','21588','21589','21590','21593','21594','21598','21600','21872','21878','21893','21910','21912','21913');

SELECT * FROM PRDUPCEE ORDER BY PRD_UPC DESC FETCH FIRST 10 ROWS ONLY;
SELECT * FROM PRDUPCAE ORDER BY AUDIT_DATE DESC FETCH FIRST 10 ROWS ONLY;


