select * from epmm.pmgstscd where pmg_stat_code IN (4,6,7);
/*
419	101	GYE ORELLANA
423	102	UIO GRANADOS
420	851	CD GUAYAQUIL

RTV_STATUS_ID	RTV_STS_DESC
0	Trabajo
1	Autorización pendiente
2	Autorizado
3	Liberado para recoger
4	Recogido
5	Despachado
6	Completado
7	En Manifiesto
8	Cancelado
10	Trabajo en tienda
11	Despachado en tienda

 */
--API RESPUESTA
SELECT B2B_DOWNLOAD_DATE,ACK.* FROM edsr.B2BACKEE2 ACK ORDER BY B2B_ID DESC;

-- CONSULTA OC
SELECT  PMG.PRIM_ORG_LVL_number AS Tienda, PMG.PMG_PO_NUMBER AS OC,PMG.PMG_STAT_CODE,STS.PMG_STAT_NAME, 
	PMG.VPC_TECH_KEY ProveedorID,TRIM(VPC.VENDOR_NUMBER) AS Codigo_Proveedor,VPC.VENDOR_NAME AS Nombre_Proveedor, PMG.* 
FROM EPMM.PMGHDREE PMG
	INNER JOIN EPMM.VPCMSTEE VPC ON VPC.VPC_TECH_KEY = PMG.VPC_TECH_KEY
	LEFT JOIN epmm.pmgstscd STS ON STS.PMG_STAT_CODE = PMG.PMG_STAT_CODE
--UPDATE edsr.B2B_OC_RCV_ENVIO B2B SET B2B.FEC_PROC_FIN = NULL
WHERE PMG_PO_NUMBER IN (175653)
--AND PMG.PMG_STAT_CODE = 1
;
COMMIT
;

-- B2B FINANCIERO
SELECT RCV.FEC_PROC_FIN, RCV.* FROM edsr.B2B_OC_RCV_ENVIO RCV
--UPDATE edsr.B2B_OC_RCV_ENVIO SET FEC_PROC_FIN = NULL
--WHERE pmg_po_number IN (10253,10274) AND impuesto_fin != '0';
WHERE pmg_po_number IN (175653) AND impuesto_fin != '0'; --2025-05-12 12:05:01.000
COMMIT;

-- B2B LOGISTICO
select FEC_PROC_LOG,RCV.* from edsr.B2B_OC_RCV_ENVIO RCV
--UPDATE edsr.B2B_OC_RCV_ENVIO SET FEC_PROC_LOG = null
WHERE pmg_po_number IN (164555) AND impuesto_fin = '0';
COMMIT;



/* 
 * DIRECTORY: El directorio es TP_FILE_B2B_FIN_CQ donde graba los archivos XML
 * generados en TP_PKG_ARCHIVOS_B2B.sp_genera_archivo_xml_oc_recep_fin
 * Dentro de su SP sp_genera_archivo_xml (Aquí hace el armado del XML)
 * Dentro del SP EDSR.SP_GEN_FILE_XML (Aquí graba el XML en el DIRECTORY)
 * RUTA: /prochp/interfaces/hpsa/b2b/integracion/output/log/cq
*/
SELECT directory_name, directory_path --, dir.*
FROM dba_directories dir
WHERE dir.directory_name = 'TP_FILE_B2B_FIN_CQ';

--B2B FINANCIERO
SELECT PMG.PMG_PO_NUMBER, B2B.FEC_PROC_FIN AS B2B_FINANCIERO, PMG.VPC_TECH_KEY ProveedorID,TRIM(VPC.VENDOR_NUMBER),
VPC.VENDOR_NAME,STS.PMG_STAT_NAME ,PMG.PMG_STAT_CODE, PMG.* 
FROM EPMM.PMGHDREE PMG 
	INNER JOIN EPMM.VPCMSTEE VPC ON VPC.VPC_TECH_KEY = PMG.VPC_TECH_KEY
	LEFT JOIN epmm.pmgstscd STS ON STS.PMG_STAT_CODE = PMG.PMG_STAT_CODE
	LEFT JOIN edsr.B2B_OC_RCV_ENVIO B2B ON B2B.PMG_PO_NUMBER = PMG.PMG_PO_NUMBER
--UPDATE edsr.B2B_OC_RCV_ENVIO B2B SET B2B.FEC_PROC_FIN = NULL
WHERE  B2B.impuesto_fin != '0' 
	AND B2B.PMG_PO_NUMBER IN (120787) ;
COMMIT;

SELECT * FROM VPCMSTEE FETCH FIRST 1 ROWS ONLY; --PROVEEDOR
SELECT * FROM edsr.GRE_EMPRESA;




SELECT * FROM EPMM.PMGDTLEE WHERE PMG_PO_NUMBER IN (146490);

SELECT * FROM EDSR.WMS_MODELO_REQUEST WHERE MODELO LIKE '%146490%'
AND FEC_REG 
;

--CREACION DE OCs al B2B desde WMS
SELECT * FROM B2B_OC_ENVIO WHERE NOMBRE_ARCHIVO LIKE '%177448%';
SELECT * FROM B2B_OC_ENVIO WHERE NOMBRE_ARCHIVO LIKE '%177469%';
SELECT * FROM B2B_OC_ENVIO WHERE NOMBRE_ARCHIVO LIKE '%177447%';

SELECT * FROM WMS_MODELO_REQUEST 
WHERE
	--ID_TIPO = 2 AND
	--AND FEC_REG >= TO_DATE('2025-04-03', 'YYYY-MM-DD')
	--AND FEC_REG < TO_DATE('2025-04-04', 'YYYY-MM-DD')
	 --MODELO LIKE '%NAC000941449%'
	IDENTIFICADOR LIKE '%NAC000941449%'
;
SELECT * FROM WMS_MODELO_REQUEST  
WHERE WMS_MODELO_REQUEST.IDENTIFICADOR IN ('OS85100018501','OS85100018541')
ORDER BY IDENTIFICADOR, FEC_REG
;

--ASN
SELECT DOWNLOAD_DATE_1,ERR_CODE, substr(shipment_nbr, 1, 2), shipment_nbr ,HDR.* FROM WMS_RCV_ASN_HDR HDR
--UPDATE WMS_RCV_ASN_HDR SET DOWNLOAD_DATE_1 = null, ERR_CODE = null
WHERE SHIPMENT_NBR = 'NAC000941449';
COMMIT;

SELECT ERR_CODE,PO_NBR,SHIPPED_QTY,RECEIVED_QTY, dtl.* FROM WMS_RCV_ASN_DTL dtl 
WHERE HDR_GROUP_NBR = 36238;

SELECT RCV_DATE,ERROR_CODE,RCV_DOC_NUMBER,rcd.* from sdircdrej rcd WHERE RCV_DOC_NUMBER = 'NAC000941449';
SELECT RCV_DATE,ERROR_CODE,RCV_DOC_NUMBER,rcd.* from sdircdrej rcd WHERE PMG_PO_NUMBER = 120787;
SELECT RCV_DATE,ERROR_CODE,RCV_DOC_NUMBER,rcd.* from sdircdrej rcd ORDER BY rcd.RCV_DATE DESC;

SELECT * FROM sqlerree where procedure_name = 'IMP_RCV_OC' ORDER BY ERROR_DATE DESC;

SELECT * FROM B2B_OC_RCV_ENVIO WHERE PMG_PO_NUMBER= 120787;


--ERRORES RECEPCION
--CARTON DUPLICADO O GENERICO (SIN CODIGO)
SELECT  DOWNLOAD_DATE_1,DATE_CREATED,MNFST_NUMBER,ERROR_CODE,TRF_NUMBER,CARTON_NUMBER,PRD_LVL_NUMBER, SDI.* 
FROM epmm.SDITRFDTI SDI
WHERE UPPER(MNFST_NUMBER) like '%NAC%' AND SDI.ERROR_CODE  = 204
ORDER BY session_number DESC;

