-- SEQUENCE
CREATE SEQUENCE EDSR.SEQ_CARPAREPO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- TABLA HISTORICO
CREATE TABLE EDSR.CARPAREPO (
  ID         NUMBER PRIMARY KEY,
  PROCESS_ID VARCHAR2(30) NOT NULL,
  TEMPLATE   VARCHAR2(10) NOT NULL, -- DYNAMIC | MINMAX

  USUARIO    VARCHAR2(20) NOT NULL,
  NOMBRE     VARCHAR2(50) NOT NULL,

  FILENAME   VARCHAR2(255) NOT NULL,
  SIZEBYTES  NUMBER NOT NULL,
  HASHSHA256 VARCHAR2(64) NOT NULL,
  UPLOADEDAT TIMESTAMP WITH TIME ZONE NOT NULL,
  ROWCOUNT   NUMBER NOT NULL,

  STATUS     VARCHAR2(20) NOT NULL, -- RECEIVED | REGISTERED | PROCESSING | FINALIZED | FAILED
  ERROR_MSG  VARCHAR2(1000),
  PROCESS    VARCHAR2(10), -- P1 | P2 ... | PN
  DETAIL_PROCESS   VARCHAR2(4000), -- Mensaje de avance
  PROCESS_START TIMESTAMP,
  PROCESS_END TIMESTAMP,
  TOTAL            NUMBER,
  TOTAL_INSERTADOS NUMBER,
  VALIDATED  NUMBER DEFAULT 0,

  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- Indice para evitar doble carga por hash (idempotencia)
CREATE UNIQUE INDEX EDSR.UK_CARPAREPO_HASH
ON EDSR.CARPAREPO (HASHSHA256, TEMPLATE);

ALTER TABLE EDSR.CARPAREPO ADD (
  VALIDATED  NUMBER DEFAULT 0,
  PROCESS_START TIMESTAMP,
  PROCESS_END TIMESTAMP
);

COMMIT;


/
