SELECT TRIM(V.VENDOR_NUMBER) , V.VENDOR_NAME , OC.* 
FROM EPMM.PMGHDREE OC
	INNER JOIN EPMM.VPCMSTEE v ON V.VPC_TECH_KEY = OC.VPC_TECH_KEY
WHERE OC.PMG_PO_NUMBER IN (165362);
-- 124177 y 123514

--API RESPUESTA
SELECT B2B_DOWNLOAD_DATE,ACK.* FROM edsr.B2BACKEE2 ACK ORDER BY B2B_ID DESC;

-- B2B Logistico
select FEC_PROC_LOG,RCV.* from edsr.B2B_OC_RCV_ENVIO RCV
--UPDATE edsr.B2B_OC_RCV_ENVIO SET FEC_PROC_LOG = null
WHERE pmg_po_number IN (165362) AND impuesto_fin = '0';
COMMIT;

--B2B Financiero
select FEC_PROC_FIN,RCV.* from edsr.B2B_OC_RCV_ENVIO RCV
--UPDATE edsr.B2B_OC_RCV_ENVIO SET FEC_PROC_FIN = null
WHERE pmg_po_number IN (165362) AND impuesto_fin != '0';

COMMIT;

-- CONSULTA OC
SELECT PMG.PRIM_ORG_LVL_number, PMG.PMG_PO_NUMBER,PMG.PMG_STAT_CODE,STS.PMG_STAT_NAME, PMG.VPC_TECH_KEY ProveedorID
,TRIM(VPC.VENDOR_NUMBER) PROVEEDOR,VPC.VENDOR_NAME
, PMG.* 
FROM EPMM.PMGHDREE PMG 
	INNER JOIN EPMM.VPCMSTEE VPC ON VPC.VPC_TECH_KEY = PMG.VPC_TECH_KEY
	LEFT JOIN epmm.pmgstscd STS ON STS.PMG_STAT_CODE = PMG.PMG_STAT_CODE
--UPDATE edsr.B2B_OC_RCV_ENVIO B2B SET B2B.FEC_PROC_FIN = NULL
WHERE PMG.PMG_PO_NUMBER IN (165362);
COMMIT;

SELECT * FROM dba_source 
WHERE UPPER(TEXT) LIKE '%sp_genera_archivo_xml_oc_recep_fin%'
--FETCH FIRST 10 ROWS ONLY
;

--NAC000935688
--EVALUACION DE LA RECEPCIÓN
SELECT * FROM EDSR.PMGSTSCD;
SELECT PMG_PO_NUMBER,oc.PRIM_ORG_LVL_NUMBER,OC.PMG_STAT_CODE ,PMG_CANCEL_DATE,PMG_CNCL_BY_DATE ,DOWNLOAD_DATE, oc.*
FROM pmghdree oc
	INNER JOIN EPMM.PMGSTSCD STS ON = STS.PMG_STAT_CODE = oc.PMG_STAT_CODE
WHERE pmg_po_number IN (164554, 164555, 164557, 165752);

SELECT dtl.pmg_status, dtl.* FROM EDSR.pmgdtlee dtl where PMG_PO_NUMBER in (164030);

/*
 * ERRORES COMUNES EN WMS_MODELO_REQUEST
 * 1. ORA-01013: user requested cancel of current operation => NAC000936554
 * 2. 
 * 3. 
 * 4. 
 * 5. 
 */
SELECT * FROM EDSR.WMS_MODELO_REQUEST WHERE IDENTIFICADOR IN ('NAC000936554');
SELECT * FROM EDSR.WMS_MODELO_REQUEST WHERE MOdelo LIKE '%NAC000936554%'; --222637

SELECT * FROM EDSR.WMS_MODELO_REQUEST
--UPDATE EDSR.WMS_MODELO_REQUEST SET FEC_PROCESO = NULL, FLAG_ERROR = 0, FLAG_PROCESADO= 0
WHERE ID_MODELO = 222637;
COMMIT;

--Validando si algun detalle de OC está cancelado o recibido
 select ocd.pmg_status,d.received_qty,d.hdr_group_nbr
  from wms_rcv_asn_dtl d
 inner join pmgdtlee ocd on to_number(d.po_nbr) = ocd.pmg_po_number
 inner join tpprdmst prd
    on prd.prd_lvl_number = d.item_alternate_code
   and prd.prd_lvl_child = ocd.prd_lvl_child
 where d.hdr_group_nbr = cab.hdr_group_nbr
   and d.received_qty  > 0
   and ocd.pmg_status  in (6, 7);

--CONSULTAR RECEPCION
SELECT HDR.HDR_GROUP_NBR,HDR.CREATE_DATE,HDR.DOWNLOAD_DATE_1,HDR.LOAD_NBR,HDR.ERR_CODE,ERR.ERR_DESC, HDR.*
FROM WMS_RCV_ASN_HDR HDR
    LEFT JOIN EDSR.WMS_ERROR_INT ERR ON HDR.ERR_CODE = ERR.ERR_CODE
--update WMS_RCV_ASN_HDR HDR SET ERR_CODE = null, DOWNLOAD_DATE_1 = null
WHERE SHIPMENT_NBR IN ('NAC000936234');
COMMIT;

SELECT DTL.ERR_CODE,ERR.ERR_DESC,dtl.po_nbr	, DTL.*
FROM WMS_RCV_ASN_DTL DTL
    LEFT JOIN EDSR.WMS_ERROR_INT ERR ON DTL.ERR_CODE = ERR.ERR_CODE
 --update WMS_RCV_ASN_DTL HDR SET ERR_CODE = 0
WHERE HDR_GROUP_NBR IN (31594);
COMMIT;