SELECT * FROM PRD_TE_WEB;
--Se ejecuta en la malla
--/prochp/procesos_hp/ksh/tp_mas_tpprdmst.ksh

SELECT SUBSTR('AFEC_IGV',-2,1) FROM DUAL;

-- Pruebas
SELECT PRD.AFECTO, PRD.* FROM tpprdmst PRD WHERE PRD_LVL_NUMBER IN ('36208','36209');
/*
124786
124787
*/
SELECT
    DECODE(FNU_GET_PRODUCTO_IVA(P_PRD_LVL_CHILD => '124786'), 0, 'T', 'F') AFECTO1,
    DECODE(FNU_GET_PRODUCTO_IVA(P_PRD_LVL_CHILD => '124787'), 0, 'T', 'F') AFECTO2
FROM DUAL;

SELECT PRD.AFECTO, PRD.* FROM tpprdmst PRD WHERE PRD_LVL_NUMBER IN ('36207');
--FUMIGADORA MANUAL SHINE 20l (MT-139)
SELECT PRD.AFECTO, PRD.* FROM tpprdmst PRD WHERE PRD_LVL_NUMBER IN ('36206');
SELECT PRD.* FROM PRDMSTEE PRD WHERE PRD_LVL_NUMBER IN ('36206');
SELECT PRD.* FROM PRDMSTEE PRD WHERE PRD_LVL_NUMBER IN ('36206');

SELECT PRD.AFECTO, PRD.* FROM tpprdmst PRD WHERE PRD.AFECTO = 'T';
SELECT MAX(PRD_LVL_NUMBER) FROM tpprdmst PRD WHERE PRD.AFECTO = 'T';

SELECT * FROM ALL_SOURCE WHERE UPPER(TEXT) LIKE '%AFECTO%';
SELECT * FROM ALL_SOURCE WHERE UPPER(TEXT) LIKE '%AFECTO%' AND OWNER ='EPMM';
SELECT * FROM ALL_SOURCE WHERE UPPER(TEXT) LIKE '%INSERT%PRD_TE_WEB%';
SELECT * FROM ALL_SOURCE WHERE UPPER(TEXT) LIKE '%UPDATE%TPPRDMST%';
SELECT * FROM ALL_SOURCE WHERE UPPER(TEXT) LIKE '%AFECTO%=%';


INSERT INTO SDIPRDMSI;
INSERT INTO SDIPRDATI;
SDIPRDBA(V_BATCH_NUM);