SELECT SYSDATE FROM DUAL; -- 12:32:03 (Hora Lima: 11:19:00) 1 hora y 13 min esta adelantado la hora del servidor PMM
-- MIGRACION QA a PRD
SELECT * FROM PIM_MODELO_TIPO;
SELECT * FROM PIM_ATRIBUTO;
INSERT INTO EDSR.PIM_ATRIBUTO (COD_ATRIBUTO, DES_ATRIBUTO, FLG_UND_MEDIDA, FLG_ID_VAL, FLG_CAMPO_ADD, ATR_TYP_TECH_KEY, ATR_HDR_TECH_KEY, NOMBRE_ATRIB_PIM) VALUES ('LongTail', 'Long Tail', '0', 'LV', '0', 21, 159, null);

-- Tabla SDIVPCCSI: Registra muchos atributos logisticos
SELECT  * FROM EDSR.SDIVPCCSI;
SELECT PRD_LVL_CHILD FROM PRDMSTEE WHERE PRD_LVL_NUMBER = '30799';
SELECT * FROM PRDMSTEE WHERE PRD_LVL_NUMBER = '30799';
SELECT * FROM TPPRDMST WHERE PRD_LVL_NUMBER = '30799';
SELECT * FROM PRDPDMEE WHERE PRD_LVL_CHILD IN (119685);
--Inventario
SELECT * FROM INVBALEE WHERE PRD_LVL_CHILD IN (119685);
-- Maestro de Precios
SELECT * FROM PRCMSTEE WHERE PRD_LVL_CHILD IN (119685); -- 11.300
-- Precio Actual
SELECT * FROM CHLPRCE2 WHERE PRD_LVL_CHILD IN (119685); -- 11.300
SELECT  BATCH_NUM,TECH_KEY,PRD_LVL_NUMBER,TRAN_TYPE,VENDOR_NUMBER,CASE_PACK_ID,inv_uom,VPC_CST_START,VPC_CST_END,CASE_PACK_DESC,EACHES_PER_INNER,VPC_PRD_COST,vpc_primary_flag,vpc_buy_multiple,VPC_CASE_QTY_UOM,VPC_CASE_QTY,VPC_CASE_GROSS_WGT,VPC_CASE_WGT,VPC_CASE_WIDTH,VPC_CASE_LEN,VPC_CASE_HEIGHT,VPC_CASE_CUBE,SLL_UNITS_PER_INNER,ASSOCIATED_PRD_UPC,VPC_CASE_WGT_UOM,VPC_CASE_DIM_UOM,CASE_CUBE_UOM,VPC_CASE_STD_PACK,NUMBER_OF_INNERS
FROM EDSR.SDIVPCCSI
WHERE PRD_LVL_NUMBER = '30798';

---------------------------------------------------------------------------
INSERT INTO SDIVPCCSI(
        BATCH_NUM,
        TECH_KEY,
        PRD_LVL_NUMBER,
        TRAN_TYPE,
        VENDOR_NUMBER,
        CASE_PACK_ID,
        inv_uom,
        VPC_CST_START,
        VPC_CST_END,
        CASE_PACK_DESC,
        EACHES_PER_INNER,
        VPC_PRD_COST,
        vpc_primary_flag,
        vpc_buy_multiple,
        VPC_CASE_QTY_UOM,
        VPC_CASE_QTY,
        VPC_CASE_GROSS_WGT,
        VPC_CASE_WGT,
        VPC_CASE_WIDTH,
        VPC_CASE_LEN,
        VPC_CASE_HEIGHT,
        VPC_CASE_CUBE,
        SLL_UNITS_PER_INNER,
        ASSOCIATED_PRD_UPC,
        VPC_CASE_WGT_UOM,
        VPC_CASE_DIM_UOM,
        CASE_CUBE_UOM,
        VPC_CASE_STD_PACK,
        NUMBER_OF_INNERS
      )
      VALUES(
        V_BATCH_NUM,
        1,
        V_PRD_LVL_NUMBER,
        'A',
        V_VENDOR_NUMBER,
        V_SKU_PROVEEDOR,
        V_UMI,
        (select t.caldat from caldayee t),
        to_date('31/12/2999', 'dd/mm/yyyy'),
        V_PRD_NAME_FULL,
        1,
        V_COSTO,
        'T',
        DECODE(V_MP_CANT, 0, NULL, V_MP_CANT),
        V_UMI,
        1,
        V_PESO_BRUTO,
        V_PESO_NETO,
        V_UND_LOG_ANCHO,
        V_UND_LOG_LONGITUD,
        V_UND_LOG_ALTO,
        V_UND_LOG_VOLUMEN,
        1,
        NVL(V_EAN, V_COD_BAR_AUX),
        FN_GET_UND_MED_DEF('PESO'),
        V_UND_LOG_UND_MED,
        FN_GET_UND_MED_DEF('VOLUMEN'),
        V_MP_CANT,
        1
      );
---------------------------------------------------------------------------
SELECT  * FROM EDSR.SDIVPCREJ;
SELECT  * FROM EDSR.IFH_PARAMETROS;
SELECT  * FROM EDSR.PIM_PRODUCTO_DATA_PMM;

--DELETE FROM PIM_MODELO; Commit;

SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE FROM PIM_MODELO WHERE ID_TIPO = 1 ORDER BY  FEC_CREACION DESC;
SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE FROM PIM_MODELO WHERE ID_TIPO = 2 ORDER BY  FEC_CREACION DESC;
SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE FROM PIM_MODELO WHERE ID_TIPO = 3 ORDER BY  FEC_CREACION DESC;
SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE FROM PIM_MODELO WHERE ID_TIPO = 4 ORDER BY  FEC_CREACION DESC;
SELECT * FROM PIM_MODELO ORDER BY FEC_CREACION DESC;
SELECT * FROM PIM_MODELO WHERE ID_MODELO = 1198;

SELECT * FROM PIM_PRODUCTO ORDER BY FEC_CREACION DESC;
SELECT * FROM PIM_PRODUCTO WHERE ID_PIM = 'HESA_TEST_110041' ORDER BY FEC_CREACION DESC;
SELECT PRD.* FROM PRDMSTEE PRD WHERE PRD.PRD_NAME_FULL = 'PISO CERAMICO MARMOL DARINKA 60X60 CM 2.58M2';

SELECT * FROM PIM_PRODUCTO_ATRIB;
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD = 813;
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD = 813 and COD_ATRIBUTO = 'CodLinea';
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE COD_ATRIBUTO = 'CodLinea' AND ID_PIM  LIKE 'HESA_TEST_%' ORDER BY ID_PIM DESC;
-- Maestro de Jerarquias
SELECT * FROM PRDCTLEE ORDER BY PRD_LVL_ID;
-- Maestro de Status
SELECT * FROM PRDSTSEE ORDER BY PRD_STATUS;
SELECT * FROM PRDPLVEE ORDER BY PRD_LVL_ID;
SELECT * FROM PRDMSTEE ORDER BY PRD_LVL_NUMBER ASC;

DECLARE
    V_NUMBER NUMBER := '10' ;
BEGIN
    IF V_NUMBER > 5 THEN
        RAISE_APPLICATION_ERROR(-20001,'El numero es mayor que 5');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('CODIGO: ' || SQLCODE); -- 20001
        DBMS_OUTPUT.PUT_LINE('ERROR BLOQUE EXCEPTION:' || SQLERRM); -- El numero es mayor que 5
END;

/*
0   Variacion
1   Producto/Estilo
2   Linea
3   Departamento
4   Area
5   Division
*/


SELECT SUBSTR('L0869-Limpiadores De Baños, Cocinas Y Especializados',1,5 ) FROM DUAL;
-- FUNCTION FVC_ATRIBUTO_VALOR
SELECT EDSR.PKG_PIM_INTEGRACION.FVC_ATRIBUTO_VALOR(813, 'CodLinea') FROM DUAL;
SELECT substr(EDSR.PKG_PIM_INTEGRACION.FVC_ATRIBUTO_VALOR(813, 'CodLinea'),1,5) FROM DUAL;
SELECT DECODE(FLG_ID_VAL, 'TL', VALOR, NVL(ID,VALOR))
FROM PIM_PRODUCTO_ATRIB
WHERE ID_PIM_PROD    = 813
      AND COD_ATRIBUTO   = 'CodLinea';

SELECT * FROM PIM_PRODUCTO_ATRIB
--UPDATE PIM_PRODUCTO_ATRIB SET VALOR = 'SFB40GYA'
WHERE ID_PIM_PROD = 784 AND COD_ATRIBUTO = 'SkuProveedor';

SELECT * FROM PRDUPCEE WHERE PRD_UPC = '978020137962';

SELECT DECODE(FLG_ID_VAL, 'TL', VALOR, NVL(ID,VALOR))
      FROM PIM_PRODUCTO_ATRIB
      WHERE ID_PIM_PROD    = 776
        AND COD_ATRIBUTO   = 'EAN';

--SELECT * FROM PIM_PRODUCTO_DATA_PMM;
--SELECT * FROM PIM_MODELO_REQUEST WHERE ID_MODELO = 91;
--SELECT * FROM PIM_MODELO_REQUEST ORDER BY FEC_REG DESC;
--SELECT * FROM PIM_MODIFICACIONES_PMM;

-- Productos PMM
SELECT DISTINCT PRD.COD_MARCA, PRD.DES_MARCA --, PRD.COD_AREA , PRD.*
FROM EDSR.TPPRDMST PRD
ORDER BY PRD.COD_MARCA;

--- *************************************************
-- VALIDACION DE CREACION DE PRODUCTO LONG_TAIL
--- *************************************************

SELECT * FROM EDSR.PRDMSTEE WHERE PRD_LVL_NUMBER IN ('36133');
-- Luego de crear, hay un trigger que llena aqui, esperar unos segundos
select prd.atr_long_tail, prd.* FROM TPPRDMST prd WHERE PRD_LVL_NUMBER IN ('36133');
select e.PRD_LVL_CHILD, e.prd_status, des.PRD_STATUS_DESC, e.*
     -- , row_number() over(partition by PRD_LVL_CHILD order by EFFECT_DATE desc) rn
from PRDSTEEE e
    INNER JOIN EDSR.PRDSTSEE des on des.PRD_STATUS = e.PRD_STATUS
WHERE PRD_LVL_CHILD IN ('124760');

SELECT vpc_prd_tech_key FROM EDSR.VPCPRDEE WHERE PRD_LVL_CHILD IN ('124760');
SELECT vpc_prd_status FROM edsr.vpcsteee WHERE vpc_prd_tech_key=134499; -- SET =6
SELECT VPC_PRD_STATUS FROM edsr.VPCPRDEE WHERE vpc_prd_tech_key=134499;  -- SET =6

--- *********************************
-- PKG_PIM_INTEGRACION: CREAR PRODUCTO => Debugear CREACION PRODUCTOS
--- *********************************
SELECT * FROM edsr.PIM_MODELO WHERE ID_TIPO = 2 ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.PIM_MODELO WHERE ID_MODELO =2801;
SELECT * FROM EDSR.PIM_PRODUCTO WHERE ID_MODELO =2801;
SELECT * FROM edsr.Pim_Producto ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.Pim_Producto WHERE ID_PIM_PROD = 1000;
SELECT * FROM edsr.PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD = 1000;


DECLARE
    V_ID_PIM_PROD INTEGER := 1000;
    V_RESULT INTEGER;
BEGIN
    PKG_PIM_INTEGRACION.SP_CREAR_PRODUCTO(V_ID_PIM_PROD,V_RESULT);
    DBMS_OUTPUT.PUT_LINE('ID_PIM_PROD: ' || V_ID_PIM_PROD);
    DBMS_OUTPUT.PUT_LINE('RESULT: ' || V_RESULT);
END;

--PROVEEDOR
SELECT COUNT(*) FROM VPCMSTEE V WHERE TRIM(V.VENDOR_NUMBER) = trim('1791743148001');

--EAN
/*
 PRD_UPC
2500000100284
7450119365966
12500000100281
2500000100291
7450119365980
12500000100298
2500000100307
7450119365997
12500000100304
2500000100314
7450119629815
12500000100311
2500000100321
7450119629877
12500000100328
2500000100338
7450119629945
12500000100335
2500000100345
7450119348013
12500000100342
2500000100352
7450008887548
12500000100359
2500000100369
7450112849463

2500000100376
7450119702945


 */
SELECT PRD.PRD_LVL_NUMBER, EAN.* FROM PRDUPCEE EAN INNER JOIN PRDMSTEE PRD ON PRD.PRD_LVL_CHILD = EAN.PRD_LVL_CHILD
WHERE PRD_UPC IN ('7861123201285');

 SELECT ID_PIM FROM pim_producto WHERE id_pim_prod = 'P_ID_PIM_PROD';

-- EN EL EDSR.PKG_PIM_INTEGRACION VERIFICAR: V_COD_ERR
--- *********************************
-- /Debugear CREACION PRODUCTOS
--- *********************************

--- *********************************
-- Debugear FVC_ATRIBUTO_VALOR
--- *********************************
    /*
 C_ATR_CODLINEA          CONSTANT VARCHAR2(50) := 'CodLinea';
  C_ATR_PROVEEDOR         CONSTANT VARCHAR2(50) := 'Proveedor';
  C_ATR_UMV               CONSTANT VARCHAR2(50) := 'UMV';
  C_ATR_PROCEDENCIA       CONSTANT VARCHAR2(50) := 'Procedencia';
  C_ATR_MP_CANT           CONSTANT VARCHAR2(50) := 'MasterPackCantidad';
  C_ATR_EAN               CONSTANT VARCHAR2(50) := 'EAN';
  C_ATR_EAN_TIPO          CONSTANT VARCHAR2(50) := 'TipoEan';
  C_ATR_PRECIO_UNIT       CONSTANT VARCHAR2(50) := 'PrecioUnitario';
  C_ATR_SKU_PROVEEDOR     CONSTANT VARCHAR2(50) := 'SkuProveedor';
  C_ATR_UMI               CONSTANT VARCHAR2(50) := 'UMI';
  C_ATR_COSTO             CONSTANT VARCHAR2(50) := 'Costo';
  C_ATR_PESO_BRUTO        CONSTANT VARCHAR2(50) := 'PesoUnidadLogistica';
  C_ATR_PESO_NETO         CONSTANT VARCHAR2(50) := 'PesoProducto';
  C_ATR_UND_LOG_ALTO      CONSTANT VARCHAR2(50) := 'AlturaUnidadLogistica';
  C_ATR_UND_LOG_ANCHO     CONSTANT VARCHAR2(50) := 'AnchoUnidadLogistica';

  C_ATR_UND_LOG_LONGITUD  CONSTANT VARCHAR2(50) := 'ProfundidadUnidadLogistica';
  C_ATR_UND_LOG_VOLUMEN   CONSTANT VARCHAR2(50) := 'VolumendelaUnidadLogistica';
  C_ATR_DUN14             CONSTANT VARCHAR2(50) := 'DUN14';
  C_ATR_TIPO_SURTIDO      CONSTANT VARCHAR2(50) := 'TipoSurtido';
  C_ATR_CLUSTER_SURTIDO   CONSTANT VARCHAR2(50) := 'ClusterSurtido';
  C_ATR_MARCA             CONSTANT VARCHAR2(50) := 'Marca';
  C_ATR_MP_TIPO           CONSTANT VARCHAR2(50) := 'MasterPackTipo';
  C_ATR_PERECIBLE         CONSTANT VARCHAR2(50) := 'Perecible';
  C_ATR_PUNTO_PRECIO      CONSTANT VARCHAR2(50) := 'PuntoPrecio';
  C_ATR_TIPO_MARCA        CONSTANT VARCHAR2(50) := 'TipoMarca';
  C_ATR_TIPO_NEG          CONSTANT VARCHAR2(50) := 'TipoNegociacion';
 */
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD = 813;
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE COD_ATRIBUTO = 'CodLinea' AND ID_PIM  LIKE 'HESA_TEST_%' ORDER BY ID_PIM DESC;
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD = 813 and COD_ATRIBUTO = 'CodLinea';

DECLARE
    V_ID_PIM_PROD NUMBER := 813;
    V_COD_ATRIBUTO VARCHAR2(50):= 'CodLinea' ;
    V_RESULT VARCHAR2(120) := '' ;
BEGIN
    SELECT EDSR.PKG_PIM_INTEGRACION.FVC_ATRIBUTO_VALOR(V_ID_PIM_PROD, V_COD_ATRIBUTO) INTO V_RESULT FROM DUAL;
    SP_GEN_LOG('V_ID_PIM_PROD: ' || V_ID_PIM_PROD);
    SP_GEN_LOG('V_COD_ATRIBUTO: ' || V_COD_ATRIBUTO);
    SP_GEN_LOG('V_RESULT: ' || V_RESULT);
END;

-- FUNCTION FVC_ATRIBUTO_VALOR
DECLARE
     V_RESULT VARCHAR2(250) := '' ;
BEGIN
      SELECT DECODE(FLG_ID_VAL, 'TL', VALOR, NVL(ID,VALOR))
        INTO V_RESULT
      FROM PIM_PRODUCTO_ATRIB
      WHERE ID_PIM_PROD    = 813
        AND COD_ATRIBUTO   = 'CodLinea';

      SP_GEN_LOG('V_RESULT: ' || V_RESULT);
      SP_GEN_LOG('SUBSTR: ' || SUBSTR(V_RESULT,1,5 ));
    EXCEPTION
      WHEN OTHERS THEN
          SP_GEN_LOG('ERROR: ' || SQLERRM);
END;
--- *********************************
-- /Debugear FVC_ATRIBUTO_VALOR
--- *********************************

-- 1) Lista de Tramas para procesarlo en PIM_PRODUCTO y PIM_PRODUCTO_ATRIB
SELECT * FROM PIM_MODELO WHERE ID_TIPO = 1 ORDER BY  FEC_CREACION DESC;
SELECT MAX (ID_MODELO) FROM PIM_MODELO;
SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID FROM PIM_MODELO WHERE ID_TIPO = 1 ORDER BY  FEC_CREACION DESC;
SELECT * FROM PIM_MODELO WHERE ID_MODELO IN (2801,2800,2640,2627,2626);
SELECT * FROM PIM_MODELO
--UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '0', FEC_PROCESO = null
WHERE ID_MODELO IN (2801) AND ID_TIPO = 1;

INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (2801, 1, '{"productos":[{"IdPim":"HESA_43107","NombreProducto":"DETERGENTE DE ROPA PARA BEBÉ SELLO AZUL 1.4L","CodigoLineaPromart":"L0051-Detergentes, Jabones Y Suavizantes De Ropa","CodigoProveedor":"1709298622001","Marca":"SELLO AZUL","TipoMarca":"Proveedor","TipoNegociacion":"Propia","ClusterSurtido":"Sin Cluster","TipoSurtido":"L","UnidadMedidadInventarioUMI":"UN","UnidadMedidaVenta":"UN","PuntoPrecio":"Best","PrecioUnitario":"5.58","Costo":"2.88","CantidadMasterpack":"12","SkuProveedor":"PT-SA-ROPA-UN-0013","EAN":"7861123201285","TipoCodigoEAN":"Ean/Upc 13","DUN14":"","NumeroPiezas":"70","TipoMasterpack":"Caja","Perecible":"No","AlturaUnidadLogistica":"28","AnchoUnidadLogistica":"14","ProfundidadUnidadLogistica":"7","VolumenUnidadLogistica":"2.744","PesoUnidadLogistica":"1.58","PesoProducto":"1.58","LongTail":"X","Rendimiento":"","AfectaIGV":"Si"}]}', SYSDATE, '0', '', '0', '', '');
COMMIT;
DELETE FROM PIM_MODELO WHERE ID_MODELO = 4423; COMMIT;

DECLARE
    V_NUMBER NUMBER := '10' ;
BEGIN
    IF V_NUMBER > 5 THEN
        RAISE_APPLICATION_ERROR(-20001,'El numero es mayor que 5');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('CODIGO: ' || SQLCODE);
        DBMS_OUTPUT.PUT_LINE('ERROR BLOQUE EXCEPTION:' || SQLERRM);
END;

    --Listar
    SELECT ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO
    FROM EDSR.PIM_MODELO
    WHERE ID_TIPO = 1 and FLG_PROCESADO = '0' and FLG_ERROR = '0'
    ORDER BY FEC_CREACION;

-- 2) Lista de Productos para Crear en PMM
SELECT * FROM edsr.Pim_Producto ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.Pim_Producto WHERE ID_MODELO = 2602;
SELECT * FROM edsr.Pim_Producto
--UPDATE edsr.Pim_Producto SET  FLG_PROCESADO = '1' --,  FEC_PROCESO = NULL
WHERE ID_PIM_PROD IN (886);
--ATRIBUTOS
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD IN (887);

    --Listar
    SELECT pp.ID_PIM_PROD, pp.DESCRIPCION
    FROM edsr.Pim_Producto pp
        inner join edsr.pim_modelo pm on pm.id_modelo = pp.id_modelo
    WHERE pp.FEC_PROCESO IS NULL and pp.FLG_PROCESADO = '0'
        and pm.id_tipo = 1
    ORDER BY pp.ID_PIM_PROD;

-- 3) Lista de tramas para enviar el SKU hacia PIM
SELECT ID_MODELO,ID_TIPO,FEC_CREACION, FLG_PROCESADO, FEC_PROCESO FROM edsr.pim_modelo WHERE ID_TIPO = 2 ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.pim_modelo
--UPDATE edsr.pim_modelo SET  FLG_PROCESADO = '1'
WHERE ID_MODELO IN (2641) AND ID_TIPO = 2 ; COMMIT;

    --Listar
    SELECT
     FEC_CREACION,Id_Modelo, Id_Tipo, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO
    FROM edsr.pim_modelo
    WHERE id_tipo = 2 and FLG_PROCESADO = '0'
    ORDER BY FEC_CREACION DESC;



/*****************************************************************************/
-- ERRORES MAPEADOS DEL PKG_PIM_INTEGRACION
/*****************************************************************************/

-- V_COD_ERR := 5
SELECT SUBSTR(SDI.ERROR_CODE || ' - ' || ERR.REJ_DESC, 0, 4000)
INTO V_MSG_ERROR
FROM SDIPRDMSI SDI
    INNER JOIN SDIREJCD ERR ON SDI.ERROR_CODE = ERR.REJ_CODE
WHERE SDI.BATCH_NUM = V_BATCH_NUM
  AND ROWNUM = 1
  AND SDI.ERROR_CODE IS NOT NULL
  AND SDI.ERROR_CODE > 0;
/*
V_BATCH_NUM: 1153
V_PRD_LVL_NUMBER: 32635
V_PRD_LVL_ID: 1
V_COD_LINEA: L0730
V_PRD_NAME_FULL: PISO CERAMICO MARMOL LUMIERE BEIGE 60X60 CM 2.58M2
V_VENDOR_NUMBER: 1115
V_PRD_SLL_UOM: UN
 */
SELECT PRD.PRD_LVL_NUMBER, PRD.* FROM PRDMSTEE PRD WHERE PRD_LVL_NUMBER IN ('36001');
-- SKU MAXIMO: 36000 (2024/07/09 12:41pm)
SELECT PRD.PRD_LVL_NUMBER FROM PRDMSTEE PRD ORDER BY PRD.PRD_LVL_NUMBER DESC; --36000
SELECT * FROM bascntee;
/***************************************** sequencial SKU *******************************************/
SELECT EPMM.PRD_LVL_NUMBER.NEXTVAL FROM DUAL;
-- Solo si has llamado una vez al NEXTVAL en la sesion actual
SELECT EPMM.PRD_LVL_NUMBER.CURRVAL FROM DUAL;

SELECT (SEQ.LAST_NUMBER - 1) AS SEQUENCE_NOW, SEQ.LAST_NUMBER  , SEQ.* FROM ALL_SEQUENCES SEQ
--UPDATE ALL_SEQUENCES SET LAST_NUMBER = 36001
WHERE SEQUENCE_NAME = 'PRD_LVL_NUMBER' AND SEQUENCE_OWNER = 'EPMM';

-- AL NO HABER PRIVILEGIOS, SE VA A EJECUTAR UN BUCLE
DECLARE
    V_SEQUENCE_VALUE NUMBER := 0;
BEGIN
    FOR I IN 1..3333 LOOP
        SELECT EPMM.PRD_LVL_NUMBER.NEXTVAL INTO V_SEQUENCE_VALUE FROM DUAL;
        DBMS_OUTPUT.PUT_LINE('CURRENT SEQUENCE: ' || V_SEQUENCE_VALUE);
    END LOOP;
END;

/******************************* /sequencial SKU *******************************************/

SELECT SDI.DOWNLOAD_DATE_1,SDI.DOWNLOAD_DATE_2 , SDI.ERROR_CODE,SDI.* FROM SDIPRDMSI SDI WHERE BATCH_NUM IN (1153);
SELECT SDI.DOWNLOAD_DATE_1,SDI.DOWNLOAD_DATE_2 , SDI.ERROR_CODE,SDI.* FROM SDIPRDMSI SDI WHERE SDI.ERROR_CODE = 5 ORDER BY SDI.DOWNLOAD_DATE_1  DESC;
SELECT * FROM SDIREJCD WHERE REJ_TECH_KEY = 5; -- 999 ERRORES MAPEADOS



--UPDATE SDIPRDMSI SET DOWNLOAD_DATE_1 = NULL WHERE BATCH_NUM = 1153;

DECLARE
    V_BATCH INTEGER := 1153;
BEGIN
    EPMM.SDIPRDBA(V_BATCH);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('CODIGO: ' || SQLCODE);
        DBMS_OUTPUT.PUT_LINE('ERROR BLOQUE EXCEPTION:' || SQLERRM);
END;

/***************************************** Restriccion UNICA EPMM.PRDMSTEEP1: PRD_LVL_CHILD (TABLE: PRDMSTEE)*******************************************/
SELECT COLUMN_NAME FROM ALL_CONS_COLUMNS WHERE CONSTRAINT_NAME = 'PRDMSTEEP1' AND OWNER = 'EPMM'; --PRD_LVL_CHILD
SELECT COLUMN_NAME FROM ALL_CONS_COLUMNS WHERE CONSTRAINT_NAME = 'SDIPRDPCIP1' AND OWNER = 'EPMM'; --BATCH_NUM

-- PRD_LVL_CHILD MAXIMO: 124696 (2024/07/09 13:45pm)
SELECT PRD.PRD_LVL_CHILD FROM PRDMSTEE PRD ORDER BY PRD.PRD_LVL_CHILD DESC; --124696

SELECT (SEQ.LAST_NUMBER - 1) AS SEQUENCE_NOW, SEQ.LAST_NUMBER  , SEQ.* FROM ALL_SEQUENCES SEQ
--UPDATE ALL_SEQUENCES SET LAST_NUMBER = 36001
WHERE SEQUENCE_NAME = 'PRD_LVL_CHILD' AND SEQUENCE_OWNER = 'EPMM';

DECLARE
    V_CHILD_VALUE NUMBER := 0;
BEGIN
    FOR I IN 1..3522 LOOP
        SELECT EPMM.PRD_LVL_CHILD.NEXTVAL INTO V_CHILD_VALUE FROM DUAL;
        DBMS_OUTPUT.PUT_LINE(V_CHILD_VALUE);
    END LOOP;
END;
/***************************************** /Restriccion UNICA EPMM.PRDMSTEEP1 *******************************************/

/***************************************** Restriccion UNICA EPMM.SDIPRDPCIP1: BATCH_NUM (TABLE: SDIPRDPCI)*******************************************/
SELECT SEQ_TE_LOD_ATR.NEXTVAL FROM DUAL;
SELECT SEQ_TE_LOD_ATR.CURRVAL FROM DUAL; -- 1163

-- INTO V_BATCH_NUM


SELECT COLUMN_NAME, C.* FROM ALL_CONS_COLUMNS C WHERE CONSTRAINT_NAME = 'SDIPRDPCIP1' AND OWNER = 'EPMM'; --BATCH_NUM


-- BATCH_NUM MAXIMO: 22924 (2024/07/09 14:07pm)
SELECT SDI.BATCH_NUM FROM SDIPRDPCI SDI ORDER BY SDI.BATCH_NUM DESC; --22924

SELECT (SEQ.LAST_NUMBER - 1) AS SEQUENCE_NOW, SEQ.LAST_NUMBER  , SEQ.* FROM ALL_SEQUENCES SEQ
--UPDATE ALL_SEQUENCES SET LAST_NUMBER = 22925
WHERE SEQUENCE_NAME LIKE '%SEQ_TE_LOD_ATR%' AND SEQUENCE_OWNER = 'EDSR';
--WHERE SEQUENCE_NAME LIKE '%BATCH%NUM%' AND SEQUENCE_OWNER = 'EPMM';

DECLARE
    V_BATCH_VALUE NUMBER := 0;
BEGIN

    FOR I IN 1..21761 LOOP
        SELECT EDSR.SEQ_TE_LOD_ATR.nextval INTO V_BATCH_VALUE FROM DUAL;
        DBMS_OUTPUT.PUT_LINE('BATCH_NUMBER: ' || V_BATCH_VALUE);
    END LOOP;
END;
/***************************************** /Restriccion UNICA EPMM.SDIPRDPCIP1 *******************************************/

    /***************************************** Restriccion UNICA EPMM.SDIPRDPCIP1: BATCH_NUM (TABLE: SDIPRDPCI)*******************************************/
SELECT COLUMN_NAME, C.* FROM ALL_CONS_COLUMNS C WHERE CONSTRAINT_NAME = 'SDIPRDPCIP1' AND OWNER = 'EPMM'; --BATCH_NUM

-- BATCH_NUM MAXIMO: 36000 (2024/07/09 14:07pm)
SELECT SDI.BATCH_NUM FROM SDIPRDPCI SDI ORDER BY SDI.BATCH_NUM DESC; --22924

SELECT (SEQ.LAST_NUMBER - 1) AS SEQUENCE_NOW, SEQ.LAST_NUMBER  , SEQ.* FROM ALL_SEQUENCES SEQ
--UPDATE ALL_SEQUENCES SET LAST_NUMBER = 36001
WHERE SEQUENCE_NAME LIKE '%BATCH%NUM%' AND SEQUENCE_OWNER = 'EPMM';

DECLARE
    V_BATCH_VALUE NUMBER := 0;
BEGIN

    FOR I IN 1..5118 LOOP
        SELECT EPMM.BATCH_NUMBER.nextval INTO V_BATCH_VALUE FROM DUAL;
        DBMS_OUTPUT.PUT_LINE('BATCH_NUMBER: ' || V_BATCH_VALUE);
    END LOOP;
END;
/***************************************** /Restriccion UNICA EPMM.SDIPRDPCIP1 *******************************************/

/***************************************** 9 - Case Pack Ya Existe Para El Proveedor *******************************************/
SELECT * FROM PIM_PRODUCTO_ATRIB
--UPDATE PIM_PRODUCTO_ATRIB SET VALOR = '7380902923007'
WHERE ID_PIM_PROD = 782 AND COD_ATRIBUTO = 'Proveedor'; --1089

SELECT  RPAD(1089, 15, ' ') FROM DUAL; -- '1089           '


SELECT V.VPC_TECH_KEY
  INTO V_VPC_TECH_KEY
FROM VPCMSTEE V
WHERE V.VENDOR_NUMBER = RPAD(V_VENDOR_NUMBER, 15, ' ');

SELECT V.VPC_TECH_KEY, V.*
-- INTO V_VPC_TECH_KEY
FROM VPCMSTEE V
WHERE V.VENDOR_NUMBER = RPAD(1089, 15, ' ');

SELECT * FROM VPCPRDEE CP
WHERE CP.VPC_TECH_KEY = 14241
    AND CP.VPC_CASE_PACK_ID = RPAD('P1024G', 25, ' ');

/*
SELECT COUNT(1)
INTO V_COUNT
FROM VPCPRDEE CP
WHERE CP.VPC_TECH_KEY = V_VPC_TECH_KEY
AND CP.VPC_CASE_PACK_ID = RPAD(V_SKU_PROVEEDOR, 25, ' ');
 */
/***************************************** /9 - Case Pack Ya Existe Para El Proveedor *******************************************/

/*****************************************************************************/
-- /ERRORES MAPEADOS DEL PKG_PIM_INTEGRACION
/*****************************************************************************/

-- SP_GET_TRAMAS_PENDIENTES
SELECT ID_MODELO, PIM.FEC_CREACION, PIM.FLG_PROCESADO, PIM.FLG_ERROR,PIM.FEC_PROCESO --, PIM.*
    --PIM.ID_MODELO, TO_CLOB(TO_NCLOB(PIM.CONTENIDO)) CONTENIDO,
FROM edsr.pim_modelo PIM
WHERE ID_TIPO = 1
      AND NOT FLG_PROCESADO = '0'
      AND NOT FLG_ERROR = '0'
     -- AND TRUNC(FEC_CREACION) = TRUNC(SYSDATE) - 1
     -- AND FEC_PROCESO IS NULL
ORDER BY FEC_CREACION DESC;

--GET SKU
SELECT
 Id_Modelo, Id_Tipo --,TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO
FROM edsr.pim_modelo
WHERE id_tipo = 2 and FLG_PROCESADO = '0';


SELECT * FROM EDSR.PIM_MODELO
--UPDATE edsr.pim_modelo SET FLG_PROCESADO = '0', FLG_ERROR = '0'
WHERE ID_MODELO >= 1011;

-- SP_GET_TRAMAS_PENDIENTES: Tramas a Procesar desde INICIO, esto indica que obtendra una lista para crear productos y sus atributos correspondientes.
SELECT ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO  FROM EDSR.PIM_MODELO
-- UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '1'
WHERE ID_TIPO = 1 and FLG_PROCESADO = '0' and FLG_ERROR = '0'
ORDER BY FEC_CREACION;

SELECT ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO  FROM EDSR.PIM_MODELO
-- UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '0'
WHERE ID_TIPO = 2 and FLG_PROCESADO = '0' and FLG_ERROR = '0'
ORDER BY FEC_CREACION;

-- SP_GET_TRAMAS_PENDIENTES: Tramas a Procesar para ACTUALIZAR, esto indica que obtendra una lista para actualizar productos y sus atributos correspondientes.
SELECT ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO FROM EDSR.PIM_MODELO
-- UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '1'
WHERE ID_TIPO = 3 and FLG_PROCESADO = '0' and FLG_ERROR = '0'
ORDER BY FEC_CREACION;

-- Listar para mandar a OIC
SELECT  Id_Modelo, Id_Tipo, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO,FLG_PROCESADO
FROM edsr.pim_modelo WHERE id_tipo = 2 and FLG_PROCESADO = '0'
ORDER BY FEC_CREACION DESC;

/*
VALIDAR_DATA_PIM (EL PROVEEDOR NO EXISTE)
SP_VALIDAR_NUEVO -> VALIDAR_PROVEEDOR -> (2)

ID_TIPO
1: Crear producto PIM a PMM
2: Actualizar SKU PMM a PIM
3: Actualizar atributos
 */
SELECT * FROM edsr.pim_modelo WHERE ID_MODELO > 847;
SELECT * FROM EDSR.PIM_MODELO WHERE TRUNC(FEC_CREACION) = TRUNC(SYSDATE) ORDER BY FEC_CREACION DESC;
SELECT * FROM EDSR.PIM_MODELO WHERE TRUNC(FEC_CREACION) = TRUNC(TO_DATE('2024-03-22','YYYY-MM-DD')) ORDER BY FEC_CREACION DESC;
SELECT * FROM EDSR.PIM_MODELO WHERE TRUNC(FEC_CREACION) >= TRUNC(SYSDATE) - INTERVAL '5' DAY ORDER BY FEC_CREACION DESC;
SELECT M.ID_MODELO,M.ID_TIPO,M.FLG_PROCESADO,M.FEC_CREACION, TO_CHAR(FEC_CREACION,'YYYYMMDD'),TRUNC(FEC_CREACION),TRUNC(SYSDATE) - INTERVAL '3' DAY FROM EDSR.PIM_MODELO M ORDER BY FEC_CREACION DESC;
SELECT M.ID_MODELO,M.ID_TIPO,M.FLG_PROCESADO,M.FEC_CREACION FROM EDSR.PIM_MODELO M WHERE TO_CHAR(FEC_CREACION,'YYYYMMDD') = '20240322' ORDER BY FEC_CREACION DESC;
SELECT M.ID_MODELO,M.ID_TIPO,M.FLG_PROCESADO,M.FEC_CREACION FROM EDSR.PIM_MODELO M WHERE TRUNC(FEC_CREACION) = TRUNC(TO_DATE('2024-03-22','YYYY-MM-DD')) ORDER BY FEC_CREACION DESC;
SELECT M.ID_MODELO,M.ID_TIPO,M.FLG_PROCESADO,M.FEC_CREACION FROM EDSR.PIM_MODELO M WHERE TRUNC(FEC_CREACION) >= TRUNC(SYSDATE) - INTERVAL '5' DAY ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.pim_modelo WHERE FLG_PROCESADO = '0' ORDER BY ID_MODELO DESC;
SELECT * FROM edsr.pim_modelo WHERE ID_TIPO = 1 ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.pim_modelo WHERE ID_TIPO = 2 ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.pim_modelo WHERE ID_TIPO = 3 ORDER BY FEC_CREACION DESC;
SELECT FLG_PROCESADO,FLG_ERROR, ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO FROM edsr.pim_modelo
-- UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '1'
WHERE ID_MODELO IN (646);

SELECT * FROM edsr.PIM_PRODUCTO ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.PIM_PRODUCTO WHERE ID_PIM_PROD = 704;
SELECT * FROM edsr.PIM_PRODUCTO WHERE ID_PIM = 'HESA_TEST_100118';
SELECT * FROM edsr.PIM_PRODUCTO_ATRIB WHERE ID_PIM = 'HESA_PRUEBA_100050';
-- LV: Lista de Valores
-- TL: Texto Libre
SELECT COD_ATRIBUTO,DECODE(FLG_ID_VAL, 'TL', VALOR, NVL(ID,VALOR)) FROM PIM_PRODUCTO_ATRIB
WHERE ID_PIM_PROD = 606 AND COD_ATRIBUTO   = 'PesoUnidadLogistica';




SELECT * FROM edsr.pim_modelo ORDER BY FEC_CREACION DESC;

SELECT * FROM EDSR.PIM_MODELO
--UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '0'
WHERE ID_TIPO = 2 AND ID_MODELO >= 843;

SELECT FLG_PROCESADO,FLG_ERROR, ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO FROM edsr.pim_modelo
--UPDATE edsr.pim_modelo SET FLG_PROCESADO = '1', FLG_ERROR = '0'
WHERE ID_MODELO = 710 and FLG_PROCESADO = '0' and FLG_ERROR = '0';

SELECT FLG_PROCESADO,FLG_ERROR, ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO FROM edsr.pim_modelo
--UPDATE edsr.pim_modelo SET FLG_PROCESADO = '1', FLG_ERROR = '0'
WHERE ID_MODELO IN (
870,
871,
866,
869,
868,
867) and FLG_PROCESADO = '0' and FLG_ERROR = '0';

DECLARE
    in_ID_PIM_PROD     PIM_PRODUCTO.ID_PIM_PROD%type;
    in_ID_PIM          PIM_PRODUCTO.ID_PIM%type := 'HESA_PRUEBA_100050';
    in_ID_MODELO       PIM_PRODUCTO.ID_MODELO%type := 710;
    in_DESCRIPCION     PIM_PRODUCTO.DESCRIPCION%type := 'Lapiz Plumon Ceramica Retiro 59x2';
    in_prd_lvl_number  PIM_PRODUCTO.prd_lvl_number%type default '';
BEGIN

    BEGIN
        --PKG_PIM_INTEGRACION.SP_INS_PIM_PRODUCTO(in_ID_PIM,in_ID_MODELO,in_DESCRIPCION,in_ID_PIM_PROD,in_prd_lvl_number);
        PKG_PIM_INTEGRACION.SP_INS_PIM_PRODUCTO(in_ID_PIM,in_ID_PIM_PROD);
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('EXCEPTION: ' || SQLERRM) ;
    END;
END;

-- DEBUG
DECLARE
    V_RETORNO    VARCHAR2(50);
    V_PESO_BRUTO  NUMBER(15,4);
BEGIN
  SELECT DECODE(FLG_ID_VAL, 'TL', VALOR, NVL(ID,VALOR))
    INTO V_RETORNO
  FROM PIM_PRODUCTO_ATRIB
  WHERE ID_PIM_PROD    = 646
    AND COD_ATRIBUTO   = 'PesoUnidadLogistica';

  DBMS_OUTPUT.PUT_LINE('V_RETORNO: ' || V_RETORNO) ;
  V_PESO_BRUTO := TO_VARCHAR(V_RETORNO,'9999999999.99999');

  DBMS_OUTPUT.PUT_LINE('V_PESO_BRUTO: ' || V_PESO_BRUTO) ;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('EXCEPTION: ' || SQLERRM) ;
END;


SELECT VPC_CASE_GROSS_WGT FROM SDIVPCCSI;
SELECT * FROM PRDMSTEE WHERE PRD_NAME_FULL LIKE '%MESA%MINI%BLANC%52X37CM%ORANGE%';
SELECT ID_PIM,COD_ATRIBUTO, FLG_ID_VAL, VALOR, ID FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD    = 606;

SELECT ID_PIM, PRD_LVL_CHILD, PRD_LVL_NUMBER, prd_name_full, estadoProducto, dun14, razon_social, codigo_proveedor
              , umi, ean, umv, sku_proveedor, tipo_surtido
FROM EDSR.PIM_PRODUCTO_DATA_PMM;




-- Procesar para que no se manden a OIC
SELECT * FROM edsr.pim_modelo
--UPDATE PIM_MODELO SET FLG_PROCESADO = '1'
WHERE ID_TIPO = 2 AND FLG_PROCESADO = '0' AND ID_MODELO IN (765,763);--  AND ID_MODELO>=755 AND ID_MODELO <=762 --AND ID_MODELO NOT IN (752,753,754);

--ULTIMO PASO: SP_ACTUALIZA_PIM_MODELO
/*
UPDATE PIM_MODELO
SET flg_procesado = '1',
    Mensaje = 'OK',
    FEC_PROCESO = sysdate
WHERE ID_TIPO = 2 AND ID_MODELO = in_id_Modelo;
 */



create table PIM_PRODUCTO
(
    ID_PIM_PROD    NUMBER(18)           not null constraint PK_PIM_PRODUCTO primary key,
    ID_MODELO      NUMBER(18)           not null,
    ID_PIM         VARCHAR2(18)         not null,
    DESCRIPCION    VARCHAR2(50)         not null,
    FEC_CREACION   DATE default SYSDATE not null,
    FLG_PROCESADO  CHAR default '0'     not null constraint CH_PIM_PRODUCTO_PROCESADO check (flg_procesado IN ('0', '1')),
    FEC_PROCESO    DATE,
    PRD_LVL_CHILD  NUMBER(12),
    FLG_ERROR      CHAR default '0'     not null constraint CH_PIM_PRODUCTO_ERROR check (flg_error IN ('0', '1')),
    MENSAJE        VARCHAR2(4000),
    PRD_LVL_NUMBER VARCHAR2(50)
);

create table PIM_PRODUCTO
(
    ID_PIM_PROD    NUMBER(18)           not null constraint PK_PIM_PRODUCTO primary key,
    ID_MODELO      NUMBER(18)           not null,
    ID_PIM         VARCHAR2(18)         not null,
    DESCRIPCION    VARCHAR2(50)         not null,
    FEC_CREACION   DATE default SYSDATE not null,
    FLG_PROCESADO  CHAR default '0'     not null constraint CH_PIM_PRODUCTO_PROCESADO check (flg_procesado IN ('0', '1')),
    FEC_PROCESO    DATE,
    PRD_LVL_CHILD  NUMBER(12),
    FLG_ERROR      CHAR default '0'     not null constraint CH_PIM_PRODUCTO_ERROR check (flg_error IN ('0', '1')),
    MENSAJE        VARCHAR2(4000),
    PRD_LVL_NUMBER VARCHAR2(50)
);




SELECT p.prd_lvl_child, trim(p.prd_lvl_number) prd_lvl_number, trim(p.prd_name_full) prd_name_full
             --campos nuevos
             , TO_CHAR(est.prd_status) prd_status, to_char(dun.prd_upc) dun14, prov.vendor_name, to_char(prov.vendor_number) vendor_number
             , vpc.INV_UOM UMI, to_char(ean.prd_upc) ean, vpc.VPC_CASE_QTY_UOM, vpc.VPC_CASE_PACK_ID sku_proveedor
             , tipo_surt.ATR_CODE tipo_surtido
 FROM prdmstee p
 INNER JOIN (select e.PRD_LVL_CHILD, e.prd_status,
       row_number() over(partition by PRD_LVL_CHILD order by EFFECT_DATE desc) rn
       from PRDSTEEE e) est
   on est.PRD_LVL_CHILD = p.PRD_LVL_CHILD and est.rn = 1
 LEFT JOIN PRDUPCEE dun on dun.PRD_LVL_CHILD = p.PRD_LVL_CHILD and dun.upc_type = 14 and dun.active_flag ='T'
 LEFT JOIN PRDUPCEE ean on dun.PRD_LVL_CHILD = p.PRD_LVL_CHILD and dun.upc_type = 13 and dun.default_flag ='T'
 LEFT JOIN vpcprdee vpc on dun.vpc_prd_tech_key = vpc.vpc_prd_tech_key
 LEFT JOIN vpcmstee prov on vpc.vpc_tech_key = prov.vpc_tech_key
 LEFT JOIN basatpee des_atr on p.PRD_LVL_CHILD = des_atr.PRD_LVL_CHILD and atr_hdr_tech_key = 141
 LEFT JOIN basacdee tipo_surt on des_atr.ATR_COD_TECH_KEY = tipo_surt.ATR_COD_TECH_KEY;

