SELECT SYSDATE FROM DUAL; -- 12:32:03 (Hora Lima: 11:19:00) 1 hora y 13 min esta adelantado la hora del servidor PMM
-- MIGRACION QA a PRD
SELECT * FROM PIM_MODELO_TIPO;
SELECT * FROM PIM_ATRIBUTO ORDER BY COD_ATRIBUTO;
SELECT COUNT(*) FROM PIM_ATRIBUTO;

INSERT INTO EDSR.PIM_ATRIBUTO (COD_ATRIBUTO, DES_ATRIBUTO, FLG_UND_MEDIDA, FLG_ID_VAL, FLG_CAMPO_ADD, ATR_TYP_TECH_KEY, ATR_HDR_TECH_KEY, NOMBRE_ATRIB_PIM)
values  ('Rendimiento', 'Campo Adicional, LABEL: Cant. M2 x Caja ', '0', 'TL', '0', null, null, null);

--20/10/2024
INSERT INTO EDSR.PIM_ATRIBUTO (COD_ATRIBUTO, DES_ATRIBUTO, FLG_UND_MEDIDA, FLG_ID_VAL, FLG_CAMPO_ADD, ATR_TYP_TECH_KEY, ATR_HDR_TECH_KEY, NOMBRE_ATRIB_PIM)
VALUES ('DescripcionPMM', 'Descripción del Producto', '0', 'TL', '0', null, null,null);

ALTER TABLE EDSR.PIM_PRODUCTO_ATRIB
ADD Observaciones VARCHAR2(1000);

ALTER TABLE EDSR.PIM_PRODUCTO_ATRIB
ADD (
    CONTROL_NUMBER NUMBER NULL,
    BATCH_NUM NUMBER NULL,
    Observaciones VARCHAR2(1000) NULL
);

SELECT COD_ATRIBUTO, NOMBRE_ATRIB_PIM FROM PIM_ATRIBUTO ORDER BY COD_ATRIBUTO ;



SELECT * FROM ALL_SOURCE WHERE UPPER(TEXT) LIKE '%B2B_OC_RCV_ENVIO%';

--DELETE FROM PIM_MODELO; Commit;
-- Lista de Marcas
--
SELECT  * FROM EDSR.TPPRDMST PRD;
-- Maestra códigos de barra
SELECT  * FROM EDSR.PRDUPCEE;
-- Tipos de códigos de barra
SELECT  * FROM EDSR.PRDUCDEE;
-- Maestro de Case Pack
SELECT  * FROM EDSR.VPCPRDEE;

SELECT  * FROM EDSR.ORGMSTEE;

SELECT  * FROM EDSR.PRDPRCREJ;
SELECT  * FROM EDSR.PRDPCDEE;

SELECT  * FROM EDSR.SDIPRDATI;
SELECT  * FROM EDSR.SDIUPIREJ;
-- Tabla de Errores General
SELECT  * FROM EDSR.SDIREJCD;

SELECT  * FROM EDSR.SDIVPCREJ;
SELECT  * FROM EDSR.SDIVPCUPI;
SELECT  * FROM EDSR.SDIPRDPCI;
SELECT  * FROM EDSR.IFH_PARAMETROS;

-- Proveedor
SELECT * FROM VPCMSTEE V WHERE TRIM(V.VENDOR_NUMBER) = trim('0992234814001');


SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, CONTENIDO FROM PIM_MODELO WHERE ID_TIPO = 1 ORDER BY  FEC_CREACION DESC;
SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE FROM PIM_MODELO WHERE ID_TIPO = 1 ORDER BY  FEC_CREACION DESC;

SELECT * FROM PIM_MODELO
--UPDATE PIM_MODELO SET FLG_PROCESADO = '0', FLG_ERROR = '0', FEC_PROCESO = null, CONTENIDO = '{"productos":[{"IdPim":"HESA_41453","NombreProducto":"UNION CANALETA PVC 20X10","CodigoLineaPromart":"L0227-Canaletas","CodigoProveedor":"0993367458001","Marca":"M/B","TipoMarca":"Proveedor","TipoNegociacion":"Propia","ClusterSurtido":"Sin Cluster","TipoSurtido":"H","UnidadMedidadInventarioUMI":"UN","UnidadMedidaVenta":"UN","PuntoPrecio":"Opp","PrecioUnitario":"0.3963","Costo":"0.16","CantidadMasterpack":"100","SkuProveedor":"UNC20X10","EAN":"7862137481342","TipoCodigoEAN":"Ean/Upc 13","DUN14":"17862137481349","NumeroPiezas":"20.7","TipoMasterpack":"Caja","Perecible":"No","AlturaUnidadLogistica":"1.01","AnchoUnidadLogistica":"2.07","ProfundidadUnidadLogistica":"2.07","VolumenUnidadLogistica":"0.00433","PesoUnidadLogistica":"0","PesoProducto":"0","LongTail":"","Rendimiento":""}]}'
WHERE ID_MODELO = 33257;
COMMIT;



SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE FROM PIM_MODELO WHERE ID_TIPO = 2 ORDER BY  FEC_CREACION DESC;
SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE FROM PIM_MODELO WHERE ID_TIPO = 3 ORDER BY  FEC_CREACION DESC;
SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE FROM PIM_MODELO WHERE ID_TIPO = 4 ORDER BY  FEC_CREACION DESC;
SELECT * FROM PIM_MODELO ORDER BY FEC_CREACION DESC;
SELECT * FROM PIM_MODELO WHERE ID_MODELO = 33257;

SELECT * FROM PIM_PRODUCTO ORDER BY FEC_CREACION DESC;
SELECT * FROM PIM_PRODUCTO WHERE ID_PIM = 'HESA_40720' ORDER BY FEC_CREACION DESC;
SELECT PRD.* FROM PRDMSTEE PRD WHERE PRD.PRD_NAME_FULL = 'PISO CERAMICO MARMOL DARINKA 60X60 CM 2.58M2';

SELECT * FROM PIM_PRODUCTO_ATRIB;
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD = 909;
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD = 904;
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD = 813 and COD_ATRIBUTO = 'CodLinea';
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE COD_ATRIBUTO = 'CodLinea' AND ID_PIM  LIKE 'HESA_TEST_%' ORDER BY ID_PIM DESC;

--- *********************************
-- Debugear CREACION PRODUCTOS
--- *********************************
SELECT * FROM edsr.PIM_MODELO ORDER BY FEC_CREACION DESC;
SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE FROM PIM_MODELO WHERE ID_TIPO = 2 ORDER BY  FEC_CREACION DESC;
SELECT * FROM PIM_MODELO WHERE ID_MODELO = 69979 ;

SELECT * FROM edsr.Pim_Producto ORDER BY FEC_CREACION DESC;
SELECT * FROM PIM_MODELO WHERE CONTENIDO like '%HESA_41094%' ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.Pim_Producto WHERE ID_PIM_PROD = 914;
SELECT * FROM edsr.PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD = 914;
SELECT * FROM edsr.PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD = 905; -- Paso validaciones

SELECT * FROM basacdee where ATR_HDR_TECH_KEY = 111 ;

 SELECT *
--INTO v_ATR_CODE
FROM basacdee
WHERE atr_hdr_tech_key = 105
      AND UPPER(TRIM(ATR_CODE)) = UPPER(TRIM('PACIFICO'));

SELECT *
--INTO v_exists_attrib
FROM EPMM.BASATPEE
WHERE PRD_LVL_CHILD='124776'
      AND ATR_TYP_TECH_KEY = 22
      AND ATR_HDR_TECH_KEY = 105;

SELECT * FROM PIM_ATRIBUTO;
SELECT  ID_PIM, COD_ATRIBUTO, ID,
              VALOR, UND_MEDIDA, FLG_UND_MEDIDA,
              FLG_ID_VAL, FLG_CAMPO_ADD, ATR_TYP_TECH_KEY,
              ATR_HDR_TECH_KEY, ID_PIM_PROD
FROM PIM_PRODUCTO_ATRIB
WHERE ID_PIM_PROD = 910;
SELECT * FROM PRDMSTEE WHERE PRD_LVL_NUMBER = '36185';
 SELECT trim(PRD_LVL_NUMBER)
      --INTO V_SKU = 36185
      FROM PIM_PRODUCTO
      WHERE ID_PIM_PROD = 910;

DECLARE
    V_ID_PIM_PROD INTEGER := 999;
    V_RESULT INTEGER;
BEGIN
    PKG_PIM_INTEGRACION.SP_CREAR_PRODUCTO(V_ID_PIM_PROD,V_RESULT);
    DBMS_OUTPUT.PUT_LINE('ID_PIM_PROD: ' || V_ID_PIM_PROD);
    DBMS_OUTPUT.PUT_LINE('RESULT: ' || V_RESULT);
END;

SELECT * FROM prducdee; --upc_type
-- Lista de Errores
SELECT * FROM SDIREJCD;
SELECT * FROM SDIREJCD WHERE REJ_CODE IN (141,132,475);
SELECT * FROM PRDMSTEE WHERE PRD_LVL_NUMBER IN ('36161');
SELECT * FROM VPCMSTEE V WHERE TRIM(V.VENDOR_NUMBER) = trim('0190159663001'); -- ANTES 1097

--- *********************************
-- Debugear ATRIBUTOS
--- *********************************
SELECT * FROM PIM_ATRIBUTO;
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD = 906;
SELECT * FROM PIM_ATRIBUTO WHERE COD_ATRIBUTO = 'TipoEan';


--Validacion de NULL en atributos
SELECT COD_ATRIBUTO FROM EDSR.PIM_PRODUCTO_ATRIB
WHERE
    ID_PIM_PROD = 905
    AND ID IS NULL AND VALOR IS NULL
    AND COD_ATRIBUTO NOT IN ('EAN','DUN14','LongTail', 'Rendimiento')
    AND ROWNUM = 1 ;

--Validacion de TipoEAN
DECLARE
    V_ID_PIM_PROD   NUMBER := 906;
    V_TIPO_EAN      VARCHAR2(50);
    V_EAN           VARCHAR2(50);
    V_COUNT         NUMBER;
BEGIN
    V_TIPO_EAN := PKG_PIM_INTEGRACION.FVC_OBTENER_EAN(V_ID_PIM_PROD, 'TipoEan');
    V_EAN := PKG_PIM_INTEGRACION.FVC_ATRIBUTO_VALOR(V_ID_PIM_PROD, 'EAN');
    DBMS_OUTPUT.PUT_LINE('V_TIPO_EAN => ' || V_TIPO_EAN);
    DBMS_OUTPUT.PUT_LINE('V_EAN => ' || V_EAN);
    DBMS_OUTPUT.PUT_LINE('LENGTH(V_EAN) => ' || LENGTH(V_EAN));

    SELECT COUNT(*)
    INTO V_COUNT
    FROM PRDUCDEE
    WHERE TRIM(UPC_TYPE) = TRIM(V_TIPO_EAN);
    DBMS_OUTPUT.PUT_LINE('V_COUNT => ' || V_COUNT);

    IF V_TIPO_EAN IS NULL OR V_TIPO_EAN = '' THEN
        DBMS_OUTPUT.PUT_LINE('ES NULL EL V_EAN => ' || V_TIPO_EAN);
    END IF;

    IF V_EAN IS NOT NULL THEN
        DBMS_OUTPUT.PUT_LINE('V_EAN DIFERENTE A VACIO => ' || V_EAN);
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('EXCEPTION => ' || SQLERRM);
END;
-- TipoEAN en PMM
SELECT * FROM prducdee
WHERE UPPER(TRIM(UPC_TYPE_DESC)) = UPPER(TRIM('Ean/Upc 13'));

--Existencia de EAN
SELECT prd_upc,
     product_upc,
     prd_lvl_child,
     prd_primary_flag, UPC.*
FROM prdupcee UPC
WHERE prd_upc = '0883049528434' AND product_upc = 'T';--DEF805373

     SELECT *
        FROM PRDUPCEE
        WHERE PRD_UPC = '0883049528434';

-- Maestro de Jerarquias
SELECT * FROM PRDCTLEE ORDER BY PRD_LVL_ID;
-- Maestro de Status
SELECT * FROM PRDSTSEE ORDER BY PRD_STATUS;
SELECT * FROM PRDPLVEE ORDER BY PRD_LVL_ID;
SELECT * FROM PRDMSTEE ORDER BY PRD_LVL_NUMBER ASC;



-- EN EL EDSR.PKG_PIM_INTEGRACION VERIFICAR: V_COD_ERR
--- *********************************
-- /Debugear CREACION PRODUCTOS
--- *********************************
-- 1) Lista de Tramas para procesarlo en PIM_PRODUCTO y PIM_PRODUCTO_ATRIB
SELECT * FROM PIM_MODELO WHERE ID_TIPO = 1 ORDER BY  FEC_CREACION DESC;
SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE FROM PIM_MODELO WHERE ID_TIPO = 1 ORDER BY  FEC_CREACION DESC;
SELECT * FROM PIM_MODELO
--UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '0'
WHERE ID_MODELO IN (1253,1255,1254) AND ID_TIPO = 1 ;

    --Listar
    SELECT ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO
    FROM EDSR.PIM_MODELO
    WHERE ID_TIPO = 1 and FLG_PROCESADO = '0' and FLG_ERROR = '0'
    ORDER BY FEC_CREACION;

-- 2) Lista de Productos para Crear en PMM
SELECT * FROM edsr.Pim_Producto ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.Pim_Producto
--UPDATE edsr.Pim_Producto SET  FLG_PROCESADO = '0',  FEC_PROCESO = NULL
WHERE ID_PIM_PROD IN (813);
--ATRIBUTOS
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD IN (753);

    --Listar
    SELECT pp.ID_PIM_PROD, pp.DESCRIPCION
    FROM edsr.Pim_Producto pp
        inner join edsr.pim_modelo pm on pm.id_modelo = pp.id_modelo
    WHERE pp.FEC_PROCESO IS NULL and pp.FLG_PROCESADO = '0'
        and pm.id_tipo = 1
    ORDER BY pp.ID_PIM_PROD;

-- 3) Lista de tramas para enviar el SKU hacia PIM
SELECT * FROM edsr.pim_modelo ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.pim_modelo
--UPDATE edsr.pim_modelo SET  FLG_PROCESADO = '1'
WHERE ID_TIPO = 2 AND ID_MODELO IN (542,540,541) ;

    --Listar
    SELECT
     FEC_CREACION,Id_Modelo, Id_Tipo, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO
    FROM edsr.pim_modelo
    WHERE id_tipo = 2 and FLG_PROCESADO = '0'
    ORDER BY FEC_CREACION DESC;



/*
0   Variacion
1   Producto/Estilo
2   Linea
3   Departamento
4   Area
5   Division
*/


SELECT SUBSTR('L0869-Limpiadores De Baños, Cocinas Y Especializados',1,5 ) FROM DUAL;
-- FUNCTION FVC_ATRIBUTO_VALOR
SELECT EDSR.PKG_PIM_INTEGRACION.FVC_ATRIBUTO_VALOR(813, 'CodLinea') FROM DUAL;
SELECT substr(EDSR.PKG_PIM_INTEGRACION.FVC_ATRIBUTO_VALOR(813, 'CodLinea'),1,5) FROM DUAL;
SELECT DECODE(FLG_ID_VAL, 'TL', VALOR, NVL(ID,VALOR))
FROM PIM_PRODUCTO_ATRIB
WHERE ID_PIM_PROD    = 813
      AND COD_ATRIBUTO   = 'CodLinea';

SELECT * FROM PIM_PRODUCTO_ATRIB
--UPDATE PIM_PRODUCTO_ATRIB SET VALOR = 'SFB40GYA'
WHERE ID_PIM_PROD = 784 AND COD_ATRIBUTO = 'SkuProveedor';

SELECT * FROM PRDUPCEE WHERE PRD_UPC = '978020137962';

SELECT DECODE(FLG_ID_VAL, 'TL', VALOR, NVL(ID,VALOR))
      FROM PIM_PRODUCTO_ATRIB
      WHERE ID_PIM_PROD    = 776
        AND COD_ATRIBUTO   = 'EAN';

--SELECT * FROM PIM_PRODUCTO_DATA_PMM;
--SELECT * FROM PIM_MODELO_REQUEST WHERE ID_MODELO = 91;
--SELECT * FROM PIM_MODELO_REQUEST ORDER BY FEC_REG DESC;
--SELECT * FROM PIM_MODIFICACIONES_PMM;

-- Productos PMM
SELECT DISTINCT PRD.COD_MARCA, PRD.DES_MARCA --, PRD.COD_AREA , PRD.*
FROM EDSR.TPPRDMST PRD
ORDER BY PRD.COD_MARCA;

-- Long Tail
-- 21 - 159
-- QA: 36117 LongTail (PIM)
 SELECT 'V_BATCH_NUM',ROWNUM,'36117',0,ATR_TYP_TECH_KEY,ATR_HDR_TECH_KEY,ID,'A',1
 FROM PIM_PRODUCTO_ATRIB
 WHERE ID_PIM_PROD = 879
       AND ATR_TYP_TECH_KEY IS NOT NULL;

SELECT PRD.PRD_LVL_NUMBER, PRD.* FROM PIM_PRODUCTO PRD WHERE PRD.PRD_LVL_NUMBER IN ('36117', '36120','36124');
select prd.atr_long_tail, prd.* FROM TPPRDMST prd WHERE PRD_LVL_CHILD IN ('124752','124754');

SELECT prd.prd_status , prd.* FROM PRDMSTEE prd WHERE prd.PRD_LVL_NUMBER IN ('36117', '36120','36124');
SELECT vpc.vpc_prd_status , vpc.* FROM vpcprdee vpc WHERE PRD_LVL_CHILD IN ('124752','124754','124757');

UPDATE TPPRDMST
SET ATR_LONG_TAIL = 'X'
WHERE PRD_LVL_CHILD IN ('124752');
COMMIT;

SELECT BATCH_NUM,CONTROL_NUMBER,PRD_LVL_NUMBER,ORG_LVL_NUMBER,ATR_TYP_TECH_KEY,ATR_HDR_TECH_KEY,ATR_CODE,TRAN_TYPE,PRD_LVL_ID
FROM SDIPRDATI WHERE PRD_LVL_NUMBER IN ('36120');

-- Estado Long Tail
select e.PRD_LVL_CHILD, e.prd_status, des.PRD_STATUS_DESC, e.*
     -- , row_number() over(partition by PRD_LVL_CHILD order by EFFECT_DATE desc) rn
from PRDSTEEE e
    INNER JOIN EDSR.PRDSTSEE des on des.PRD_STATUS = e.PRD_STATUS
WHERE PRD_LVL_CHILD IN ('124754','124757');



--- *********************************
-- Debugear FVC_ATRIBUTO_VALOR
--- *********************************
    /*
 C_ATR_CODLINEA          CONSTANT VARCHAR2(50) := 'CodLinea';
  C_ATR_PROVEEDOR         CONSTANT VARCHAR2(50) := 'Proveedor';
  C_ATR_UMV               CONSTANT VARCHAR2(50) := 'UMV';
  C_ATR_PROCEDENCIA       CONSTANT VARCHAR2(50) := 'Procedencia';
  C_ATR_MP_CANT           CONSTANT VARCHAR2(50) := 'MasterPackCantidad';
  C_ATR_EAN               CONSTANT VARCHAR2(50) := 'EAN';
  C_ATR_EAN_TIPO          CONSTANT VARCHAR2(50) := 'TipoEan';
  C_ATR_PRECIO_UNIT       CONSTANT VARCHAR2(50) := 'PrecioUnitario';
  C_ATR_SKU_PROVEEDOR     CONSTANT VARCHAR2(50) := 'SkuProveedor';
  C_ATR_UMI               CONSTANT VARCHAR2(50) := 'UMI';
  C_ATR_COSTO             CONSTANT VARCHAR2(50) := 'Costo';
  C_ATR_PESO_BRUTO        CONSTANT VARCHAR2(50) := 'PesoUnidadLogistica';
  C_ATR_PESO_NETO         CONSTANT VARCHAR2(50) := 'PesoProducto';
  C_ATR_UND_LOG_ALTO      CONSTANT VARCHAR2(50) := 'AlturaUnidadLogistica';
  C_ATR_UND_LOG_ANCHO     CONSTANT VARCHAR2(50) := 'AnchoUnidadLogistica';

  C_ATR_UND_LOG_LONGITUD  CONSTANT VARCHAR2(50) := 'ProfundidadUnidadLogistica';
  C_ATR_UND_LOG_VOLUMEN   CONSTANT VARCHAR2(50) := 'VolumendelaUnidadLogistica';
  C_ATR_DUN14             CONSTANT VARCHAR2(50) := 'DUN14';
  C_ATR_TIPO_SURTIDO      CONSTANT VARCHAR2(50) := 'TipoSurtido';
  C_ATR_CLUSTER_SURTIDO   CONSTANT VARCHAR2(50) := 'ClusterSurtido';
  C_ATR_MARCA             CONSTANT VARCHAR2(50) := 'Marca';
  C_ATR_MP_TIPO           CONSTANT VARCHAR2(50) := 'MasterPackTipo';
  C_ATR_PERECIBLE         CONSTANT VARCHAR2(50) := 'Perecible';
  C_ATR_PUNTO_PRECIO      CONSTANT VARCHAR2(50) := 'PuntoPrecio';
  C_ATR_TIPO_MARCA        CONSTANT VARCHAR2(50) := 'TipoMarca';
  C_ATR_TIPO_NEG          CONSTANT VARCHAR2(50) := 'TipoNegociacion';
 */
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD = 813;
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE COD_ATRIBUTO = 'CodLinea' AND ID_PIM  LIKE 'HESA_TEST_%' ORDER BY ID_PIM DESC;
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD = 813 and COD_ATRIBUTO = 'CodLinea';

DECLARE
    V_ID_PIM_PROD NUMBER := 813;
    V_COD_ATRIBUTO VARCHAR2(50):= 'CodLinea' ;
    V_RESULT VARCHAR2(120) := '' ;
BEGIN
    SELECT EDSR.PKG_PIM_INTEGRACION.FVC_ATRIBUTO_VALOR(V_ID_PIM_PROD, V_COD_ATRIBUTO) INTO V_RESULT FROM DUAL;
    SP_GEN_LOG('V_ID_PIM_PROD: ' || V_ID_PIM_PROD);
    SP_GEN_LOG('V_COD_ATRIBUTO: ' || V_COD_ATRIBUTO);
    SP_GEN_LOG('V_RESULT: ' || V_RESULT);
END;

-- FUNCTION FVC_ATRIBUTO_VALOR
DECLARE
     V_RESULT VARCHAR2(250) := '' ;
BEGIN
      SELECT DECODE(FLG_ID_VAL, 'TL', VALOR, NVL(ID,VALOR))
        INTO V_RESULT
      FROM PIM_PRODUCTO_ATRIB
      WHERE ID_PIM_PROD    = 813
        AND COD_ATRIBUTO   = 'CodLinea';

      SP_GEN_LOG('V_RESULT: ' || V_RESULT);
      SP_GEN_LOG('SUBSTR: ' || SUBSTR(V_RESULT,1,5 ));
    EXCEPTION
      WHEN OTHERS THEN
          SP_GEN_LOG('ERROR: ' || SQLERRM);
END;
--- *********************************
-- /Debugear FVC_ATRIBUTO_VALOR
--- *********************************



/*****************************************************************************/
-- ERRORES MAPEADOS DEL PKG_PIM_INTEGRACION
/*****************************************************************************/

-- V_COD_ERR := 5
SELECT SUBSTR(SDI.ERROR_CODE || ' - ' || ERR.REJ_DESC, 0, 4000)
INTO V_MSG_ERROR
FROM SDIPRDMSI SDI
    INNER JOIN SDIREJCD ERR ON SDI.ERROR_CODE = ERR.REJ_CODE
WHERE SDI.BATCH_NUM = V_BATCH_NUM
  AND ROWNUM = 1
  AND SDI.ERROR_CODE IS NOT NULL
  AND SDI.ERROR_CODE > 0;
/*
V_BATCH_NUM: 1153
V_PRD_LVL_NUMBER: 32635
V_PRD_LVL_ID: 1
V_COD_LINEA: L0730
V_PRD_NAME_FULL: PISO CERAMICO MARMOL LUMIERE BEIGE 60X60 CM 2.58M2
V_VENDOR_NUMBER: 1115
V_PRD_SLL_UOM: UN
 */
SELECT PRD.PRD_LVL_NUMBER, PRD.* FROM PRDMSTEE PRD WHERE PRD_LVL_NUMBER IN ('36001');
-- SKU MAXIMO: 36000 (2024/07/09 12:41pm)
SELECT PRD.PRD_LVL_NUMBER FROM PRDMSTEE PRD ORDER BY PRD.PRD_LVL_NUMBER DESC; --36000
SELECT * FROM bascntee;
/***************************************** sequencial SKU *******************************************/
SELECT EPMM.PRD_LVL_NUMBER.NEXTVAL FROM DUAL;
-- Solo si has llamado una vez al NEXTVAL en la sesion actual
SELECT EPMM.PRD_LVL_NUMBER.CURRVAL FROM DUAL;

SELECT (SEQ.LAST_NUMBER - 1) AS SEQUENCE_NOW, SEQ.LAST_NUMBER  , SEQ.* FROM ALL_SEQUENCES SEQ
--UPDATE ALL_SEQUENCES SET LAST_NUMBER = 36001
WHERE SEQUENCE_NAME = 'PRD_LVL_NUMBER' AND SEQUENCE_OWNER = 'EPMM';

-- AL NO HABER PRIVILEGIOS, SE VA A EJECUTAR UN BUCLE
DECLARE
    V_SEQUENCE_VALUE NUMBER := 0;
BEGIN
    FOR I IN 1..3333 LOOP
        SELECT EPMM.PRD_LVL_NUMBER.NEXTVAL INTO V_SEQUENCE_VALUE FROM DUAL;
        DBMS_OUTPUT.PUT_LINE('CURRENT SEQUENCE: ' || V_SEQUENCE_VALUE);
    END LOOP;
END;

/******************************* /sequencial SKU *******************************************/

SELECT SDI.DOWNLOAD_DATE_1,SDI.DOWNLOAD_DATE_2 , SDI.ERROR_CODE,SDI.* FROM SDIPRDMSI SDI WHERE BATCH_NUM IN (1153);
SELECT SDI.DOWNLOAD_DATE_1,SDI.DOWNLOAD_DATE_2 , SDI.ERROR_CODE,SDI.* FROM SDIPRDMSI SDI WHERE SDI.ERROR_CODE = 5 ORDER BY SDI.DOWNLOAD_DATE_1  DESC;
SELECT * FROM SDIREJCD WHERE REJ_TECH_KEY = 5; -- 999 ERRORES MAPEADOS



--UPDATE SDIPRDMSI SET DOWNLOAD_DATE_1 = NULL WHERE BATCH_NUM = 1153;

DECLARE
    V_BATCH INTEGER := 1153;
BEGIN
    EPMM.SDIPRDBA(V_BATCH);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('CODIGO: ' || SQLCODE);
        DBMS_OUTPUT.PUT_LINE('ERROR BLOQUE EXCEPTION:' || SQLERRM);
END;

/***************************************** Restriccion UNICA EPMM.PRDMSTEEP1: PRD_LVL_CHILD (TABLE: PRDMSTEE)*******************************************/
SELECT COLUMN_NAME FROM ALL_CONS_COLUMNS WHERE CONSTRAINT_NAME = 'PRDMSTEEP1' AND OWNER = 'EPMM'; --PRD_LVL_CHILD
SELECT COLUMN_NAME FROM ALL_CONS_COLUMNS WHERE CONSTRAINT_NAME = 'SDIPRDPCIP1' AND OWNER = 'EPMM'; --BATCH_NUM

-- PRD_LVL_CHILD MAXIMO: 124696 (2024/07/09 13:45pm)
SELECT PRD.PRD_LVL_CHILD FROM PRDMSTEE PRD ORDER BY PRD.PRD_LVL_CHILD DESC; --124696

SELECT (SEQ.LAST_NUMBER - 1) AS SEQUENCE_NOW, SEQ.LAST_NUMBER  , SEQ.* FROM ALL_SEQUENCES SEQ
--UPDATE ALL_SEQUENCES SET LAST_NUMBER = 36001
WHERE SEQUENCE_NAME = 'PRD_LVL_CHILD' AND SEQUENCE_OWNER = 'EPMM';

DECLARE
    V_CHILD_VALUE NUMBER := 0;
BEGIN
    FOR I IN 1..3522 LOOP
        SELECT EPMM.PRD_LVL_CHILD.NEXTVAL INTO V_CHILD_VALUE FROM DUAL;
        DBMS_OUTPUT.PUT_LINE(V_CHILD_VALUE);
    END LOOP;
END;
/***************************************** /Restriccion UNICA EPMM.PRDMSTEEP1 *******************************************/

/***************************************** Restriccion UNICA EPMM.SDIPRDPCIP1: BATCH_NUM (TABLE: SDIPRDPCI)*******************************************/
SELECT SEQ_TE_LOD_ATR.NEXTVAL FROM DUAL;
SELECT SEQ_TE_LOD_ATR.CURRVAL FROM DUAL; -- 1163

-- INTO V_BATCH_NUM


SELECT COLUMN_NAME, C.* FROM ALL_CONS_COLUMNS C WHERE CONSTRAINT_NAME = 'SDIPRDPCIP1' AND OWNER = 'EPMM'; --BATCH_NUM


-- BATCH_NUM MAXIMO: 22924 (2024/07/09 14:07pm)
SELECT SDI.BATCH_NUM FROM SDIPRDPCI SDI ORDER BY SDI.BATCH_NUM DESC; --22924

SELECT (SEQ.LAST_NUMBER - 1) AS SEQUENCE_NOW, SEQ.LAST_NUMBER  , SEQ.* FROM ALL_SEQUENCES SEQ
--UPDATE ALL_SEQUENCES SET LAST_NUMBER = 22925
WHERE SEQUENCE_NAME LIKE '%SEQ_TE_LOD_ATR%' AND SEQUENCE_OWNER = 'EDSR';
--WHERE SEQUENCE_NAME LIKE '%BATCH%NUM%' AND SEQUENCE_OWNER = 'EPMM';

DECLARE
    V_BATCH_VALUE NUMBER := 0;
BEGIN

    FOR I IN 1..21761 LOOP
        SELECT EDSR.SEQ_TE_LOD_ATR.nextval INTO V_BATCH_VALUE FROM DUAL;
        DBMS_OUTPUT.PUT_LINE('BATCH_NUMBER: ' || V_BATCH_VALUE);
    END LOOP;
END;
/***************************************** /Restriccion UNICA EPMM.SDIPRDPCIP1 *******************************************/

    /***************************************** Restriccion UNICA EPMM.SDIPRDPCIP1: BATCH_NUM (TABLE: SDIPRDPCI)*******************************************/
SELECT COLUMN_NAME, C.* FROM ALL_CONS_COLUMNS C WHERE CONSTRAINT_NAME = 'SDIPRDPCIP1' AND OWNER = 'EPMM'; --BATCH_NUM

-- BATCH_NUM MAXIMO: 36000 (2024/07/09 14:07pm)
SELECT SDI.BATCH_NUM FROM SDIPRDPCI SDI ORDER BY SDI.BATCH_NUM DESC; --22924

SELECT (SEQ.LAST_NUMBER - 1) AS SEQUENCE_NOW, SEQ.LAST_NUMBER  , SEQ.* FROM ALL_SEQUENCES SEQ
--UPDATE ALL_SEQUENCES SET LAST_NUMBER = 36001
WHERE SEQUENCE_NAME LIKE '%BATCH%NUM%' AND SEQUENCE_OWNER = 'EPMM';

DECLARE
    V_BATCH_VALUE NUMBER := 0;
BEGIN

    FOR I IN 1..5118 LOOP
        SELECT EPMM.BATCH_NUMBER.nextval INTO V_BATCH_VALUE FROM DUAL;
        DBMS_OUTPUT.PUT_LINE('BATCH_NUMBER: ' || V_BATCH_VALUE);
    END LOOP;
END;
/***************************************** /Restriccion UNICA EPMM.SDIPRDPCIP1 *******************************************/

/***************************************** 9 - Case Pack Ya Existe Para El Proveedor *******************************************/
SELECT * FROM PIM_PRODUCTO_ATRIB
--UPDATE PIM_PRODUCTO_ATRIB SET VALOR = '7380902923007'
WHERE ID_PIM_PROD = 782 AND COD_ATRIBUTO = 'Proveedor'; --1089

SELECT  RPAD(1089, 15, ' ') FROM DUAL; -- '1089           '


SELECT V.VPC_TECH_KEY
  INTO V_VPC_TECH_KEY
FROM VPCMSTEE V
WHERE V.VENDOR_NUMBER = RPAD(V_VENDOR_NUMBER, 15, ' ');

SELECT V.VPC_TECH_KEY, V.*
-- INTO V_VPC_TECH_KEY
FROM VPCMSTEE V
WHERE V.VENDOR_NUMBER = RPAD(1089, 15, ' ');

SELECT * FROM VPCPRDEE CP
WHERE CP.VPC_TECH_KEY = 14241
    AND CP.VPC_CASE_PACK_ID = RPAD('P1024G', 25, ' ');

/*
SELECT COUNT(1)
INTO V_COUNT
FROM VPCPRDEE CP
WHERE CP.VPC_TECH_KEY = V_VPC_TECH_KEY
AND CP.VPC_CASE_PACK_ID = RPAD(V_SKU_PROVEEDOR, 25, ' ');
 */
/***************************************** /9 - Case Pack Ya Existe Para El Proveedor *******************************************/

/*****************************************************************************/
-- /ERRORES MAPEADOS DEL PKG_PIM_INTEGRACION
/*****************************************************************************/

-- SP_GET_TRAMAS_PENDIENTES
SELECT ID_MODELO, PIM.FEC_CREACION, PIM.FLG_PROCESADO, PIM.FLG_ERROR,PIM.FEC_PROCESO --, PIM.*
    --PIM.ID_MODELO, TO_CLOB(TO_NCLOB(PIM.CONTENIDO)) CONTENIDO,
FROM edsr.pim_modelo PIM
WHERE ID_TIPO = 1
      AND NOT FLG_PROCESADO = '0'
      AND NOT FLG_ERROR = '0'
     -- AND TRUNC(FEC_CREACION) = TRUNC(SYSDATE) - 1
     -- AND FEC_PROCESO IS NULL
ORDER BY FEC_CREACION DESC;

--GET SKU
SELECT
 Id_Modelo, Id_Tipo --,TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO
FROM edsr.pim_modelo
WHERE id_tipo = 2 and FLG_PROCESADO = '0';


SELECT * FROM EDSR.PIM_MODELO
--UPDATE edsr.pim_modelo SET FLG_PROCESADO = '0', FLG_ERROR = '0'
WHERE ID_MODELO >= 1011;

-- SP_GET_TRAMAS_PENDIENTES: Tramas a Procesar desde INICIO, esto indica que obtendra una lista para crear productos y sus atributos correspondientes.
SELECT ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO  FROM EDSR.PIM_MODELO
-- UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '1'
WHERE ID_TIPO = 1 and FLG_PROCESADO = '0' and FLG_ERROR = '0'
ORDER BY FEC_CREACION;

SELECT ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO  FROM EDSR.PIM_MODELO
-- UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '0'
WHERE ID_TIPO = 2 and FLG_PROCESADO = '0' and FLG_ERROR = '0'
ORDER BY FEC_CREACION;

-- SP_GET_TRAMAS_PENDIENTES: Tramas a Procesar para ACTUALIZAR, esto indica que obtendra una lista para actualizar productos y sus atributos correspondientes.
SELECT ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO FROM EDSR.PIM_MODELO
-- UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '1'
WHERE ID_TIPO = 3 and FLG_PROCESADO = '0' and FLG_ERROR = '0'
ORDER BY FEC_CREACION;

-- Listar para mandar a OIC
SELECT  Id_Modelo, Id_Tipo, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO,FLG_PROCESADO
FROM edsr.pim_modelo WHERE id_tipo = 2 and FLG_PROCESADO = '0'
ORDER BY FEC_CREACION DESC;

/*
VALIDAR_DATA_PIM (EL PROVEEDOR NO EXISTE)
SP_VALIDAR_NUEVO -> VALIDAR_PROVEEDOR -> (2)

ID_TIPO
1: Crear producto PIM a PMM
2: Actualizar SKU PMM a PIM
3: Actualizar atributos
 */
SELECT * FROM edsr.pim_modelo WHERE ID_MODELO > 847;
SELECT * FROM EDSR.PIM_MODELO WHERE TRUNC(FEC_CREACION) = TRUNC(SYSDATE) ORDER BY FEC_CREACION DESC;
SELECT * FROM EDSR.PIM_MODELO WHERE TRUNC(FEC_CREACION) = TRUNC(TO_DATE('2024-03-22','YYYY-MM-DD')) ORDER BY FEC_CREACION DESC;
SELECT * FROM EDSR.PIM_MODELO WHERE TRUNC(FEC_CREACION) >= TRUNC(SYSDATE) - INTERVAL '5' DAY ORDER BY FEC_CREACION DESC;
SELECT M.ID_MODELO,M.ID_TIPO,M.FLG_PROCESADO,M.FEC_CREACION, TO_CHAR(FEC_CREACION,'YYYYMMDD'),TRUNC(FEC_CREACION),TRUNC(SYSDATE) - INTERVAL '3' DAY FROM EDSR.PIM_MODELO M ORDER BY FEC_CREACION DESC;
SELECT M.ID_MODELO,M.ID_TIPO,M.FLG_PROCESADO,M.FEC_CREACION FROM EDSR.PIM_MODELO M WHERE TO_CHAR(FEC_CREACION,'YYYYMMDD') = '20240322' ORDER BY FEC_CREACION DESC;
SELECT M.ID_MODELO,M.ID_TIPO,M.FLG_PROCESADO,M.FEC_CREACION FROM EDSR.PIM_MODELO M WHERE TRUNC(FEC_CREACION) = TRUNC(TO_DATE('2024-03-22','YYYY-MM-DD')) ORDER BY FEC_CREACION DESC;
SELECT M.ID_MODELO,M.ID_TIPO,M.FLG_PROCESADO,M.FEC_CREACION FROM EDSR.PIM_MODELO M WHERE TRUNC(FEC_CREACION) >= TRUNC(SYSDATE) - INTERVAL '5' DAY ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.pim_modelo WHERE FLG_PROCESADO = '0' ORDER BY ID_MODELO DESC;
SELECT * FROM edsr.pim_modelo WHERE ID_TIPO = 1 ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.pim_modelo WHERE ID_TIPO = 2 ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.pim_modelo WHERE ID_TIPO = 3 ORDER BY FEC_CREACION DESC;
SELECT FLG_PROCESADO,FLG_ERROR, ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO FROM edsr.pim_modelo
-- UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '1'
WHERE ID_MODELO IN (646);

SELECT * FROM edsr.PIM_PRODUCTO ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.PIM_PRODUCTO WHERE ID_PIM_PROD = 704;
SELECT * FROM edsr.PIM_PRODUCTO WHERE ID_PIM = 'HESA_TEST_100118';
SELECT * FROM edsr.PIM_PRODUCTO_ATRIB WHERE ID_PIM = 'HESA_PRUEBA_100050';
-- LV: Lista de Valores
-- TL: Texto Libre
SELECT COD_ATRIBUTO,DECODE(FLG_ID_VAL, 'TL', VALOR, NVL(ID,VALOR)) FROM PIM_PRODUCTO_ATRIB
WHERE ID_PIM_PROD = 606 AND COD_ATRIBUTO   = 'PesoUnidadLogistica';




SELECT * FROM edsr.pim_modelo ORDER BY FEC_CREACION DESC;

SELECT * FROM EDSR.PIM_MODELO
--UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '0'
WHERE ID_TIPO = 2 AND ID_MODELO >= 843;

SELECT FLG_PROCESADO,FLG_ERROR, ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO FROM edsr.pim_modelo
--UPDATE edsr.pim_modelo SET FLG_PROCESADO = '1', FLG_ERROR = '0'
WHERE ID_MODELO = 710 and FLG_PROCESADO = '0' and FLG_ERROR = '0';

SELECT FLG_PROCESADO,FLG_ERROR, ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO FROM edsr.pim_modelo
--UPDATE edsr.pim_modelo SET FLG_PROCESADO = '1', FLG_ERROR = '0'
WHERE ID_MODELO IN (
870,
871,
866,
869,
868,
867) and FLG_PROCESADO = '0' and FLG_ERROR = '0';

DECLARE
    in_ID_PIM_PROD     PIM_PRODUCTO.ID_PIM_PROD%type;
    in_ID_PIM          PIM_PRODUCTO.ID_PIM%type := 'HESA_PRUEBA_100050';
    in_ID_MODELO       PIM_PRODUCTO.ID_MODELO%type := 710;
    in_DESCRIPCION     PIM_PRODUCTO.DESCRIPCION%type := 'Lapiz Plumon Ceramica Retiro 59x2';
    in_prd_lvl_number  PIM_PRODUCTO.prd_lvl_number%type default '';
BEGIN

    BEGIN
        --PKG_PIM_INTEGRACION.SP_INS_PIM_PRODUCTO(in_ID_PIM,in_ID_MODELO,in_DESCRIPCION,in_ID_PIM_PROD,in_prd_lvl_number);
        PKG_PIM_INTEGRACION.SP_INS_PIM_PRODUCTO(in_ID_PIM,in_ID_PIM_PROD);
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('EXCEPTION: ' || SQLERRM) ;
    END;
END;

-- DEBUG
DECLARE
    V_RETORNO    VARCHAR2(50);
    V_PESO_BRUTO  NUMBER(15,4);
BEGIN
  SELECT DECODE(FLG_ID_VAL, 'TL', VALOR, NVL(ID,VALOR))
    INTO V_RETORNO
  FROM PIM_PRODUCTO_ATRIB
  WHERE ID_PIM_PROD    = 646
    AND COD_ATRIBUTO   = 'PesoUnidadLogistica';

  DBMS_OUTPUT.PUT_LINE('V_RETORNO: ' || V_RETORNO) ;
  V_PESO_BRUTO := TO_VARCHAR(V_RETORNO,'9999999999.99999');

  DBMS_OUTPUT.PUT_LINE('V_PESO_BRUTO: ' || V_PESO_BRUTO) ;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('EXCEPTION: ' || SQLERRM) ;
END;


SELECT VPC_CASE_GROSS_WGT FROM SDIVPCCSI;
SELECT * FROM PRDMSTEE WHERE PRD_NAME_FULL LIKE '%MESA%MINI%BLANC%52X37CM%ORANGE%';
SELECT ID_PIM,COD_ATRIBUTO, FLG_ID_VAL, VALOR, ID FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD    = 606;

SELECT ID_PIM, PRD_LVL_CHILD, PRD_LVL_NUMBER, prd_name_full, estadoProducto, dun14, razon_social, codigo_proveedor
              , umi, ean, umv, sku_proveedor, tipo_surtido
FROM EDSR.PIM_PRODUCTO_DATA_PMM;




-- Procesar para que no se manden a OIC
SELECT * FROM edsr.pim_modelo
--UPDATE PIM_MODELO SET FLG_PROCESADO = '1'
WHERE ID_TIPO = 2 AND FLG_PROCESADO = '0' AND ID_MODELO IN (765,763);--  AND ID_MODELO>=755 AND ID_MODELO <=762 --AND ID_MODELO NOT IN (752,753,754);

--ULTIMO PASO: SP_ACTUALIZA_PIM_MODELO
/*
UPDATE PIM_MODELO
SET flg_procesado = '1',
    Mensaje = 'OK',
    FEC_PROCESO = sysdate
WHERE ID_TIPO = 2 AND ID_MODELO = in_id_Modelo;
 */



create table PIM_PRODUCTO
(
    ID_PIM_PROD    NUMBER(18)           not null constraint PK_PIM_PRODUCTO primary key,
    ID_MODELO      NUMBER(18)           not null,
    ID_PIM         VARCHAR2(18)         not null,
    DESCRIPCION    VARCHAR2(50)         not null,
    FEC_CREACION   DATE default SYSDATE not null,
    FLG_PROCESADO  CHAR default '0'     not null constraint CH_PIM_PRODUCTO_PROCESADO check (flg_procesado IN ('0', '1')),
    FEC_PROCESO    DATE,
    PRD_LVL_CHILD  NUMBER(12),
    FLG_ERROR      CHAR default '0'     not null constraint CH_PIM_PRODUCTO_ERROR check (flg_error IN ('0', '1')),
    MENSAJE        VARCHAR2(4000),
    PRD_LVL_NUMBER VARCHAR2(50)
);

create table PIM_PRODUCTO
(
    ID_PIM_PROD    NUMBER(18)           not null constraint PK_PIM_PRODUCTO primary key,
    ID_MODELO      NUMBER(18)           not null,
    ID_PIM         VARCHAR2(18)         not null,
    DESCRIPCION    VARCHAR2(50)         not null,
    FEC_CREACION   DATE default SYSDATE not null,
    FLG_PROCESADO  CHAR default '0'     not null constraint CH_PIM_PRODUCTO_PROCESADO check (flg_procesado IN ('0', '1')),
    FEC_PROCESO    DATE,
    PRD_LVL_CHILD  NUMBER(12),
    FLG_ERROR      CHAR default '0'     not null constraint CH_PIM_PRODUCTO_ERROR check (flg_error IN ('0', '1')),
    MENSAJE        VARCHAR2(4000),
    PRD_LVL_NUMBER VARCHAR2(50)
);




SELECT p.prd_lvl_child, trim(p.prd_lvl_number) prd_lvl_number, trim(p.prd_name_full) prd_name_full
             --campos nuevos
             , TO_CHAR(est.prd_status) prd_status, to_char(dun.prd_upc) dun14, prov.vendor_name, to_char(prov.vendor_number) vendor_number
             , vpc.INV_UOM UMI, to_char(ean.prd_upc) ean, vpc.VPC_CASE_QTY_UOM, vpc.VPC_CASE_PACK_ID sku_proveedor
             , tipo_surt.ATR_CODE tipo_surtido
 FROM prdmstee p
 INNER JOIN (select e.PRD_LVL_CHILD, e.prd_status,
       row_number() over(partition by PRD_LVL_CHILD order by EFFECT_DATE desc) rn
       from PRDSTEEE e) est
   on est.PRD_LVL_CHILD = p.PRD_LVL_CHILD and est.rn = 1
 LEFT JOIN PRDUPCEE dun on dun.PRD_LVL_CHILD = p.PRD_LVL_CHILD and dun.upc_type = 14 and dun.active_flag ='T'
 LEFT JOIN PRDUPCEE ean on dun.PRD_LVL_CHILD = p.PRD_LVL_CHILD and dun.upc_type = 13 and dun.default_flag ='T'
 LEFT JOIN vpcprdee vpc on dun.vpc_prd_tech_key = vpc.vpc_prd_tech_key
 LEFT JOIN vpcmstee prov on vpc.vpc_tech_key = prov.vpc_tech_key
 LEFT JOIN basatpee des_atr on p.PRD_LVL_CHILD = des_atr.PRD_LVL_CHILD and atr_hdr_tech_key = 141
 LEFT JOIN basacdee tipo_surt on des_atr.ATR_COD_TECH_KEY = tipo_surt.ATR_COD_TECH_KEY;



SELECT B.ID_PIM, A.*
        FROM (
             SELECT p.prd_lvl_child, trim(p.prd_lvl_number) prd_lvl_number, trim(p.prd_name_full) prd_name_full
             --campos nuevos
             , TO_CHAR(est.PRD_STATUS_DESC) prd_status, to_char(dun.prd_upc) dun14, prov.vendor_name, to_char(prov.vendor_number) vendor_number
             , vpc.INV_UOM UMI, to_char(ean.prd_upc) ean, vpc.VPC_CASE_QTY_UOM, vpc.VPC_CASE_PACK_ID sku_proveedor
             , tipo_surt.ATR_CODE tipo_surtido
             FROM prdmstee p
             inner join (select e.PRD_LVL_CHILD, e.prd_status, des.PRD_STATUS_DESC,
                   row_number() over(partition by PRD_LVL_CHILD order by EFFECT_DATE desc) rn
                   from PRDSTEEE e INNER JOIN EDSR.PRDSTSEE des on des.PRD_STATUS = e.PRD_STATUS) est
               on est.PRD_LVL_CHILD = p.PRD_LVL_CHILD and est.rn = 1
             left join PRDUPCEE dun on dun.PRD_LVL_CHILD = p.PRD_LVL_CHILD and dun.upc_type = 14 and dun.active_flag ='T'
             left join PRDUPCEE ean on EAN.PRD_LVL_CHILD = p.PRD_LVL_CHILD and EAN.upc_type IN (7,8,12,13) and EAN.default_flag ='T'
             left join vpcprdee vpc on dun.vpc_prd_tech_key = vpc.vpc_prd_tech_key
             left join vpcmstee prov on vpc.vpc_tech_key = prov.vpc_tech_key
             left join basatpee des_atr on p.PRD_LVL_CHILD = des_atr.PRD_LVL_CHILD and atr_hdr_tech_key = 141
             left join basacdee tipo_surt on des_atr.ATR_COD_TECH_KEY = tipo_surt.ATR_COD_TECH_KEY
        ) A --SELECT DE PMM CON LA DATA ACTUALIZADA

        INNER JOIN (
              SELECT ID_PIM, PRD_LVL_CHILD, PRD_LVL_NUMBER, prd_name_full, estadoProducto, dun14, razon_social, codigo_proveedor
              , umi, ean, umv, sku_proveedor, tipo_surtido
              FROM EDSR.PIM_PRODUCTO_DATA_PMM

        ) B --SELECT DE LA TABLA PIM_PRODUCTO_DATA_PMM (DATA SNAPSHOT)
        ON A.prd_lvl_child = B.prd_lvl_child
        WHERE NVL(TRIM(A.prd_status), 'XX') <> NVL(TRIM(B.estadoProducto), 'XX')
              OR NVL(TRIM(A.dun14), 'XX') <> NVL(TRIM(B.dun14), 'XX')
              OR NVL(TRIM(A.vendor_name), 'XX') <> NVL(TRIM(B.razon_social), 'XX')
              OR NVL(TRIM(A.vendor_number), 'XX') <> NVL(TRIM(B.codigo_proveedor), 'XX')
              OR NVL(TRIM(A.UMI), 'XX') <> NVL(TRIM(B.UMI), 'XX')
              OR NVL(TRIM(A.ean), 'XX') <> NVL(TRIM(B.ean), 'XX')
              OR NVL(TRIM(A.VPC_CASE_QTY_UOM), 'XX') <> NVL(TRIM(B.umv), 'XX')
              OR NVL(TRIM(A.sku_proveedor), 'XX') <> NVL(TRIM(B.sku_proveedor), 'XX')
              OR NVL(TRIM(A.tipo_surtido), 'XX') <> NVL(TRIM(B.tipo_surtido), 'XX');

SELECT * FROM EDSR.PIM_MODELO M WHERE ID_TIPO IN (3) AND FLG_PROCESADO = '0' ORDER BY FEC_CREACION DESC;
SELECT MAX(ID_MODELO) FROM EDSR.PIM_MODELO M;
SELECT PIM_MODELO.NEXT FROM DUAL;

INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75302, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"AlturaUnidadLogistica","ValorModificado":"60"}]}', TIMESTAMP '2024-10-16 17:31:42', '1', null, '0', null, '12476797519935423');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75303, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"AnchoUnidadLogistica","ValorModificado":"120"}]}', TIMESTAMP '2024-10-16 17:31:42', '1', null, '0', null, '12476827087007787');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75295, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"CantidadMasterpack","ValorModificado":"22"}]}', TIMESTAMP '2024-10-16 17:31:41', '1', null, '0', null, '12476802837669787');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75288, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"ClusterSurtido","ValorModificado":"Sin Cluster"}]}', TIMESTAMP '2024-10-16 17:31:41', '1', null, '0', null, '12658648758480144');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75283, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"CodigoLineaPromart","ValorModificado":"L0732-Porcelanato Marmolizado"}]}', TIMESTAMP '2024-10-16 17:31:40', '1', null, '0', null, '12476765958859343');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75284, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"CodigoProveedor","ValorModificado":"0190066304001"}]}', TIMESTAMP '2024-10-16 17:31:40', '1', null, '0', null, '12659206712847987');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75294, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"Costo","ValorModificado":"25.2504"}]}', TIMESTAMP '2024-10-16 17:31:41', '1', null, '0', null, '12658902695754776');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75298, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"DUN14","ValorModificado":"12500000371803"}]}', TIMESTAMP '2024-10-16 17:31:42', '1', null, '0', null, '12476875012811613');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75285, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"Marca","ValorModificado":"ITALPISOS \\ ITALPISOS"}]}', TIMESTAMP '2024-10-16 17:31:40', '1', null, '0', null, '12658824397183590');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75300, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"MasterPackTipo","ValorModificado":"Caja"}]}', TIMESTAMP '2024-10-16 17:31:42', '1', null, '0', null, '12476799413775005');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75299, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"NumeroPiezas","ValorModificado":"3"}]}', TIMESTAMP '2024-10-16 17:31:42', '1', null, '0', null, '12658890194180918');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75301, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"Perecible","ValorModificado":"No"}]}', TIMESTAMP '2024-10-16 17:31:42', '1', null, '0', null, '12658960307095936');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75307, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"PesoProducto","ValorModificado":".000125"}]}', TIMESTAMP '2024-10-16 17:31:43', '1', null, '0', null, '12658831839237347');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75306, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"PesoUnidadLogistica","ValorModificado":"47"}]}', TIMESTAMP '2024-10-16 17:31:43', '1', null, '0', null, '12658706106102868');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75293, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"PrecioUnitario","ValorModificado":"58.0179"}]}', TIMESTAMP '2024-10-16 17:31:41', '1', null, '0', null, '12658691432042861');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75304, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"ProfundidadUnidadLogistica","ValorModificado":"3.6"}]}', TIMESTAMP '2024-10-16 17:31:43', '1', null, '0', null, '12658876299074509');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75292, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"PuntoPrecio","ValorModificado":"Good"}]}', TIMESTAMP '2024-10-16 17:31:41', '1', null, '0', null, '12658663509015114');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75308, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"Rendimiento","ValorModificado":"2.16"}]}', TIMESTAMP '2024-10-16 17:31:43', '1', null, '0', null, '12659216146504472');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75296, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"SkuProveedor","ValorModificado":"1136E2C2000701"}]}', TIMESTAMP '2024-10-16 17:31:42', '1', null, '0', null, '12658875411135409');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75297, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"TipoCodigoEAN","ValorModificado":"Ean/Upc 13"}]}', TIMESTAMP '2024-10-16 17:31:42', '1', null, '0', null, '12476828740112648');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75286, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"TipoMarca","ValorModificado":"Propia"}]}', TIMESTAMP '2024-10-16 17:31:40', '1', null, '0', null, '12658724486031368');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75287, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"TipoNegociacion","ValorModificado":"Propia"}]}', TIMESTAMP '2024-10-16 17:31:41', '1', null, '0', null, '12476809703757506');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75289, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"TipoSurtido","ValorModificado":"H"}]}', TIMESTAMP '2024-10-16 17:31:41', '1', null, '0', null, '12476889651275060');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75290, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"UnidadMedidadInventarioUMI","ValorModificado":"UN"}]}', TIMESTAMP '2024-10-16 17:31:41', '1', null, '0', null, '12658854880093935');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75291, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"UnidadMedidaVenta","ValorModificado":"UN"}]}', TIMESTAMP '2024-10-16 17:31:41', '1', null, '0', null, '12658744796882032');
INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (75305, 3, '{"productos":[{"IdPim":"HESA_40921","NombreProducto":"ITALPISOS REALI CREMA 60X120 2.16M2","sku":"37180","codAtributoPIM":"VolumendelaUnidadLogistica","ValorModificado":"6.912"}]}', TIMESTAMP '2024-10-16 17:31:43', '1', null, '0', null, '12658831907904332');

SELECT * FROM PIM_ATRIBUTO ORDER BY COD_ATRIBUTO;
SELECT
   --* -- COUNT(*)
    PIM.*, JSON.*
FROM EDSR.PIM_MODELO PIM
    ,JSON_TABLE(PIM.CONTENIDO,
                '$.productos[*]'
                COLUMNS (IdPim VARCHAR2(15) PATH '$.IdPim',
                        NombreProducto VARCHAR2(100) PATH '$.NombreProducto',
                        SKU VARCHAR2(8) PATH '$.sku',
                        CodigoAtributo VARCHAR2(50) PATH '$.codAtributoPIM',
                        ValorModificado VARCHAR2(120) PATH '$.ValorModificado')
                ) JSON

WHERE JSON.ValorModificado IS NOT NULL
    AND JSON.IdPim = 'HESA_40921'
    AND PIM.FEC_CREACION >= TO_DATE('2024-10-16', 'YYYY-MM-DD')
    AND PIM.FEC_CREACION < TO_DATE('2024-10-17', 'YYYY-MM-DD')
ORDER BY JSON.CodigoAtributo
;

UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '0', FLG_ERROR = '0'
WHERE JSON_VALUE(CONTENIDO, '$.productos[0].sku') = '36161';
COMMIT;

UPDATE EDSR.PIM_MODELO
SET CONTENIDO = JSON_TRANSFORM(CONTENIDO,
    SET '$.productos[*].sku' = '36161')
WHERE JSON_VALUE(CONTENIDO, '$.productos[0].sku') = '37180';
COMMIT;

SELECT CONTENIDO
FROM EDSR.PIM_MODELO
WHERE JSON_VALUE(CONTENIDO, '$.productos[0].sku') = '36161';

SELECT m.CONTENIDO
FROM EDSR.PIM_MODELO m
WHERE JSON_EXISTS(m.CONTENIDO, '$.productos[*].sku')
AND JSON_VALUE(m.CONTENIDO, '$.productos[0].sku') = '37180';

-- DEBUG

SELECT * FROM PIM_PRODUCTO WHERE ID_PIM_PROD = 905;
SELECT * FROM PRDMSTEE WHERE PRD_LVL_NUMBER = '36161';

SELECT * FROM PIM_PRODUCTO ORDER BY ID_PIM_PROD DESC;
SELECT ATRIB.ID_PIM_PROD, ATRIB.* FROM PIM_PRODUCTO_ATRIB ATRIB ORDER BY ATRIB.ID_PIM_PROD DESC;
SELECT * FROM PIM_PRODUCTO WHERE ID_PIM_PROD = 973;
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD = 975;
SELECT DISTINCT ID_PIM_PROD FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD = 974; --6615

SELECT COD_ATRIBUTO, NOMBRE_ATRIB_PIM FROM PIM_ATRIBUTO;
SELECT COD_ATRIBUTO FROM PIM_ATRIBUTO WHERE NOMBRE_ATRIB_PIM = 'AlturaUnidadLogistica';

SELECT  ID_PIM, COD_ATRIBUTO, ID,
              VALOR, UND_MEDIDA, FLG_UND_MEDIDA,
              FLG_ID_VAL, FLG_CAMPO_ADD, ATR_TYP_TECH_KEY,
              ATR_HDR_TECH_KEY, ID_PIM_PROD
      FROM PIM_PRODUCTO_ATRIB
      WHERE ID_PIM_PROD = 973;


DECLARE
    V_ID_PIM_PROD NUMBER := 975;
    V_MASIVO NUMBER := 0;
    V_PRD_LVL_CHILD NUMBER;
    V_MIN NUMBER := 973;
    V_MAX NUMBER := 998;
BEGIN

    IF V_MASIVO = 1 THEN
        WHILE V_MIN <= V_MAX LOOP
            V_ID_PIM_PROD := V_MIN;
            PKG_PIM_INTEGRACION.SP_MODIFICAR_PRODUCTO_ATRIBUTO(V_ID_PIM_PROD,V_PRD_LVL_CHILD);
            DBMS_OUTPUT.PUT_LINE('ID_PIM_PROD: ' || V_ID_PIM_PROD);
            DBMS_OUTPUT.PUT_LINE('V_PRD_LVL_CHILD: ' || V_PRD_LVL_CHILD);

            V_MIN := V_MIN + 1;
        END LOOP;
    ELSE
        PKG_PIM_INTEGRACION.SP_MODIFICAR_PRODUCTO_ATRIBUTO(V_ID_PIM_PROD,V_PRD_LVL_CHILD);
        DBMS_OUTPUT.PUT_LINE('ID_PIM_PROD: ' || V_ID_PIM_PROD);
        DBMS_OUTPUT.PUT_LINE('V_PRD_LVL_CHILD: ' || V_PRD_LVL_CHILD);
    END IF;
END;

UPDATE PIM_MODELO SET FLG_PROCESADO = '1' WHERE ID_MODELO IN (75302,75303); COMMIT;
UPDATE PIM_MODELO SET FLG_PROCESADO = '0' WHERE ID_MODELO IN (75295,75288,75283,75284,75294,75298,75285,75300,75299,75301,75307,75306,75293,75304,75292,75308,75296,75297,75286,75287,75289,75290,75291,75305);
COMMIT ;