SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE FROM PIM_MODELO WHERE ID_TIPO = 1 ORDER BY  FEC_CREACION DESC;
SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE FROM PIM_MODELO ORDER BY  FEC_CREACION DESC;
SELECT * FROM EDSR.PIM_MODELO M  WHERE TRUNC(FEC_CREACION) = TRUNC(SYSDATE) and ID_TIPO IN (1,2) ORDER BY FEC_CREACION DESC;
SELECT * FROM EDSR.PIM_MODELO M  WHERE TRUNC(FEC_CREACION) = TRUNC(SYSDATE) and ID_TIPO IN (1,2) ORDER BY FEC_CREACION DESC;
SELECT * FROM PIM_PRODUCTO       WHERE ID_PIM IN ('HESA_TEST_9989');
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM IN ('HESA_TEST_9989') and ID_PIM_PROD = 897;

SELECT * FROM PIM_MODELO
--UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '0'
WHERE ID_MODELO IN (33255) AND ID_TIPO = 1 ;

SELECT * FROM pim_atributo ;
insert into EDSR.PIM_ATRIBUTO (COD_ATRIBUTO, DES_ATRIBUTO, FLG_UND_MEDIDA, FLG_ID_VAL, FLG_CAMPO_ADD, ATR_TYP_TECH_KEY, ATR_HDR_TECH_KEY, NOMBRE_ATRIB_PIM) values ('Rendimiento', 'Campo Adicional, LABEL: Cant. M2 x Caja ', '0', 'TL', '0', null, null, null);

DECLARE
    NUM NUMBER(6,2);
BEGIN
    NUM := NVL(TRIM(' '),0);
    DBMS_OUTPUT.PUT_LINE(NUM);
END;

SELECT * FROM edsr.Pim_Producto
--UPDATE edsr.Pim_Producto SET  FLG_PROCESADO = '1',  FEC_PROCESO = NULL
WHERE ID_PIM_PROD IN (896);

SELECT pp.ID_PIM_PROD, pp.DESCRIPCION
    FROM edsr.Pim_Producto pp
        inner join edsr.pim_modelo pm on pm.id_modelo = pp.id_modelo
    WHERE pp.FEC_PROCESO IS NULL and pp.FLG_PROCESADO = '0'
        and pm.id_tipo = 1
    ORDER BY pp.ID_PIM_PROD;

--Atributos o

--Campos adicionales =< oc
-- CP: Rendimiento => Cant. M2 x Caja
SELECT * FROM BASGENEE WHERE entity_name = 'PRDMSTEE';



--SDIPRDATI
-- SDI: Tabla trabajo
-- Hay un CronJob que dispara de la tabla de Trabajo (SDI) hacia las tablas de Negocio
-- Normalmente existen FUNCIONES nativas de PMM que realizan estas tareas, pero tambien puede haber un cronJob o Trigger que lo realice.
SELECT * FROM SDIVALMSI;
SELECT (SEQ.LAST_NUMBER - 1) AS SEQUENCE_NOW, SEQ.LAST_NUMBER  , SEQ.* FROM ALL_SEQUENCES SEQ WHERE SEQUENCE_NAME LIKE '%SEQ_SDIVALMSI%'; -- AND SEQUENCE_OWNER = 'EPMM';
SELECT SEQ_SDIVALMSI.NEXTVAL FROM DUAL;
--SEQ_SDIVALMSI.NEXTVAL

/*
28498
28499
28500
28501
28502
28503
28504
*/

-- 13/09/2024 => Queda pendiente agregar logica para el escenario en donde haya mas de un Campo Adicional
DECLARE
    V_SEQ_SDIVALMSI NUMBER := SEQ_SDIVALMSI.NEXTVAL;
BEGIN

EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ''.,''';
INSERT INTO SDIVALMSI
    (AUDIT_NUMBER,
    -- BATCH_NUM,
     TRAN_TYPE,
     PRD_LVL_ID,
     PRD_LVL_NUMBER,
     FIELD_CODE,
     ENTITY_NAME, --
     VALUE,
     DATE_CREATED)
  VALUES
    (V_SEQ_SDIVALMSI,
  --   7899,
     'A', --A: Add C: Change
        1,
     '10505',
     'CP',
     'PRDMSTEE',
     90,
     SYSDATE);
COMMIT;

--EPMM.SDIVALIM(in_batch_num => 7899);
EPMM.SDIVALIM(IN_BATCH_NUM => V_SEQ_SDIVALMSI);


END;

--Tabla de usuarios
SELECT * FROM basusree WHERE USR_SIGNON like '%DFL%';
--Tabla en el que se registra CP PRODUCTOS por CHILD (TECH_KEY1) y sus valores
SELECT * FROM basvalee ;

-- Tipos de atributos
SELECT * FROM BASATYEE ;
-- Subtipo de atributo
SELECT * FROM BASAHREE ;
-- Código de atributo
SELECT * FROM BASACDEE ;
-- Aplicaciones
SELECT * FROM APPAPPEE ;
-- Atributos/Aplicación
SELECT * FROM BASAAXEE ;

--Atributos Prd por Org
SELECT * FROM BASAPLEE;
--Proveedor/Atributos
SELECT * FROM VPCATVEE;
--Prod. asignados a atributos
SELECT * FROM BASATPEE;
--Org/Prod asignados a atributos
SELECT * FROM BASATBEE;
--Org. asignados a atributos
SELECT * FROM BASATOEE;

--Audit de Prod. asignados a atributos
SELECT * FROM BASATPAE;
--Audit de Org. asignados a atributos
SELECT * FROM BASATOAE;

--Atr Restring
SELECT * FROM BASAPREE;
--Atr / Dim
SELECT * FROM BASADXEE;

--Validacion
--24130 PRODUCTOS CON AFECTO: F
--305   PRODUCTOS CON AFECTO: T

SELECT * FROM PRDMSTEE WHERE PRD_LVL_NUMBER = '36205'; --100497, 100498
SELECT PRD.AFECTO, PRD.* FROM TPPRDMST PRD WHERE PRD_LVL_NUMBER = '36205'; --100497, 100498
SELECT PRD.AFECTO, PRD.* FROM TPPRDMST PRD WHERE AFECTO = 'T'; --100497, 100498

SELECT * FROM ALL_SOURCE;

SELECT PRD.AFECTO, PRD.PRD_LVL_NUMBER, BSV.* FROM basvalee BSV INNER JOIN TPPRDMST PRD ON PRD.PRD_LVL_CHILD = BSV.TECH_KEY1
 WHERE PRD.PRD_LVL_NUMBER IN ('36208','36209');

-- Tabla en la que se inserta la operacion y lista si hay algun Error sino se borra el registro.
SELECT MSI.VAL_ERR_CODE, ERR.REJ_DESC,MSI.*
FROM SDIVALMSI MSI
    LEFT JOIN SDIREJCD ERR ON MSI.VAL_ERR_CODE = ERR.REJ_TECH_KEY
;

SELECT * FROM SDIVALMSI ORDER BY AUDIT_NUMBER DESC ;

SELECT V.PRD_LVL_ID, V.* FROM prdmstee V WHERE PRD_LVL_NUMBER = '28505';
SELECT * FROM prdmstee V WHERE PRD_LVL_ID = 1;
SELECT * FROM prdmstee V WHERE PRD_LVL_ID = 2;
SELECT * FROM prdmstee V WHERE PRD_LVL_ID = 3;
SELECT * FROM prdmstee V WHERE PRD_LVL_ID = 4;
SELECT * FROM prdmstee V WHERE PRD_LVL_ID = 5;


--SDIVALIM(AUDIT_NUMBER);
-- Campo Validacion: VAL_ERR_CODE
SELECT VAL_ERR_CODE FROM SDIVALMSI;
--Tabla de Errores
SELECT * FROM SDIREJCD;


SELECT * FROM ALL_SOURCE WHERE UPPER(TEXT)  LIKE '%SDIVALMSI%';
SELECT * FROM ALL_SOURCE WHERE UPPER(TEXT)  LIKE '%SDIVALI%' ;

--Tabla Negocio
--TECH_KEY1_LVL_ID: Nivel producto
--TECH_KEY1: Child
SELECT * FROM prdmstee V ;
SELECT * FROM prdmstee V WHERE PRD_LVL_NUMBER = '28505';
SELECT * FROM prdmstee V WHERE TRIM(V.PRD_NAME_FULL) = trim('SERVICIO ARMADO PROMOCIONAL');

SELECT BSV.* FROM basvalee BSV
WHERE BSV.tech_key1 = 'P_TECH_KEY1'
 AND BSV.entity_name = 'PRDMSTEE'
 AND BSV.field_code = 'CP'
;