SELECT * FROM EDSR.PIM_MODELO M WHERE TRUNC(FEC_CREACION) = TRUNC(SYSDATE) ORDER BY FEC_CREACION DESC;
SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, CONTENIDO FROM PIM_MODELO WHERE ID_TIPO = 1 ORDER BY  FEC_CREACION DESC;
SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE FROM PIM_MODELO WHERE ID_TIPO = 2 ORDER BY  FEC_CREACION DESC;
SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE FROM PIM_MODELO WHERE ID_TIPO = 3 ORDER BY  FEC_CREACION DESC;
SELECT ID_MODELO, ID_TIPO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE FROM PIM_MODELO WHERE ID_TIPO = 4 ORDER BY  FEC_CREACION DESC;

INSERT INTO EDSR.PIM_MODELO (ID_MODELO, ID_TIPO, CONTENIDO, FEC_CREACION, FLG_PROCESADO, FEC_PROCESO, FLG_ERROR, MENSAJE, MESSAGE_ID) VALUES (4430, 1, '{"productos":[{"IdPim":"HESA_TEST_40067","NombreProducto":"TUBO EST CUADRADO 50X50X3.00X6","CodigoLineaPromart":"L0320-Perfiles Metalicos","CodigoProveedor":"1790004724001  ","Marca":"ADELCA","TipoMarca":"Proveedor","TipoNegociacion":"Propia","ClusterSurtido":"Sin Cluster","TipoSurtido":"L","UnidadMedidadInventarioUMI":"UN","UnidadMedidaVenta":"UN","PuntoPrecio":"Good","PrecioUnitario":"61.71","Costo":"26.564","CantidadMasterpack":"1","SkuProveedor":"1941","EAN":"","TipoCodigoEAN":"Ean/Upc 13","DUN14":"","NumeroPiezas":"75","TipoMasterpack":"Caja","Perecible":"No","AlturaUnidadLogistica":"7.5","AnchoUnidadLogistica":"600","ProfundidadUnidadLogistica":"7.5","VolumenUnidadLogistica":"33750","PesoUnidadLogistica":"1","PesoProducto":"1","LongTail":"X"}]}', TIMESTAMP '2024-08-07 15:58:43', '0', null, '0', null, '11931997024573167');
COMMIT;

SELECT * FROM EDSR.PIM_MODELO M
--DELETE EDSR.PIM_MODELO
--UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '0', FEC_PROCESO = NULL
WHERE ID_MODELO = 991822;
COMMIT;
