SELECT * FROM EDSR.PIM_PRODUCTO;
SELECT * FROM EDSR.PIM_PRODUCTO_ATRIB;
SELECT * FROM EDSR.PIM_MODELO;

SELECT * FROM PIM_MODELO_REQUEST;

-- DROP TABLE EDSR.PIM_PRODUCTO_DATA_PMM;
CREATE TABLE EDSR.PIM_PRODUCTO_DATA_PMM (
	ID_PIM VARCHAR2(18) NOT NULL,
	PRD_LVL_CHILD NUMBER NULL,
	PRD_LVL_NUMBER VARCHAR2(50) NULL,
	PRD_NAME_FULL VARCHAR2(100) NULL,
	ESTADOPRODUCTO VARCHAR2(100) NULL,
	DUN14 VARCHAR2(100) NULL,
	RAZON_SOCIAL VARCHAR2(100) NULL,
	CODIGO_PROVEEDOR VARCHAR2(100) NULL,
	UMI VARCHAR2(100) NULL,
	EAN VARCHAR2(100) NULL,
	UMV VARCHAR2(100) NULL,
	SKU_PROVEEDOR VARCHAR2(100) NULL,
	TIPO_SURTIDO VARCHAR2(100) NULL,
	CONSTRAINT SYS_C001489164 CHECK ("ID_PIM" IS NOT NULL)
);