-- Consulta SKU
SELECT * FROM EDSR.PRDMSTEE WHERE PRD_LVL_NUMBER IN ('45358');

--Reenvio
SELECT * FROM EDSR.WMS_ITEM_ENVIO
--UPDATE EDSR.WMS_ITEM_ENVIO WMS SET FEC_PROCESADO = NULL
WHERE PRD_LVL_CHILD IN (133582) AND TRAN_TYPE = 'A';
COMMIT;

SELECT * FROM EDSR.WMS_ITEM_ENVIO WMS 
WHERE FLG_ERROR = '0' AND TEXT_RESQUEST LIKE '%CREATE%'
ORDER BY FEC_REG DESC FETCH FIRST 15 ROWS ONLY;

--Reenvio
SELECT WMS.PRD_LVL_CHILD,FEC_REG, TEXT_RESQUEST , FEC_PROCESADO, FLG_ERROR, MENSAJE,JSON_RESPONSE --, WMS.* 
FROM EDSR.WMS_ITEM_ENVIO WMS
--UPDATE EDSR.WMS_ITEM_ENVIO WMS SET FEC_PROCESADO = NULL, FLG_ERROR = '0', MENSAJE = NULL, JSON_RESPONSE = NULL
WHERE TRAN_TYPE = 'A' AND
	PRD_LVL_CHILD IN (SELECT PRD_LVL_CHILD FROM EDSR.PRDMSTEE WHERE PRD_LVL_NUMBER IN ('40411') ) 
		-- FLG_ERROR  = '1'
		-- FEC_PROCESADO IS NULL AND WMS.TEXT_RESQUEST IS NOT NULL AND WMS.FEC_REG >= TO_DATE('2025-01-01','YYYY-MM-DD') 
		 
;
COMMIT;