SELECT b.prd_lvl_child, b.trf_dist_pak
FROM EPMM.ORGMSTEE a
     INNER JOIN epmm.whsprdee b ON b.org_lvl_child = a.org_lvl_child
WHERE a.org_lvl_child = 420


SELECT * FROM EPMM.ORGMSTEE a WHERE a.org_lvl_child = 420;


 INSERT INTO EDSR.WMS_TIPO_INTEGRACION (ID_TIPO, TIPO_INTEGRACION, HORA_INICIO, HORA_FINAL) VALUES (16, 'PURCHASE ORDER - UPDATE', 0, 23);
    INSERT INTO EDSR.WMS_TIPO_INTEGRACION_ORG (ID_TIPO, ORG_LVL_CHILD) VALUES (16, 419);
    INSERT INTO EDSR.WMS_TIPO_INTEGRACION_ORG


    SELECT * FROM EDSR.WMS_TIPO_INTEGRACION ;
    SELECT * FROM EDSR.WMS_TIPO_INTEGRACION_ORG ;

