SELECT  *  FROM  EDSRCT2.PIV_TRX_BCT_HEAD HEAD WHERE HEADID = 72;
SELECT  *  FROM EDSRCT2.PIV_TRX_BCT_ITEM ITEM WHERE HEADID = 72;
SELECT  *  FROM EDSRCT2.PIV_TRX_BCT_DSCTO DSCTO WHERE HEADID = 72;

SELECT  ROUND(NVL(SUM(DSCTO.AMOUNT)/( (12/100) + 1 ),0.00),2)  FROM EDSRCT2.PIV_TRX_BCT_DSCTO DSCTO WHERE HEADID = 72;










-- factura
SELECT
		    COM.RAZON_SOCIAL as razonSocial,
		    COM.RUC AS ruc,

		    '01' codDoc,

		    REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,1) AS estab,
		    REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,2) AS ptoEmi,
		    REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,3) AS secuencial,
		    COM.DIRECCION_MATRIZ AS dirMatriz,

		    TO_CHAR(HEAD.TRXDATE,'DD/MM/YYYY') AS fechaEmision,
		    EST.VC_DIRECCION AS dirEstablecimiento,
		    'SI' AS obligadoContabilidad,
		    CASE
		        WHEN HEAD.CUSTOMERBUSINESSDOCNUMBER IS NULL THEN '05'
		        WHEN LENGTH(HEAD.CUSTOMERBUSINESSDOCNUMBER) = 0 THEN '05'
		        ELSE '04'
		    END AS tipoIdentificacionComprador,

		    CASE
		        WHEN HEAD.CUSTOMERBUSINESSDOCNUMBER IS NULL THEN HEAD.CUSTOMERNAME || ' ' || HEAD.CUSTOMERSURNAME
		        WHEN LENGTH(HEAD.CUSTOMERBUSINESSDOCNUMBER) = 0 THEN  HEAD.CUSTOMERNAME || ' ' || HEAD.CUSTOMERSURNAME
		        ELSE HEAD.CUSTOMERBUSINESSNAME
		    END AS razonSocialComprador,

		    CASE
		        WHEN HEAD.CUSTOMERBUSINESSDOCNUMBER IS NULL THEN HEAD.CUSTOMERDOCUMENTNUMBER
		        WHEN LENGTH(HEAD.CUSTOMERBUSINESSDOCNUMBER) = 0 THEN HEAD.CUSTOMERDOCUMENTNUMBER
		        ELSE HEAD.CUSTOMERBUSINESSDOCNUMBER
		    END AS identificacionComprador,
		    nvl(pic.direccion, 'Guayaquil') AS direccionComprador,
		    HEAD.AFFECTEDTOTALAMOUNT AS totalSinImpuestos,

		    (SELECT ROUND(NVL(SUM(AMOUNT)/( (HEAD.IGVPERCENTAGE/100) + 1 ),0.00),2) FROM EDSRCT2.PIV_TRX_BCT_DSCTO WHERE HEADID = HEAD.HEADID ) AS totalDescuento,

		    2 AS codigo,
		    2 AS codigoPorcentaje,
		    HEAD.AFFECTEDTOTALAMOUNT AS baseImponible,
		    HEAD.IGVPERCENTAGE AS tarifa,
		    HEAD.IGVTOTALAMOUNT AS valor,

		    '0.00' AS propina,
		    HEAD.AMOUNT AS importeTotal,
		    'DOLAR' AS moneda,

		    MEDIOPAGO.COD_SRI AS formaPago,
		    HEAD.AMOUNT AS total,
		    PAYMENT.CUOTAS*30 AS plazo,
		    'dias' AS unidadTiempo,

		    HEAD.CUSTOMEREMAIL AS email,
		    HEAD.CUSTOMERPHONE AS telefono

		FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
		INNER JOIN EDSR.PIVOT_COMPANY COM ON HEAD.COMPANY = COM.COD_COMPANY
		INNER JOIN EDSR.PIVOT_ESTABLECIMIENTO EST ON (HEAD.BRANCHID = EST.BRANCHID AND COM.COD_COMPANY = EST.COD_COMPANY)
		LEFT JOIN EDSRCT2.PIV_TRX_BCT_DSCTO  DSCTO  ON HEAD.HEADID = DSCTO.HEADID
		LEFT JOIN EDSRCT2.PIV_TRX_BCT_PAYMENT PAYMENT ON PAYMENT.HEADID = HEAD.HEADID
		LEFT JOIN EDSR.HP_VTEX_MEDIO_PAGO MEDIOPAGO ON MEDIOPAGO.IDVTEX = PAYMENT.PAYMENTMETHODCODE
    left join edsr.hp_vtex_picking pic on pic.id_picking = head.originid and head.origintrx = 1
		WHERE
		    COM.COD_COMPANY = 'HE'
		   -- AND PAYMENT.PAYMENTMETHODCODE IN (1,401,2,3,4,5)
		    AND HEAD.HEADID = 72;

-- detalle
SELECT
		ITEM.SKU AS codigoPrincipal,
	    ITEM.PRODUCTNAME AS descripcion,
	    TO_NUMBER(ITEM.QUANTITY,'9999.99') AS cantidad,
	    ROUND(NVL(ITEM.PRICE/( (HEAD.IGVPERCENTAGE/100) + 1 ),0.00),2) AS precioUnitario,
	    ROUND(NVL(DSCTO.AMOUNT/( (HEAD.IGVPERCENTAGE/100) + 1 ),0.00),2) AS descuento,
	    ROUND(NVL( ITEM.QUANTITY*(ITEM.PRICE/( (HEAD.IGVPERCENTAGE/100) + 1 )) - ROUND(NVL(DSCTO.AMOUNT/( (HEAD.IGVPERCENTAGE/100) + 1 ),0.00),2), 0.00) ,2) AS precioTotalSinImpuesto,

	    2 AS codigo,
	    2 AS codigoPorcentaje,
	    TO_CHAR(HEAD.IGVPERCENTAGE,'999.99') AS tarifa,
	    ROUND(NVL( ITEM.QUANTITY*(ITEM.PRICE/( (HEAD.IGVPERCENTAGE/100) + 1 )) - ROUND(NVL(DSCTO.AMOUNT/( (HEAD.IGVPERCENTAGE/100) + 1 ),0.00),2), 0.00) ,2) AS baseImponible,
	    ITEM.TAXAMOUNT AS valor

	FROM EDSRCT2.PIV_TRX_BCT_ITEM ITEM
	INNER JOIN  EDSRCT2.PIV_TRX_BCT_HEAD HEAD ON HEAD.HEADID = ITEM.HEADID
	INNER JOIN EDSR.PIVOT_COMPANY COM ON HEAD.COMPANY = COM.COD_COMPANY
	INNER JOIN EDSR.PIVOT_ESTABLECIMIENTO EST ON (HEAD. BRANCHID = EST.BRANCHID AND COM.COD_COMPANY = EST.COD_COMPANY)
	LEFT JOIN EDSRCT2.PIV_TRX_BCT_DSCTO  DSCTO  ON (HEAD.HEADID = DSCTO.HEADID AND ITEM.SEQUENCE = DSCTO.ITEMSEQUENCE)
	WHERE
	    COM.COD_COMPANY = 'HE'
	    AND HEAD.HEADID = 72;