DECLARE
    TYPE t_cursor IS REF CURSOR;

    P_CURSOR t_cursor;
BEGIN
EDSR.TP_PKG_INTERFAZ_PMM2SAPFICO.SP_GEN_INTERFAZ_SAP_RSL(
        P_PERIODO => '202311',
        P_USUARIO => 'HP70436936',
        P_EMPRESA => '30',
        P_MESSAGE => 'L30001',
        P_CUR_RESULT => P_CURSOR);
END;


BEGIN
    EDSR.TP_PKG_INTERFAZ_PMM2SAPFICO.SP_DEL_INTERFAZ_SAP_RSL(P_PERIODO => '202311');
END;

--648
--756
--972
select COUNT(1) from ISR_REP_RSL;
select * from ISR_REP_RSL order by SESSION_NUMBER ASC;

select COUNT(1) from edsr.ISR_F550911;
select * from edsr.ISR_F550911 ;
select PERIODO from edsr.ISR_F550911;

/*
SELECT VALOR FROM ISP_VALORES_SAP WHERE CODIGO='CPCO';
DELETE ISR_F550911
WHERE PERIODO='202311'
    AND ESTADO_ENVIO='P'
    AND POCO='A501';
*/