SELECT * FROM ECT.CTX_HEADER_TRX CHT WHERE HED_FPROCESO >= TO_DATE('20240528', 'YYYYmmDD');
SELECT CHT.HED_FPROCESO,CHT.* FROM ECT.CTX_HEADER_TRX CHT ORDER BY CHT.HED_FPROCESO DESC ;



SELECT TO_CHAR(TVA.FEC_CRE,'YYYYmmDD'), TVA.DOWNLOAD_B2B, TVA.DOWNLOAD_B2B_2 , TVA.*
FROM EDSR.TPVTAHIS TVA
ORDER BY TVA.FEC_CRE DESC; -- TO_CHAR(FEC_VENTA,'YYYYmmDD') = TO_CHAR(SYSDATE - 1 ,'YYYYmmDD');