EDSR.PKG_VTEX_INTEGRACION_STOCK.SP_PROC_STOCK_PRINCIPAL


SELECT ORG_LVL_NUMBER,
             PRD_LVL_NUMBER,
             CANTIDAD
      FROM edsr.VTEX_STOCK_DIFF;


INSERT INTO EDSR.VTEX_STOCK_DIFF(ORG_LVL_NUMBER, PRD_LVL_NUMBER, CANTIDAD) VALUES ('101','11826',0);
COMMIT;

-- STOCK ANTERIOR
SELECT ORG_LVL_NUMBER, PRD_LVL_NUMBER, CANTIDAD
FROM VTEX_STOCK_ACTUAL ACT
WHERE EXISTS(
           SELECT 1
           FROM VTEX_STOCK_DIFF DIF
           WHERE DIF.ORG_LVL_NUMBER = ACT.ORG_LVL_NUMBER
             AND DIF.PRD_LVL_NUMBER = ACT.PRD_LVL_NUMBER
             AND FLG_ENVIO_VTEX = '1'
          )
    OR
    NOT EXISTS(
               SELECT 1
               FROM VTEX_STOCK_DIFF DIF
               WHERE DIF.ORG_LVL_NUMBER = ACT.ORG_LVL_NUMBER
                 AND DIF.PRD_LVL_NUMBER = ACT.PRD_LVL_NUMBER
              );

-- STOCK ACTUAL
SELECT O.ORG_LVL_NUMBER,
             VP.PRD_LVL_NUMBER,
             NVL(STK.CANTIDAD, 0) AS CANTIDAD
FROM VTEX_SKU_TMP VP
    INNER JOIN HP_SUC_VTEX S ON S.ESTADO = 1
    INNER JOIN ORGMSTEE O ON S.ORG_LVL_CHILD = O.ORG_LVL_CHILD
    LEFT JOIN (
               SELECT X.ORG_LVL_CHILD,
                      X.PRD_LVL_CHILD,
                      SUM(X.CANTIDAD) CANTIDAD
               FROM (
                     SELECT ORG_LVL_CHILD, PRD_LVL_CHILD, CANTIDAD
                     FROM VTEX_STOCK_TMP
                     UNION ALL
                     SELECT ORG_LVL_CHILD, PRD_LVL_CHILD, CANTIDAD * -1
                     FROM VTEX_STOCK_VTA_TMP
                    ) X
               GROUP BY X.ORG_LVL_CHILD, X.PRD_LVL_CHILD
              ) STK ON STK.ORG_LVL_CHILD = O.ORG_LVL_CHILD AND STK.PRD_LVL_CHILD = VP.PRD_LVL_CHILD;

 SELECT P.PRD_LVL_CHILD,
             P.PRD_LVL_NUMBER,
             P.COD_BIGTCK,
             NVL(P.FLAG_ECOM_RETIRO_TDA, 'NO'),
             NVL(P.FLAG_ECOM_VTA_PRV, 'NO')
       FROM TPPRDMST P
         INNER JOIN HP_VTEX_PRODUCTO VP ON VP.PRD_LVL_CHILD = P.PRD_LVL_CHILD;

SELECT
    NVL(ACT.ORG_LVL_NUMBER, ANT.ORG_LVL_NUMBER) AS ORG_LVL_NUMBER,
    NVL(ACT.PRD_LVL_NUMBER, ANT.PRD_LVL_NUMBER) AS PRD_LVL_NUMBER,
    CASE WHEN NVL(ACT.CANTIDAD,0) <= 0 THEN 0 ELSE ACT.CANTIDAD END AS CANTIDAD
    FROM VTEX_STOCK_ACTUAL ACT
        FULL OUTER JOIN VTEX_STOCK_ANTERIOR ANT
        ON ACT.ORG_LVL_NUMBER = ANT.ORG_LVL_NUMBER AND ACT.PRD_LVL_NUMBER = ANT.PRD_LVL_NUMBER
    WHERE
        --ACT.CANTIDAD IS NULL
        --OR ANT.CANTIDAD IS NULL
        --OR
        (NVL(ACT.CANTIDAD,0) <> NVL(ANT.CANTIDAD,0));

SELECT * FROM VTEX_STOCK_ACTUAL WHERE CANTIDAD IS NULL;
SELECT * FROM VTEX_STOCK_ANTERIOR WHERE CANTIDAD IS NULL;

