-- REENVIO DE INTERFACE DE CREACION DE PRODUCTO (ITEM)
SELECT * FROM EDSR.PRDMSTEE WHERE PRD_LVL_NUMBER = '38561';
SELECT * FROM EDSR.WMS_ITEM_ENVIO WMS
-- UPDATE EDSR.WMS_ITEM_ENVIO WMS SET FEC_PROCESADO = NULL
WHERE WMS.PRD_LVL_CHILD = '127005' AND TRAN_TYPE = 'A';

SELECT * FROM EDSR.WMS_ITEM_ENVIO WMS WHERE prd_lvl_child = 127017;

SELECT * FROM EDSR.WMS_ITEM_ENVIO WMS ORDER BY FEC_REG DESC FETCH FIRST 10 ROWS ONLY;
SELECT PRD_LVL_CHILD, MENSAJE,FEC_REG
FROM EDSR.WMS_ITEM_ENVIO WMS
         WHERE FEC_REG < TO_DATE('2024-11-09','YYYY-MM-DD') AND FEC_REG >= TO_DATE('2024-11-08','YYYY-MM-DD')
               AND MENSAJE = 'Producto sin EAN principal'
ORDER BY FEC_REG DESC
--FETCH FIRST 20 ROWS ONLY
;

SELECT * FROM ALL_SOURCE WHERE UPPER(TEXT) LIKE  '%WMS_ITEM_ENVIO%';
SELECT * FROM ALL_SOURCE WHERE UPPER(TEXT) LIKE  '%SP_CARGA_ITEM%';

-- EAN
select *
from prdupcee
where prd_lvl_child = '126401'
  and prd_primary_flag = 'T';