SELECT * FROM WMS_MODELO_REQUEST
--UPDATE EDSR.WMS_MODELO_REQUEST SET FLAG_PROCESADO = '0', FLAG_ERROR = '0', FEC_PROCESO= NULL
WHERE 
	WMS_MODELO_REQUEST.IDENTIFICADOR IN ('OS85100029261') --AND ID_TIPO = 2
	--ID_MODELO = 250755;
ORDER BY IDENTIFICADOR, FEC_REG
;
COMMIT;

SELECT * FROM WMS_MODELO_REQUEST WHERE ID_MODELO = 250755; --ORA-01013: user requested cancel of current operation
SELECT * FROM WMS_MODELO_REQUEST WHERE modelo LIKE '%OS85100031706%';

--Estados de Transferencia
SELECT * FROM EPMM.TRFSTSCD t ;

SELECT * FROM PRDMSTEE WHERE PRD_LVL_NUMBER = '34731';

--Estado de la transferencia
 select d.trf_status, d.*
  from trfdtlee d
  where d.trf_number    = 388783
    and d.prd_lvl_child = 123437
    and d.trf_qty_req   != 0;

SELECT * FROM WMS_MODELO_REQUEST
--UPDATE EDSR.WMS_MODELO_REQUEST SET FLAG_PROCESADO = '0', FLAG_ERROR = '0', FEC_PROCESO= NULL
WHERE WMS_MODELO_REQUEST.id_modelo = 156628;
COMMIT;

SELECT DISTINCT id_tipo FROM WMS_MODELO_REQUEST WHERE IDENTIFICADOR LIKE 'NAC%';
SELECT * FROM WMS_MODELO_REQUEST
WHERE id_tipo= 1 AND MODELO LIKE '%TRF00000388783%'
ORDER BY FEC_REG
FETCH FIRST 50 ROWS ONLY
;

--Buscar carton duplicado
SELECT H.LOAD_MANIFEST_NBR , H.DOWNLOAD_DATE_1, D.HDR_GROUP_NBR,ORDER_NBR,D.ITEM_ALTERNATE_CODE,D.ERR_CODE,OB_LPN_NBR,PALLET_NBR, D.* 
FROM EDSR.WMS_SHP_LOAD_DTL D
	INNER JOIN  WMS_SHP_LOAD_HDR H ON H.HDR_GROUP_NBR = D.HDR_GROUP_NBR
WHERE D.OB_LPN_NBR IN ('BEC85100658563','BEC85100658562')
ORDER BY LINE_NBR;

--**********************************************************************
--**********************************************************************
--SOLUCIÓN: Actualizar directamente los cartones repetidos, luego hacer el reimpulso.
--**********************************************************************
--**********************************************************************
--OS85100022401,OS85100022521,OS85100022381,OS85100022503
--DETECTAR ERROR:
SELECT  DOWNLOAD_DATE_1,DATE_CREATED,MNFST_NUMBER,ERROR_CODE,TRF_NUMBER,CARTON_NUMBER,PRD_LVL_NUMBER, SDI.* 
FROM epmm.SDITRFDTI SDI
WHERE MNFST_NUMBER = 'OS85100029261' AND SDI.ERROR_CODE  = 204
ORDER BY session_number DESC;

--Cabecera
SELECT DOWNLOAD_DATE_1, ERR_CODE,LOAD_MANIFEST_NBR,H.*
FROM EDSR.WMS_SHP_LOAD_HDR H 
WHERE LOAD_MANIFEST_NBR IN ('OS85100029261')
ORDER BY CREATE_DATE DESC
;

--Detalle => ACTUALIZAR CARTON
SELECT HDR_GROUP_NBR,OB_LPN_NBR,ORDER_NBR,D.ITEM_ALTERNATE_CODE,D.ERR_CODE,OB_LPN_NBR,PALLET_NBR, D.* 
FROM WMS_SHP_LOAD_DTL D
--UPDATE EDSR.WMS_SHP_LOAD_DTL SET OB_LPN_NBR = 'BEC85100524446' 
WHERE HDR_GROUP_NBR = 2781 --AND OB_LPN_NBR IN ('BEC85100635342','BEC85100635351') 
;
COMMIT;

--REIMPULSO: Al KSH: /prochp/interfaces/wms/import/ksh/wms_shipped_loads.ksh
SELECT DOWNLOAD_DATE_1, ERR_CODE,H.* FROM WMS_SHP_LOAD_HDR H 
--UPDATE EDSR.WMS_SHP_LOAD_HDR SET DOWNLOAD_DATE_1 = NULL, ERR_CODE = null
WHERE HDR_GROUP_NBR IN (2787);
COMMIT;

SELECT CREATE_DATE,DOWNLOAD_DATE_1, LOAD_MANIFEST_NBR,SHP.* 
FROM WMS_SHP_LOAD_HDR SHP
WHERE CREATE_DATE >= TRUNC(TO_DATE('30-09-2025','DD-MM-YYYY'))
ORDER BY HDR_GROUP_NBR;
--Cabecera
SELECT DOWNLOAD_DATE_1, ERR_CODE,H.*
FROM EDSR.WMS_SHP_LOAD_HDR H 
WHERE LOAD_MANIFEST_NBR IN ('OS85100031706');

--detalle (CARTON_NUMBER = OB_LPN_NBR)
SELECT HDR_GROUP_NBR,ORDER_NBR,D.ITEM_ALTERNATE_CODE,D.ERR_CODE,OB_LPN_NBR,PALLET_NBR, D.* 
FROM EDSR.WMS_SHP_LOAD_DTL D
WHERE HDR_GROUP_NBR IN (3158)
ORDER BY LINE_NBR;

--BUSCAR ERROR CODIGO 204(CARTON REPETIDO) POR CARGA y codigo ERROR
SELECT DOWNLOAD_DATE_1,DATE_CREATED,MNFST_NUMBER,ERROR_CODE,TRF_NUMBER,CARTON_NUMBER,PRD_LVL_NUMBER, SDI.* 
FROM epmm.SDITRFDTI SDI
ORDER BY SDI.DATE_CREATED DESC
FETCH FIRST 50 ROWS ONLY;

SELECT  DOWNLOAD_DATE_1,DATE_CREATED,MNFST_NUMBER,ERROR_CODE,TRF_NUMBER,CARTON_NUMBER,PRD_LVL_NUMBER, SDI.* 
FROM epmm.SDITRFDTI SDI
WHERE MNFST_NUMBER = 'OS85100031862' AND SDI.ERROR_CODE  = 204
ORDER BY session_number DESC;

SELECT MNFST_NUMBER,ERROR_CODE,TRF_NUMBER,CARTON_NUMBER,PRD_LVL_NUMBER, SDI.* 
FROM epmm.SDITRFDTI SDI
WHERE MNFST_NUMBER 	IN ('OS85100031706','OS85100031861','OS85100031604','OS85100031862','OS85100031408','OS85100032061','OS85100031561') AND SDI.ERROR_CODE  = 204
ORDER BY session_number DESC;

--SABER CUANTOS CODIGOS ESTAN:
SELECT DISTINCT ERROR_CODE
FROM epmm.SDITRFDTI SDI
WHERE MNFST_NUMBER = 'OS85100018501'
;
/*
 * CASO: 2025-06-30
 * OS85100017781 => 67 cartones repetidos
 * OS85100017781 => 24 cartones repetidos
 */

SELECT * FROM WMS_MODELO_REQUEST  
WHERE ID_TIPO = 1 AND FLAG_ERROR = 1 AND DESC_ERROR = 'ORA-01013: user requested cancel of current operation';

--ORA-01013: user requested cancel of current operation
SELECT * FROM WMS_MODELO_REQUEST  
WHERE WMS_MODELO_REQUEST.MODELO LIKE '%NAC000928739%' --AND ID_TIPO = 1
	AND FEC_REG >= TRUNC(TO_DATE('01-10-2025','DD-MM-YYYY'))
;

SELECT * FROM WMS_MODELO_REQUEST  
WHERE WMS_MODELO_REQUEST.ID_MODELO IN (155248,154628)
ORDER BY IDENTIFICADOR, FEC_REG
;


SELECT * FROM edsr.WMS_ACTIVITY_CODE wac;
--Lista de Errores
SELECT * FROM edsr.WMS_ERROR_INT ;
--TRANSFERENCIAS - ESTADO
SELECT TRF_STATUS, TRF.* FROM epmm.TRFHDREE TRF WHERE TRF_NUMBER IN (11058);
SELECT * FROM EPMM.TRFSTSCD t ;




--OS85100017781
--Cabecera
SELECT DOWNLOAD_DATE_1, ERR_CODE,H.* 
FROM WMS_SHP_LOAD_HDR H 
WHERE LOAD_MANIFEST_NBR IN ('OS85100025585');

--detalle (CARTON_NUMBER = OB_LPN_NBR)
SELECT HDR_GROUP_NBR,ORDER_NBR,D.ITEM_ALTERNATE_CODE,D.ERR_CODE,OB_LPN_NBR,PALLET_NBR, D.* 
FROM WMS_SHP_LOAD_DTL D
WHERE HDR_GROUP_NBR IN (2351) AND OB_LPN_NBR = 'BEC85100588892'
ORDER BY LINE_NBR;

SELECT * FROM WMS_SHP_LOAD_DTL WHERE OB_LPN_NBR = 'BEC85100587683';
SELECT * FROM EDSR.WMS_SHP_LOAD_HDR where HDR_GROUP_NBR = 2336;

SELECT HDR_GROUP_NBR,ORDER_NBR,D.ITEM_ALTERNATE_CODE,D.ERR_CODE,OB_LPN_NBR,PALLET_NBR, D.* 
FROM edsr.WMS_SHP_LOAD_DTL D
--UPDATE EDSR.WMS_SHP_LOAD_DTL SET OB_LPN_NBR = 'BEC85100526451'
WHERE HDR_GROUP_NBR = 2051 AND OB_LPN_NBR = 'BEC85100526451';
COMMIT;





SELECT HDR_GROUP_NBR,ORDER_NBR,D.ITEM_ALTERNATE_CODE,D.ERR_CODE,OB_LPN_NBR,PALLET_NBR, D.* FROM WMS_SHP_LOAD_DTL D
--UPDATE EDSR.WMS_SHP_LOAD_HDR SET DOWNLOAD_DATE_1 = NULL, ERR_CODE = null
WHERE HDR_GROUP_NBR IN (2033);
COMMIT;

