SELECT * FROM EDSR.WMS_MODELO_REQUEST WHERE ID_TIPO = 1 ORDER BY ID_MODELO DESC FETCH FIRST 5 ROWS ONLY	;
SELECT FLAG_PROCESADO,FEC_PROCESO, MODELO.* FROM EDSR.WMS_MODELO_REQUEST MODELO WHERE ID_MODELO IN(126879,126878) ;

UPDATE EDSR.WMS_MODELO_REQUEST
SET FEC_PROCESO = NULL, FLAG_PROCESADO = 0
WHERE ID_MODELO = 126878;
COMMIT;
