SELECT * FROM EDSR.METDPTSUC 
WHERE GOAL_DATE >= to_date('2025-03-11','YYYY-MM-DD') AND GOAL_DATE < to_date('2025-03-12','YYYY-MM-DD');


SELECT DISTINCT CHANNEL FROM EDSR.METDPTSUC ORDER BY CHANNEL;
SELECT DISTINCT DIVISION_CODE FROM EDSR.METDPTSUC ORDER BY DIVISION_CODE;
SELECT DISTINCT AREA_CODE FROM EDSR.METDPTSUC ORDER BY AREA_CODE;

--SalesByDivision
SELECT * FROM EDSR.METDPTSUC WHERE GOAL_DATE >= :initial_date AND GOAL_DATE < :end_date AND AREA_CODE IN (:area_code_0,:area_code_1)