SELECT
 V.AUDIT_NUMBER Auditoria,
 V.TRANS_SESSION Sesión,
 TRUNC(V.POSTED_DATE_TIME) Proceso,
 V.TRANS_DATE Transaccion,
 --P.DES_AREA "Area",
 --P.DES_LIN "Línea",
 O.ORG_LVL_NUMBER Sucursal,
 TRANS_REF NUmeroReferencia,
 --TRANS_REF2 "Número Referencia 2",
 V.INV_MRPT_CODE MaestroReporte,
 V.INV_DRPT_CODE DetalleReporte,
 D.INV_DRPT_DESC Movimiento,
 V.INV_EFF_QTY EfectoInventario,
 V.INV_EFF_CST EfectoCosto,
 P.PRD_LVL_NUMBER SKU,
 P.PRD_FULL_NAME Descripcion,
 V.INNER_PACK_ID InnerPack,
 V.TRANS_QTY Cantidad,
 V.TRANS_COST Costo,
 V.TRANS_RETL Precio,
 V.TRANS_EXT_COST CostoExt,
 V.TRANS_EXT_RETL PrecioExt,
 H.TRANS_USER Usuario
  FROM EDSR.INVAUDEE V
 INNER JOIN EDSR.ORGMSTEE O
    ON V.TRANS_ORG_CHILD = O.ORG_LVL_CHILD
 INNER JOIN EDSR.TPPRDMST P
    ON V.TRANS_PRD_CHILD = P.PRD_LVL_CHILD
 INNER JOIN EDSR.INVAHREE H
    ON V.TRANS_SESSION = H.TRANS_SESSION
 INNER JOIN EDSR.INVTRDEE D
    ON V.INV_MRPT_CODE = D.INV_MRPT_CODE
   AND V.INV_DRPT_CODE = D.INV_DRPT_CODE
 WHERE
   /*  TO_CHAR(V.POSTED_DATE_TIME, 'YYYYMMDD') >= '20240101'
   AND TO_CHAR(V.POSTED_DATE_TIME, 'YYYYMMDD') <= '20250125' AND
*/
--TRF00000071972 sano
--TRF00000058252 dañado
 --TRF00000120818	10170
 --118959		10506
   -- TRANS_REF IN ('58252')
    TRANS_REF IN ('120818') and  P.PRD_LVL_NUMBER = '10170'
    -- TRANS_REF IN ('77663')
 ORDER BY TRANS_REF, PROCESO;
;