-- TABLA LOG ORDEN DE COMPRA
SELECT * FROM EDSR.SDIHDIREJ;

SELECT * FROM EDSR.SDIPMGHDI;

SELECT * FROM EDSR.ORGMSTEE;

SELECT * FROM  EDSR.RPLPMHEE
ORDER BY RPL_BEGDATE DESC;

SELECT * FROM  EDSR.RPLPMHEE
where PRD_LVL_NUMBER = '21200';

SELECT * FROM  EDSR.RPLPMHEE
where PRD_LVL_NUMBER = '22040';

SELECT * FROM  EDSR.RPLPMHEE
where PRD_LVL_NUMBER = '22603';

SELECT * FROM  EDSR.PMGHDREE
where PMG_TYPE_CODE IN (98);

--ORDENES DE COMPRA (AUTOMATICA O MANUAL)
SELECT * FROM  EDSR.PMGOTPEE;

/*
Carga menos de 1000 productos mediante SCR
*/


SELECT COUNT(1) FROM EDSR.TPCARPAR;
SELECT COUNT(1) FROM EDSR.TPCARSEM;


DROP TABLE  EDSR.TEMP_TPCARSEM;
DROP TABLE  EDSR.TEMP_PARAMREPOSEM;