/*
    1. Cloud Function:
        https://us-west1-prd-promartec-sistemas-wms.cloudfunctions.net/he-wms-outbound-load
    2. Pub/Sub
    3. RANCHER DEMON: he-ti-demon-pubsub-wms-suscriptor (Siempre)
        (EDSR.PKG_WMS_GENERAL.SP_INS_WMS_MODELO_REQUEST)
        INSERT INTO WMS_MODELO_REQUEST (P_ID_MODELO,P_ID_TIPO,P_MODELO,P_MESSAGE_ID)
            1: outbound-load
            2: verificacion_asn (ASN)
            3: inventory_history
            4: order_crossdock

    4. RANCHER DEMON: he-demon-wms-registrar-output (Cada 5 min)
        4.1. Selecciona todos los pendientes, sin importar el tipo
        (EDSR.PKG_WMS_GENERAL.sp_sel_modelo_request_pendiente)
        SELECT * FROM WMS_MODELO_REQUEST (flag_procesado = '0')


        4.2. Para este caso, selecciona el tipo 2 (Verificacion ASN), y registra todo el modelo del WMS en columnas divididas por |
        (EDSR.PKG_WMS_GENERAL.SP_INS_SHP_LOAD_HDR)
        INSERT INTO WMS_RCV_ASN_HDR

    RECORDAR:
        ASN NACIONALES comienzan con NAC....
        ASN IMPORTADAS comienzan con OS.....

 */
/*
 RECORDAR: Todo movimiento genera un INVENTORY para mover el inventario
 CASO: Traslado de mercaderia de la 851 a 101
 El Outbound que es el DESPACHO o SALIDA de la mercadería genera un INVENTORY HISTORY (851)
 El ASN Entrada es la RECEPCION o LLEGADA de la mercaderia genera un INVENTORY HISTORY (101)
 */

SELECT * FROM WMS_MODELO_REQUEST ORDER BY FEC_REG FETCH FIRST 50 ROWS ONLY ;
SELECT * FROM WMS_MODELO_REQUEST WHERE ID_TIPO = 2 AND MODELO NOT LIKE '[H1]NAC%' ORDER BY FEC_REG DESC FETCH FIRST 50 ROWS ONLY ;
SELECT * FROM WMS_MODELO_REQUEST WHERE ID_TIPO = 2 AND MODELO LIKE '[H1]OS%' ORDER BY FEC_REG DESC FETCH FIRST 50 ROWS ONLY ;
SELECT * FROM WMS_MODELO_REQUEST WHERE ID_TIPO = 2 AND MODELO LIKE '%OS85100012261%' ORDER BY FEC_REG DESC FETCH FIRST 50 ROWS ONLY ;
SELECT * FROM WMS_MODELO_REQUEST WHERE ID_TIPO = 2 AND MODELO LIKE '%NAC000914640%' ORDER BY FEC_REG DESC FETCH FIRST 50 ROWS ONLY ;

SELECT * FROM WMS_ERROR_INT;
SELECT * FROM PMGSTSCD;

SELECT * FROM WMS_RCV_ASN_HDR ORDER BY CREATE_DATE DESC FETCH FIRST 50 ROWS ONLY;

SELECT HDR.* FROM WMS_RCV_ASN_HDR HDR WHERE SHIPMENT_NBR = 'NAC000914640';
SELECT DISTINCT DTL.PO_NBR, DTL.* FROM WMS_RCV_ASN_DTL DTL WHERE DTL.HDR_GROUP_NBR = 10038;

--DETALLE ASN
SELECT DTL.PO_NBR, DTL.*
FROM WMS_RCV_ASN_DTL DTL
WHERE DTL.HDR_GROUP_NBR = 10038
;

-- OC
SELECT * FROM PMGHDREE WHERE PMG_PO_NUMBER IN (120382,120138,120139);
/*
 CASO PRD
 OS85100012261
 */
SELECT CREATE_DATE, ERR_CODE, HDR.* FROM WMS_RCV_ASN_HDR HDR WHERE SHIPMENT_NBR = 'OS85100012261';


SELECT CREATE_DATE, ERR_CODE, HDR.* FROM WMS_RCV_ASN_HDR HDR WHERE ERR_CODE  > 0 ORDER BY hdr.CREATE_DATE DESC;
SELECT ERR_CODE, DTL.* FROM WMS_RCV_ASN_DTL DTL WHERE HDR_GROUP_NBR = 9397;

SELECT CREATE_DATE, ERR_CODE, HDR.* FROM WMS_RCV_ASN_HDR HDR WHERE SHIPMENT_NBR = 'OS85100012823';
SELECT ERR_CODE, DTL.* FROM WMS_RCV_ASN_DTL DTL WHERE HDR_GROUP_NBR = 9897;

SELECT CREATE_DATE, ERR_CODE, HDR.* FROM WMS_RCV_ASN_HDR HDR WHERE SHIPMENT_NBR = 'OS85100012541';
SELECT ERR_CODE, DTL.* FROM WMS_RCV_ASN_DTL DTL WHERE HDR_GROUP_NBR = 9692;