/*
 vpcprdee --> case pack

vpccstee --> costo por case pack
COSTO PROMEDIO: CSTMSTEE
 */
SELECT * FROM PRDMSTEE WHERE PRD_LVL_NUMBER = '39306';
SELECT * FROM VPCPRDEE WHERE PRD_LVL_CHILD = 127705;
SELECT * FROM VPCCSTEE WHERE VPC_PRD_TECH_KEY = 142463 ;

SELECT * FROM CSTMSTEE ORDER BY CST_KEY DESC FETCH FIRST 20 ROWS ONLY;
SELECT * FROM CSTMSTEE ORDER BY CST_FROM_DATE DESC FETCH FIRST 20 ROWS ONLY;
SELECT * FROM CSTMSTEE FETCH FIRST 20 ROWS ONLY;
SELECT * FROM CSTMSTEE WHERE PRD_LVL_CHILD = 127705 ;

