-- ifh_sp_sur_close_all
SELECT *
FROM ALL_OBJECTS
WHERE OBJECT_TYPE IN ('PROCEDURE') AND OBJECT_NAME LIKE 'IFH_SP_SUR_CLOSE%';

-- Ver contenido
SELECT text
FROM all_source
WHERE name = 'IFH_SP_SUR_CLOSE_ALL'
AND type = 'PROCEDURE'
ORDER BY line;

/*
 PRODUCTOS LONG TAIL
 HESA_40051
 HESA_40050
 */
 SELECT * FROM PIM_MODELO WHERE ID_TIPO = 4 ORDER BY FEC_PROCESO DESC ;
 SELECT * FROM PIM_PRODUCTO WHERE PRD_LVL_NUMBER IN ('36160');
 SELECT * FROM PIM_PRODUCTO WHERE ID_PIM IN ('HESA_40051','HESA_40050','HESA_40006','HESA_40045');

 SELECT * FROM PIM_MODELO WHERE CONTENIDO LIKE '%HESA_40051%';
 SELECT * FROM PIM_MODELO WHERE CONTENIDO LIKE '%HESA_40050%';

SELECT * FROM PIM_ATRIBUTO;
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM IN 'HESA_40050' ; --36160 --L
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM IN 'HESA_40051' ; --36161 --L
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM IN 'HESA_40006' ; --36100 --LT
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM IN 'HESA_40045' ; --36121 --H

--- *************************************************
-- INICIO VALIDACION DE CREACION DE PRODUCTO LONG_TAIL
--- *************************************************
-- SKU
SELECT * FROM EDSR.PRDMSTEE WHERE PRD_LVL_NUMBER IN ('36291');

-- Luego de crear, hay un trigger que llena aqui, esperar unos segundos
select prd.atr_long_tail, prd.* FROM TPPRDMST prd WHERE PRD_LVL_NUMBER IN ('36291');

-- Estado
select e.PRD_LVL_CHILD, e.prd_status, des.PRD_STATUS_DESC, e.*
     -- , row_number() over(partition by PRD_LVL_CHILD order by EFFECT_DATE desc) rn
from PRDSTEEE e
    INNER JOIN EDSR.PRDSTSEE des on des.PRD_STATUS = e.PRD_STATUS
WHERE PRD_LVL_CHILD IN ('124760');

SELECT VPC_PRD_STATUS, vpc_prd_tech_key FROM EDSR.VPCPRDEE WHERE PRD_LVL_CHILD IN ('124760'); -- Extraer (vpc_prd_tech_key) SET =6
SELECT vpc_prd_status FROM edsr.VPCSTEEE WHERE vpc_prd_tech_key=134499; -- (vpc_prd_tech_key) SET =6
--- *************************************************
-- FIN VALIDACION DE CREACION DE PRODUCTO LONG_TAIL
--- *************************************************

 SELECT '28907',ROWNUM, '36160',0,ATR_TYP_TECH_KEY,ATR_HDR_TECH_KEY,ID,'A',1 FROM PIM_PRODUCTO_ATRIB WHERE  ATR_TYP_TECH_KEY IS NOT NULL AND ID_PIM IN 'HESA_40050';
 SELECT '28907',ROWNUM, '36160',0,ATR_TYP_TECH_KEY,ATR_HDR_TECH_KEY,ID,'A',1 FROM PIM_PRODUCTO_ATRIB WHERE  ATR_TYP_TECH_KEY IS NOT NULL AND ID_PIM = 'HESA_40051';
 SELECT '28907',ROWNUM, '36160',0,ATR_TYP_TECH_KEY,ATR_HDR_TECH_KEY,ID,'A',1 FROM PIM_PRODUCTO_ATRIB WHERE  ATR_TYP_TECH_KEY IS NOT NULL AND ID_PIM = 'HESA_40011'; --H
SELECT ATI.PRD_LVL_NUMBER,ATI.ATR_TYP_TECH_KEY, ATI.ATR_HDR_TECH_KEY, ATI.ATR_CODE, ATI.* FROM SDIPRDATI ATI WHERE PRD_LVL_NUMBER IN ('36160','36161','36121');
SELECT * FROM SDIPRDATI WHERE ATR_TYP_TECH_KEY = 23 AND ATR_HDR_TECH_KEY = 141 ;

SELECT * FROM PIM_PRODUCTO_ATRIB WHERE COD_ATRIBUTO IN 'TipoSurtido' AND ID = 'LT' ;

 SELECT * FROM PIM_MODELO WHERE CONTENIDO LIKE '%HESA_40051%' ;
 SELECT * FROM PIM_MODELO WHERE MENSAJE LIKE '%HESA_40051%' ;
 SELECT * FROM PIM_MODELO WHERE MENSAJE LIKE '%HESA_40050%' ;

SELECT * FROM PRDMSTEE WHERE PRD_LVL_NUMBER IN ('36160','36161','36121','35999');
                                                                -- SKU     CHILD
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM IN 'HESA_40050' ; --36160     124836  LongTail (PIM)
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM IN 'HESA_40051' ; --36161     124837  LongTail (PIM)
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM IN 'HESA_40045' ; --36121     124811  HOME (PIM)
                                                                --35999     124695  LONG TAIL (WEB MANTENEDOR)



select * from edsr.basacdee where atr_hdr_tech_key=141;
select * from edsr.basacdee where atr_hdr_tech_key=104;
select * from EPMM.chlparam where param_value='141';

SELECT * FROM SDIPRDATI WHERE ATR_TYP_TECH_KEY = 23 AND ATR_HDR_TECH_KEY = 141 ;
select distinct atr_long_tail FROM TPPRDMST;
select prd.atr_long_tail, prd.* FROM TPPRDMST prd WHERE PRD_LVL_CHILD IN ('124836','124837');

select prd.atr_long_tail, prd.* FROM TPPRDMST prd WHERE PRD_LVL_NUMBER IN ('36284');
INSERT INTO EDSR.TPPRDMST (ATR_LONG_TAIL, PRD_LVL_CHILD, PRD_LVL_NUMBER, PRD_FULL_NAME, PRD_LVL_ID, COD_DIV, DES_DIV, COD_AREA, DES_AREA, COD_DPTO, DES_DPTO, COD_LIN, DES_LIN, COD_STL, DES_STL, COD_MARCA, DES_MARCA, COD_PRV, DES_PRV, COD_EST, DES_EST, FEC_CRE, FEC_MOD, COD_PROCE, DES_PROCE, PRD_STYLE_IND, PAD_LVL_CHILD, DIV_LVL_CHILD, AREA_LVL_CHILD, DPTO_LVL_CHILD, LIN_LVL_CHILD, COD_BAR, AFECTO, COD_TIPNEG, DES_TIPNEG, FLAG_SERV, DES_SERV, COD_PAIS, DES_BIGTCK, COD_TIPMAN, DES_TIPMAN, FLAG_BIGTCK, COD_BIGTCK, COD_SERV, DIST_QTY, COD_CUR, DES_CUR, COD_TAL, DES_TAL, VPC_PRD_TECH_KEY, VPC_CASE_PACK_ID, INNER_PK_TECH_KEY, INNER_PACK_ID, VPC_TECH_KEY, COD_TIPMAR, COD_PTOPRECIO, DES_PTOPRECIO, COD_UMV, DES_UMV, COD_UMC, DES_UMC, COD_UMI, DES_UMI, COD_PRODFIS, DES_PRODFIS, COD_PERCEP, DES_PERCEP, COD_NRO_PIEZAS, DES_NRO_PIEZAS, LIQUIDACION, PRECIAZO, DESPACHO, DETRACCION, COD_BIGTCK_VTEX, DES_BIGTCK_VTEX, PERECIBLE, COD_SURTIDO, DESTIPSURTIDO, FLAG_ECOM_VTA_PRV, FLAG_ECOM_RETIRO_TDA, FLAG_DESPACHO_RANGO, FLAG_INFALTABLE, ATR_LONG_TAIL, ATR_MOD_DESP, DES_ATR_MOD_DESP, ATR_TOP_2K, DES_ATR_TOP_2K) VALUES (null, 118124, '29108', 'ENGRASADORA NEUMATICA 30L INGCO', 1, 'T02', 'FERRETERIA', 'A04', 'HERRAMIENTAS', 'D018', 'HERRAMIENTAS ELECTRICAS PORTATILES', 'L0077', 'HERRAMIENTAS NEUMATICAS', '29108', 'ENGRASADORA NEUMATICA 30L INGCO', 'INGCO', 'INGCO', '1891782892001', 'GALAIMPORTACIONES CIA.LTDA.', 5, 'Sin Matriz', TIMESTAMP '2023-09-28 15:10:00', TIMESTAMP '2024-08-01 17:00:01', 'NACIONAL', 'NACIONAL', 'F', 118124, 91445, 91453, 91486, 91718, '6925582127188', 'F', 'PROPIA', 'PROPIA', 'F', null, 'EC', null, 'CAJ', 'CAJA', 'F', null, null, 1.0000, null, null, null, null, 131051, 'AGL02301                 ', 202037, 51200, 14376, 'PROVEEDOR', 'OPP', 'OPP', 'UN', 'Unidades', 'UN', 'Unidades', 'UN', 'Unidades', 'NO', 'No es producto peligroso', 'NO', 'NO AFECTO', null, null, 'NO', 'NO', 'PALETIZADO', null, null, null, 'NO', 'H', 'Productos en Home', 'SI', 'SI', 'NO', 'NO', null, '01', 'SI  EXPRESS RETAIL', '02', 'REGULAR');


select e.PRD_LVL_CHILD, e.prd_status, des.PRD_STATUS_DESC, e.*
     -- , row_number() over(partition by PRD_LVL_CHILD order by EFFECT_DATE desc) rn
from PRDSTEEE e
    INNER JOIN EDSR.PRDSTSEE des on des.PRD_STATUS = e.PRD_STATUS
WHERE PRD_LVL_CHILD IN ('124950');

SELECT * FROM ifh_sur_chgstsprdee ORDER BY DATE_EXPORT DESC;
SELECT DISTINCT  PRD_STATUS_ACT FROM ifh_sur_chgstsprdee ;
SELECT DISTINCT  PRD_STATUS_NEW FROM ifh_sur_chgstsprdee ;
SELECT * FROM ifh_sur_chgstsprdee WHERE PRD_LVL_CHILD IN ('124836','124837');
SELECT * FROM ifh_sur_matmstee;

-- BTA: disponible CD
-- BTP: disponible con el Proveedor
-- Atributo Surtido: ATR_TYP_TECH_KEY = 23 | ATR_HDR_TECH_KEY = 141
select * from edsr.basatpee WHERE ATR_COD_TECH_KEY IN (2853);
select * from edsr.basatpee WHERE ATR_TYP_TECH_KEY = 23 AND ATR_HDR_TECH_KEY = 141 AND PRD_LVL_CHILD IN ('124836','124837','124695','124811');

-- Tipos de atributos
SELECT * FROM BASATYEE;
-- Subtipo de atributo: 57 Subtipos | 9 Mandatorios: MATERIAL HANDLING,NOMBRE DE MARCA,PROCEDENCIA,PROCEDENCIA PROV,SURTIDO,TIPO DE MARCA,TIPO NEGOCIACIÓN,TIPO PORTAL,ZONA CROSS
SELECT * FROM BASAHREE; -- 57 Subtipos de Atributo
SELECT * FROM BASAHREE WHERE ATT_MANDATORY = 'T';
SELECT * FROM BASAHREE WHERE ATR_HEADER_DESC LIKE '%SUR%';
SELECT * FROM BASAHREE WHERE ATR_HEADER_DESC LIKE '%LONG%TAIL%';
-- Código de atributo: 2679 ATRIBUTOS
SELECT * FROM BASACDEE WHERE ATR_COD_TECH_KEY IN (2853,2767);
SELECT * FROM BASACDEE WHERE ATR_CODE_DESC LIKE 'L%' ORDER BY ATR_CODE_DESC;
SELECT * FROM BASACDEE ORDER BY ATR_CODE_DESC DESC;

-- Prod. asignados a atributos
SELECT * FROM BASATPEE;

-- Org/Prod asignados a atributos
SELECT * FROM BASATBEE;
-- Org. asignados a atributos
SELECT * FROM BASATOEE;

select e.PRD_LVL_CHILD, e.prd_status, des.PRD_STATUS_DESC,
       row_number() over(partition by PRD_LVL_CHILD order by EFFECT_DATE desc) rn
from PRDSTEEE e INNER JOIN EDSR.PRDSTSEE des on des.PRD_STATUS = e.PRD_STATUS
;
-- PKG_PIM_INTEGRACION: CARGA_ATR_SDI
 SELECT
        'V_BATCH_NUM',
        ROWNUM,
        '66',
        0,
        ATR_TYP_TECH_KEY,
        ATR_HDR_TECH_KEY,
        ID,
        'A',
        1
      FROM PIM_PRODUCTO_ATRIB
      WHERE ID_PIM_PROD = 66
        AND ATR_TYP_TECH_KEY IS NOT NULL;

-- Long Tail: ATR_TYP_TECH_KEY: 21 | ATR_HDR_TECH_KEY: 159

SELECT * FROM PIM_PRODUCTO WHERE PRD_LVL_NUMBER IN ('36160');
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM IN 'HESA_40050' ;

SELECT * FROM PIM_ATRIBUTO WHERE ATR_TYP_TECH_KEY IS NOT NULL;
INSERT INTO EDSR.PIM_ATRIBUTO (COD_ATRIBUTO, DES_ATRIBUTO, FLG_UND_MEDIDA, FLG_ID_VAL, FLG_CAMPO_ADD, ATR_TYP_TECH_KEY, ATR_HDR_TECH_KEY, NOMBRE_ATRIB_PIM) VALUES ('LongTail', 'Long Tail', '0', 'LV', '0', 21, 159, null);

SELECT * FROM PIM_ATRIBUTO WHERE ATR_TYP_TECH_KEY IS NOT NULL;
SELECT * FROM PIM_MODELO WHERE CONTENIDO LIKE '%HESA_40050%';
SELECT * FROM BASAHREE WHERE ATR_TYP_TECH_KEY IN (21) AND  ATR_HDR_TECH_KEY IN (159,104);
SELECT * FROM BASAHREE WHERE ATT_MANDATORY = 'T' AND APP_FUNC = 'PRD' order by ATR_HEADER_DESC;
SELECT ATR.ATR_TYP_TECH_KEY, ATR.* FROM PIM_PRODUCTO_ATRIB ATR WHERE ID_PIM_PROD = 66 ORDER BY ATR.ATR_TYP_TECH_KEY, COD_ATRIBUTO;

SELECT * FROM PIM_ATRIBUTO;

 C_ATR_CODLINEA          CONSTANT VARCHAR2(50) := 'CodLinea';
  C_ATR_PROVEEDOR         CONSTANT VARCHAR2(50) := 'Proveedor';
  C_ATR_UMV               CONSTANT VARCHAR2(50) := 'UMV';
  C_ATR_PROCEDENCIA       CONSTANT VARCHAR2(50) := 'Procedencia';
  C_ATR_MP_CANT           CONSTANT VARCHAR2(50) := 'MasterPackCantidad';
  C_ATR_EAN               CONSTANT VARCHAR2(50) := 'EAN';
  C_ATR_EAN_TIPO          CONSTANT VARCHAR2(50) := 'TipoEan';
  C_ATR_PRECIO_UNIT       CONSTANT VARCHAR2(50) := 'PrecioUnitario';
  C_ATR_SKU_PROVEEDOR     CONSTANT VARCHAR2(50) := 'SkuProveedor';
  C_ATR_UMI               CONSTANT VARCHAR2(50) := 'UMI';
  C_ATR_COSTO             CONSTANT VARCHAR2(50) := 'Costo';
  C_ATR_PESO_BRUTO        CONSTANT VARCHAR2(50) := 'PesoUnidadLogistica';
  C_ATR_PESO_NETO         CONSTANT VARCHAR2(50) := 'PesoProducto';
  C_ATR_UND_LOG_ALTO      CONSTANT VARCHAR2(50) := 'AlturaUnidadLogistica';
  C_ATR_UND_LOG_ANCHO     CONSTANT VARCHAR2(50) := 'AnchoUnidadLogistica';

  C_ATR_UND_LOG_LONGITUD  CONSTANT VARCHAR2(50) := 'ProfundidadUnidadLogistica';
  C_ATR_UND_LOG_VOLUMEN   CONSTANT VARCHAR2(50) := 'VolumendelaUnidadLogistica';
  C_ATR_DUN14             CONSTANT VARCHAR2(50) := 'DUN14';
  C_ATR_TIPO_SURTIDO      CONSTANT VARCHAR2(50) := 'TipoSurtido';
  C_ATR_CLUSTER_SURTIDO   CONSTANT VARCHAR2(50) := 'ClusterSurtido';
  C_ATR_MARCA             CONSTANT VARCHAR2(50) := 'Marca';
  C_ATR_MP_TIPO           CONSTANT VARCHAR2(50) := 'MasterPackTipo';
  C_ATR_PERECIBLE         CONSTANT VARCHAR2(50) := 'Perecible';
  C_ATR_PUNTO_PRECIO      CONSTANT VARCHAR2(50) := 'PuntoPrecio';
  C_ATR_TIPO_MARCA        CONSTANT VARCHAR2(50) := 'TipoMarca';
  C_ATR_TIPO_NEG          CONSTANT VARCHAR2(50) := 'TipoNegociacion';
  C_ATR_LONG_TAIL         CONSTANT VARCHAR2(50) := 'LongTail';