-- MIGRACION QA a PRD
SELECT * FROM PIM_MODELO_TIPO;
SELECT * FROM PIM_ATRIBUTO;

--DELETE FROM PIM_MODELO; Commit;
SELECT * FROM PIM_MODELO where trunc(FEC_CREACION) = trunc (sysdate) and ID_TIPO = 1;
SELECT * FROM PIM_PRODUCTO;
SELECT * FROM PIM_PRODUCTO_ATRIB;
SELECT * FROM PIM_PRODUCTO_DATA_PMM;
--SELECT * FROM PIM_MODIFICACIONES_PMM;

SELECT DISTINCT PRD.COD_MARCA, PRD.DES_MARCA --, PRD.COD_AREA , PRD.*
FROM EDSR.TPPRDMST PRD
ORDER BY PRD.COD_MARCA ;

SELECT * FROM PIM_MODELO_REQUEST WHERE ID_MODELO = 91;
SELECT * FROM PIM_MODELO_REQUEST ORDER BY FEC_REG DESC;
SELECT * FROM PIM_PRODUCTO ORDER BY FEC_CREACION DESC;

     SELECT * FROM  basahree WHERE app_func = 'PRD' ;
     SELECT * FROM  basahree WHERE app_func = 'PRD' AND ATR_HEADER_DESC LIKE '%REND%';
     SELECT * FROM  basahree WHERE  ATR_HEADER_DESC LIKE '%REND%';


SELECT PRD.PRD_LVL_NUMBER FROM PRDMSTEE PRD ORDER BY PRD.PRD_LVL_NUMBER DESC; --36063
-- PKG_PIM_INTEGRACION

-- SP_GET_TRAMAS_PENDIENTES
SELECT ID_MODELO, PIM.FEC_CREACION, PIM.FLG_PROCESADO, PIM.FLG_ERROR,PIM.FEC_PROCESO --, PIM.*
    --PIM.ID_MODELO, TO_CLOB(TO_NCLOB(PIM.CONTENIDO)) CONTENIDO,
FROM edsr.pim_modelo PIM
WHERE ID_TIPO = 1
      AND NOT FLG_PROCESADO = '0'
      AND NOT FLG_ERROR = '0'
     -- AND TRUNC(FEC_CREACION) = TRUNC(SYSDATE) - 1
     -- AND FEC_PROCESO IS NULL
ORDER BY FEC_CREACION DESC;

--GET SKU
SELECT
 Id_Modelo, Id_Tipo --,TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO
FROM edsr.pim_modelo
WHERE id_tipo = 2 and FLG_PROCESADO = '0';


SELECT * FROM EDSR.PIM_MODELO
--UPDATE edsr.pim_modelo SET FLG_PROCESADO = '0', FLG_ERROR = '0'
WHERE ID_MODELO >= 1011;

-- SP_GET_TRAMAS_PENDIENTES: Tramas a Procesar desde INICIO, esto indica que obtendra una lista para crear productos y sus atributos correspondientes.
SELECT ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO  FROM EDSR.PIM_MODELO
-- UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '1'
WHERE ID_TIPO = 1 and FLG_PROCESADO = '0' and FLG_ERROR = '0'
ORDER BY FEC_CREACION;

SELECT ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO  FROM EDSR.PIM_MODELO
-- UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '1'
WHERE ID_TIPO = 2 and FLG_PROCESADO = '0' and FLG_ERROR = '0'
ORDER BY FEC_CREACION;

-- SP_GET_TRAMAS_PENDIENTES: Tramas a Procesar para ACTUALIZAR, esto indica que obtendra una lista para actualizar productos y sus atributos correspondientes.
SELECT ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO FROM EDSR.PIM_MODELO
-- UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '1'
WHERE ID_TIPO = 3 and FLG_PROCESADO = '0' and FLG_ERROR = '0'
ORDER BY FEC_CREACION;

-- Listar para mandar a OIC
SELECT  Id_Modelo, Id_Tipo, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO,FLG_PROCESADO
FROM edsr.pim_modelo WHERE id_tipo = 2 and FLG_PROCESADO = '0'
ORDER BY FEC_CREACION DESC;

/*
VALIDAR_DATA_PIM (EL PROVEEDOR NO EXISTE)
SP_VALIDAR_NUEVO -> VALIDAR_PROVEEDOR -> (2)

ID_TIPO
1: Crear producto PIM a PMM
2: Actualizar SKU PMM a PIM
3: Actualizar atributos
 */
SELECT * FROM edsr.pim_modelo WHERE ID_MODELO > 847;
SELECT * FROM EDSR.PIM_MODELO WHERE TRUNC(FEC_CREACION) = TRUNC(SYSDATE) ORDER BY FEC_CREACION DESC;
SELECT * FROM EDSR.PIM_MODELO WHERE TRUNC(FEC_CREACION) = TRUNC(TO_DATE('2024-03-22','YYYY-MM-DD')) ORDER BY FEC_CREACION DESC;
SELECT * FROM EDSR.PIM_MODELO WHERE TRUNC(FEC_CREACION) >= TRUNC(SYSDATE) - INTERVAL '5' DAY ORDER BY FEC_CREACION DESC;
SELECT M.ID_MODELO,M.ID_TIPO,M.FLG_PROCESADO,M.FEC_CREACION, TO_CHAR(FEC_CREACION,'YYYYMMDD'),TRUNC(FEC_CREACION),TRUNC(SYSDATE) - INTERVAL '3' DAY FROM EDSR.PIM_MODELO M ORDER BY FEC_CREACION DESC;
SELECT M.ID_MODELO,M.ID_TIPO,M.FLG_PROCESADO,M.FEC_CREACION FROM EDSR.PIM_MODELO M WHERE TO_CHAR(FEC_CREACION,'YYYYMMDD') = '20240322' ORDER BY FEC_CREACION DESC;
SELECT M.ID_MODELO,M.ID_TIPO,M.FLG_PROCESADO,M.FEC_CREACION FROM EDSR.PIM_MODELO M WHERE TRUNC(FEC_CREACION) = TRUNC(TO_DATE('2024-03-22','YYYY-MM-DD')) ORDER BY FEC_CREACION DESC;
SELECT M.ID_MODELO,M.ID_TIPO,M.FLG_PROCESADO,M.FEC_CREACION FROM EDSR.PIM_MODELO M WHERE TRUNC(FEC_CREACION) >= TRUNC(SYSDATE) - INTERVAL '5' DAY ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.pim_modelo WHERE FLG_PROCESADO = '0' ORDER BY ID_MODELO DESC;
SELECT * FROM edsr.pim_modelo WHERE ID_TIPO = 1 ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.pim_modelo WHERE ID_TIPO = 2 ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.pim_modelo WHERE ID_TIPO = 3 ORDER BY FEC_CREACION DESC;
SELECT FLG_PROCESADO,FLG_ERROR, ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO FROM edsr.pim_modelo
-- UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '1'
WHERE ID_MODELO IN (646);

SELECT * FROM edsr.PIM_PRODUCTO ORDER BY FEC_CREACION DESC;
SELECT * FROM edsr.PIM_PRODUCTO WHERE ID_PIM_PROD = 704;
SELECT * FROM edsr.PIM_PRODUCTO WHERE ID_PIM = 'HESA_TEST_100118';
SELECT * FROM edsr.PIM_PRODUCTO_ATRIB WHERE ID_PIM = 'HESA_PRUEBA_100050';
-- LV: Lista de Valores
-- TL: Texto Libre
SELECT COD_ATRIBUTO,DECODE(FLG_ID_VAL, 'TL', VALOR, NVL(ID,VALOR)) FROM PIM_PRODUCTO_ATRIB
WHERE ID_PIM_PROD = 606 AND COD_ATRIBUTO   = 'PesoUnidadLogistica';


DECLARE
    V_PIM_PRD INTEGER := 728;
    V_RESULT INTEGER;
BEGIN
    PKG_PIM_INTEGRACION.SP_CREAR_PRODUCTO(V_PIM_PRD,V_RESULT);
    DBMS_OUTPUT.PUT_LINE('V_RESULT: ' || V_RESULT);
END;

SELECT * FROM edsr.pim_modelo ORDER BY FEC_CREACION DESC;

SELECT * FROM EDSR.PIM_MODELO
--UPDATE EDSR.PIM_MODELO SET FLG_PROCESADO = '0'
WHERE ID_TIPO = 2 AND ID_MODELO >= 843;

SELECT FLG_PROCESADO,FLG_ERROR, ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO FROM edsr.pim_modelo
--UPDATE edsr.pim_modelo SET FLG_PROCESADO = '1', FLG_ERROR = '0'
WHERE ID_MODELO = 710 and FLG_PROCESADO = '0' and FLG_ERROR = '0';

SELECT FLG_PROCESADO,FLG_ERROR, ID_MODELO, TO_CLOB(TO_NCLOB(CONTENIDO)) CONTENIDO FROM edsr.pim_modelo
--UPDATE edsr.pim_modelo SET FLG_PROCESADO = '1', FLG_ERROR = '0'
WHERE ID_MODELO IN (
870,
871,
866,
869,
868,
867) and FLG_PROCESADO = '0' and FLG_ERROR = '0';

DECLARE
    in_ID_PIM_PROD     PIM_PRODUCTO.ID_PIM_PROD%type;
    in_ID_PIM          PIM_PRODUCTO.ID_PIM%type := 'HESA_PRUEBA_100050';
    in_ID_MODELO       PIM_PRODUCTO.ID_MODELO%type := 710;
    in_DESCRIPCION     PIM_PRODUCTO.DESCRIPCION%type := 'Lapiz Plumon Ceramica Retiro 59x2';
    in_prd_lvl_number  PIM_PRODUCTO.prd_lvl_number%type default '';
BEGIN

    BEGIN
        --PKG_PIM_INTEGRACION.SP_INS_PIM_PRODUCTO(in_ID_PIM,in_ID_MODELO,in_DESCRIPCION,in_ID_PIM_PROD,in_prd_lvl_number);
        PKG_PIM_INTEGRACION.SP_INS_PIM_PRODUCTO(in_ID_PIM,in_ID_PIM_PROD);
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('EXCEPTION: ' || SQLERRM) ;
    END;
END;

-- DEBUG
DECLARE
    V_RETORNO    VARCHAR2(50);
    V_PESO_BRUTO  NUMBER(15,4);
BEGIN
  SELECT DECODE(FLG_ID_VAL, 'TL', VALOR, NVL(ID,VALOR))
    INTO V_RETORNO
  FROM PIM_PRODUCTO_ATRIB
  WHERE ID_PIM_PROD    = 646
    AND COD_ATRIBUTO   = 'PesoUnidadLogistica';

  DBMS_OUTPUT.PUT_LINE('V_RETORNO: ' || V_RETORNO) ;
  V_PESO_BRUTO := TO_VARCHAR(V_RETORNO,'9999999999.99999');

  DBMS_OUTPUT.PUT_LINE('V_PESO_BRUTO: ' || V_PESO_BRUTO) ;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('EXCEPTION: ' || SQLERRM) ;
END;


SELECT VPC_CASE_GROSS_WGT FROM SDIVPCCSI;
SELECT * FROM PRDMSTEE WHERE PRD_NAME_FULL LIKE '%MESA%MINI%BLANC%52X37CM%ORANGE%';
SELECT ID_PIM,COD_ATRIBUTO, FLG_ID_VAL, VALOR, ID FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD    = 606;

SELECT ID_PIM, PRD_LVL_CHILD, PRD_LVL_NUMBER, prd_name_full, estadoProducto, dun14, razon_social, codigo_proveedor
              , umi, ean, umv, sku_proveedor, tipo_surtido
FROM EDSR.PIM_PRODUCTO_DATA_PMM;




-- Procesar para que no se manden a OIC
SELECT * FROM edsr.pim_modelo
--UPDATE PIM_MODELO SET FLG_PROCESADO = '1'
WHERE ID_TIPO = 2 AND FLG_PROCESADO = '0' AND ID_MODELO IN (765,763);--  AND ID_MODELO>=755 AND ID_MODELO <=762 --AND ID_MODELO NOT IN (752,753,754);

--ULTIMO PASO: SP_ACTUALIZA_PIM_MODELO
/*
UPDATE PIM_MODELO
SET flg_procesado = '1',
    Mensaje = 'OK',
    FEC_PROCESO = sysdate
WHERE ID_TIPO = 2 AND ID_MODELO = in_id_Modelo;
 */



create table PIM_PRODUCTO
(
    ID_PIM_PROD    NUMBER(18)           not null constraint PK_PIM_PRODUCTO primary key,
    ID_MODELO      NUMBER(18)           not null,
    ID_PIM         VARCHAR2(18)         not null,
    DESCRIPCION    VARCHAR2(50)         not null,
    FEC_CREACION   DATE default SYSDATE not null,
    FLG_PROCESADO  CHAR default '0'     not null constraint CH_PIM_PRODUCTO_PROCESADO check (flg_procesado IN ('0', '1')),
    FEC_PROCESO    DATE,
    PRD_LVL_CHILD  NUMBER(12),
    FLG_ERROR      CHAR default '0'     not null constraint CH_PIM_PRODUCTO_ERROR check (flg_error IN ('0', '1')),
    MENSAJE        VARCHAR2(4000),
    PRD_LVL_NUMBER VARCHAR2(50)
);

create table PIM_PRODUCTO
(
    ID_PIM_PROD    NUMBER(18)           not null constraint PK_PIM_PRODUCTO primary key,
    ID_MODELO      NUMBER(18)           not null,
    ID_PIM         VARCHAR2(18)         not null,
    DESCRIPCION    VARCHAR2(50)         not null,
    FEC_CREACION   DATE default SYSDATE not null,
    FLG_PROCESADO  CHAR default '0'     not null constraint CH_PIM_PRODUCTO_PROCESADO check (flg_procesado IN ('0', '1')),
    FEC_PROCESO    DATE,
    PRD_LVL_CHILD  NUMBER(12),
    FLG_ERROR      CHAR default '0'     not null constraint CH_PIM_PRODUCTO_ERROR check (flg_error IN ('0', '1')),
    MENSAJE        VARCHAR2(4000),
    PRD_LVL_NUMBER VARCHAR2(50)
);




SELECT p.prd_lvl_child, trim(p.prd_lvl_number) prd_lvl_number, trim(p.prd_name_full) prd_name_full
             --campos nuevos
             , TO_CHAR(est.prd_status) prd_status, to_char(dun.prd_upc) dun14, prov.vendor_name, to_char(prov.vendor_number) vendor_number
             , vpc.INV_UOM UMI, to_char(ean.prd_upc) ean, vpc.VPC_CASE_QTY_UOM, vpc.VPC_CASE_PACK_ID sku_proveedor
             , tipo_surt.ATR_CODE tipo_surtido
 FROM prdmstee p
 INNER JOIN (select e.PRD_LVL_CHILD, e.prd_status,
       row_number() over(partition by PRD_LVL_CHILD order by EFFECT_DATE desc) rn
       from PRDSTEEE e) est
   on est.PRD_LVL_CHILD = p.PRD_LVL_CHILD and est.rn = 1
 LEFT JOIN PRDUPCEE dun on dun.PRD_LVL_CHILD = p.PRD_LVL_CHILD and dun.upc_type = 14 and dun.active_flag ='T'
 LEFT JOIN PRDUPCEE ean on dun.PRD_LVL_CHILD = p.PRD_LVL_CHILD and dun.upc_type = 13 and dun.default_flag ='T'
 LEFT JOIN vpcprdee vpc on dun.vpc_prd_tech_key = vpc.vpc_prd_tech_key
 LEFT JOIN vpcmstee prov on vpc.vpc_tech_key = prov.vpc_tech_key
 LEFT JOIN basatpee des_atr on p.PRD_LVL_CHILD = des_atr.PRD_LVL_CHILD and atr_hdr_tech_key = 141
 LEFT JOIN basacdee tipo_surt on des_atr.ATR_COD_TECH_KEY = tipo_surt.ATR_COD_TECH_KEY;


SELECT DISTINCT UPC_TYPE FROM PRDUPCEE;