SELECT * FROM PIM_MODELO_TIPO;
SELECT * FROM PIM_ATRIBUTO;

SELECT * FROM PIM_MODELO WHERE ID_TIPO = 1 ORDER BY FEC_PROCESO DESC ;
SELECT * FROM PIM_MODELO ORDER BY FEC_PROCESO DESC;
SELECT * FROM PIM_PRODUCTO ORDER BY FEC_PROCESO DESC;
SELECT * FROM PIM_PRODUCTO_ATRIB WHERE ID_PIM_PROD = 54;
SELECT * FROM PRDMSTEE ORDER BY PRD_LVL_NUMBER DESC;
SELECT * FROM PIM_PRODUCTO;
SELECT ID_PIM, PRD_LVL_NUMBER FROM PIM_PRODUCTO WHERE ID_PIM IN ('HESA_40012','HESA_40013','HESA_40014','HESA_40015','HESA_40028','HESA_40037','HESA_40043','HESA_40044','HESA_40048') AND PRD_LVL_NUMBER IS NOT NULL;
SELECT * FROM PIM_PRODUCTO_ATRIB;
SELECT  * FROM EDSR.PIM_PRODUCTO_DATA_PMM;




SELECT * FROM PRDUPCEE WHERE prd_upc LIKE '%37705152065788%';

DECLARE
    V_ID_PIM_PROD INTEGER := 1;
    V_RESULT INTEGER;
BEGIN
    PKG_PIM_INTEGRACION.SP_CREAR_PRODUCTO(V_ID_PIM_PROD,V_RESULT);
    DBMS_OUTPUT.PUT_LINE('ID_PIM_PROD: ' || V_ID_PIM_PROD);
    DBMS_OUTPUT.PUT_LINE('RESULT: ' || V_RESULT);
END;

SELECT * FROM PIM_PRODUCTO_ATRIB WHERE COD_ATRIBUTO = 'Marca';

select trim(atr_code)
    --  into V_COD_ATR
from basacdee
      where atr_hdr_tech_key  in (select ATR_HDR_TECH_KEY from PIM_ATRIBUTO where cod_atributo = 'Marca')
and atr_code_desc = upper('RIMAX'); -- RIMAX \ RIMAX

-- Lista de Proveedores
SELECT WPE.VENDOR_NUMBER ID, WPE.VENDOR_NAME RazonSocial FROM EDSR.VPCMSTEE WPE;
SELECT WPE.VENDOR_NUMBER ID, WPE.VENDOR_NAME RazonSocial, WPE.* FROM EDSR.VPCMSTEE WPE WHERE VPC_TECH_KEY = 14482;
SELECT WPE.VENDOR_NUMBER ID, WPE.VENDOR_NAME RazonSocial FROM EDSR.VPCMSTEE WPE WHERE VPC_TECH_KEY = 14482;

-- Lista de Marcas
--
SELECT  * FROM EDSR.TPPRDMST PRD;
-- Maestra códigos de barra
SELECT  * FROM EDSR.PRDUPCEE;
-- Tipos de códigos de barra
SELECT  * FROM EDSR.PRDUCDEE;
-- Maestro de Case Pack
SELECT  * FROM EDSR.VPCPRDEE;
SELECT  * FROM EDSR.SDIPRDATI;
SELECT  * FROM EDSR.ORGMSTEE;
SELECT  * FROM EDSR.SDIUPIREJ;
SELECT  * FROM EDSR.PRDPRCREJ;
SELECT  * FROM EDSR.SDIREJCD;
SELECT  * FROM EDSR.SDIVPCREJ;
SELECT  * FROM EDSR.SDIVPCUPI;
SELECT  * FROM EDSR.PRDPCDEE;
SELECT  * FROM EDSR.SDIPRDPCI;
SELECT  * FROM EDSR.IFH_PARAMETROS;
SELECT * FROM BASAHREE;

-- Proveedor
SELECT * FROM VPCMSTEE V WHERE TRIM(V.VENDOR_NUMBER) = trim('V_VENDOR_NUMBER');

 SELECT TRIM(P.PARAM_VALUE), P.* FROM CHLPARAM P;
 SELECT TO_CHAR(CNTRY_LVL_CHILD), VPC.* FROM VPCMSTEE VPC;
SELECT PARAM_VALUE FROM CHLPARAM WHERE PARAM_CODE = 'CHAIN';


SELECT  * FROM EDSR.PRDCTLEE PLV WHERE PRD_LVL_NAME = 'Area';
SELECT  * FROM EDSR.PRDPLVEE PLV WHERE PRD_NAME_FULL LIKE '%KETER%';

SELECT distinct PRD.COD_MARCA, PRD.DES_MARCA FROM EDSR.TPPRDMST PRD;