--PRD
SELECT * FROM PRDMSTEE WHERE PRD_LVL_NUMBER = '36064';
--EAN
SELECT PRD.PRD_LVL_NUMBER, EAN.* FROM PRDUPCEE EAN INNER JOIN PRDMSTEE PRD ON PRD.PRD_LVL_CHILD = EAN.PRD_LVL_CHILD
WHERE PRD_UPC IN ('7861123201285');