SELECT P.PRD_LVL_CHILD,
           TRIM(P.PRD_LVL_NUMBER) PRD_LVL_NUMBER,
           TRIM(REPLACE(REPLACE(REPLACE(P.PRD_NAME_FULL, CHR(10), ''),
                                CHR(13),
                                ''),
                        CHR(9),
                        '')) PRD_FULL_NAME,
           P.PRD_LVL_ID,
           TRIM(DIV.PRD_LVL_NUMBER) COD_DIV,
           TRIM(DIV.PRD_NAME_FULL) DES_DIV,
           TRIM(ARE.PRD_LVL_NUMBER) COD_AREA,
           TRIM(ARE.PRD_NAME_FULL) DES_AREA,
           TRIM(DEP.PRD_LVL_NUMBER) COD_DPTO,
           TRIM(DEP.PRD_NAME_FULL) DES_DPTO,
           TRIM(LIN.PRD_LVL_NUMBER) COD_LIN,
           TRIM(LIN.PRD_NAME_FULL) DES_LIN,
           T_MAR.ATR_CODE COD_MARCA,
           T_MAR.ATR_CODE_DESC DES_MARCA,
           TRIM(PRV.VENDOR_NUMBER) COD_PRV,
           TRIM(PRV.VENDOR_NAME) DES_PRV,
           TRIM(EST.PRD_STATUS) COD_EST,
           TRIM(EST.PRD_STATUS_DESC) DES_EST,
           T_PROC.ATR_CODE COD_PROCE,
           T_PROC.ATR_CODE_DESC DES_PROCE,
           P.PRD_STYLE_IND,
           DIV.PRD_LVL_CHILD DIV_LVL_CHILD,
           ARE.PRD_LVL_CHILD AREA_LVL_CHILD,
           DEP.PRD_LVL_CHILD DPTO_LVL_CHILD,
           LIN.PRD_LVL_CHILD LIN_LVL_CHILD,
           NVL(UPC.PRD_UPC, 0) COD_BAR,
           DECODE(FNU_GET_PRODUCTO_IVA(P_PRD_LVL_CHILD => p.PRD_LVL_CHILD), 0, 'T', 'F') AFECTO,
           T_TNEG.ATR_CODE COD_TIPNEG,
           T_TNEG.ATR_CODE_DESC DES_TIPNEG,
           NVL2(T_TSER.ATR_CODE, 'T', 'F') FLAG_SERV,
           T_TSER.ATR_CODE_DESC DES_SERV,
           TRIM(DIR.CNTRY_CODE) COD_PAIS,
           T_BIGT.ATR_CODE_DESC DES_BIGTCK,
           T_TMAN.ATR_CODE COD_TIPMAN,
           T_TMAN.ATR_CODE_DESC DES_TIPMAN,
           NVL2(T_BIGT.ATR_CODE, 'T', 'F') FLAG_BIGTCK,
           T_BIGT.ATR_CODE COD_BIGTCK,
           T_TSER.ATR_CODE COD_SERV,
           NVL(WHS.TRF_DIST_PAK, 0) DIST_QTY,
           T_CUR.ATR_CODE COD_CUR,
           T_CUR.ATR_CODE_DESC DES_CUR,
           T_TAL.ATR_CODE COD_TAL,
           T_TAL.ATR_CODE_DESC DES_TAL,
           CP.VPC_PRD_TECH_KEY,
           CP.VPC_CASE_PACK_ID,
           CP.INNER_PK_TECH_KEY,
           CP.INNER_PACK_ID,
           P.PRD_VPC_TECH_KEY VPC_TECH_KEY,
           T_TMAR.ATR_CODE COD_TIPMAR,
           T_PTOP.ATR_CODE COD_PTOPRECIO,
           T_PTOP.ATR_CODE_DESC DES_PTOPRECIO,
           TRIM(UMV.UOM_CODE) COD_UMV,
           TRIM(UMV.UOM_DESC) DES_UMV,
           TRIM(UMC.UOM_CODE) COD_UMC,
           TRIM(UMC.UOM_DESC) DES_UMC,
           TRIM(UMI.UOM_CODE) COD_UMI,
           TRIM(UMI.UOM_DESC) DES_UMI,
           T_PRDF.ATR_CODE COD_PRODFIS,
           T_PRDF.ATR_CODE_DESC DES_PRODFIS,
           T_PERC.ATR_CODE COD_PERCEP,
           T_PERC.ATR_CODE_DESC DES_PERCEP,
           T_PIEZ.ATR_CODE COD_NRO_PIEZAS,
           T_PIEZ.ATR_CODE_DESC DES_NRO_PIEZAS,
           T_LIQ.ATR_CODE LIQUIDACION,
           T_PREZ.ATR_CODE PRECIAZO,
           T_DESP.ATR_CODE_DESC DESPACHO,
           T_DETR.ATR_CODE DETRACCION,
           T_BIGT_V.ATR_CODE COD_BIGTCK_VTEX,
           T_BIGT_V.ATR_CODE_DESC DES_BIGTCK_VTEX,
           T_PERE.ATR_CODE PERECIBLE,
           T_TSUR.ATR_CODE COD_SURTIDO,
           T_TSUR.ATR_CODE_DESC DESTIPSURTIDO,
           T_ERT.ATR_CODE FLAG_ECOM_RETIRO_TDA,
           T_RDES.ATR_CODE FLAG_DESPACHO_RANGO,
           T_FLG_E.ATR_CODE FLAG_ECOM_VTA_PRV,
           T_FLG_I.ATR_CODE FLAG_INFALTABLE,
           T_TLGT.ATR_CODE ATR_LONG_TAIL,
           T_TMD.ATR_CODE ATR_MOD_DESP,
           T_TMD.ATR_CODE_DESC DES_ATR_MOD_DESP,
           T_TOP2K.ATR_CODE ATR_TOP_2K,
           T_TOP2K.ATR_CODE_DESC DES_ATR_TOP_2K
      FROM PRDMSTEE P
     INNER JOIN PRDMSTEE LIN
        ON P.PRD_LVL_PARENT = LIN.PRD_LVL_CHILD
     INNER JOIN PRDMSTEE DEP
        ON LIN.PRD_LVL_PARENT = DEP.PRD_LVL_CHILD
     INNER JOIN PRDMSTEE ARE
        ON DEP.PRD_LVL_PARENT = ARE.PRD_LVL_CHILD
     INNER JOIN PRDMSTEE DIV
        ON ARE.PRD_LVL_PARENT = DIV.PRD_LVL_CHILD
     INNER JOIN PRDSTSEE EST
        ON P.PRD_STATUS = EST.PRD_STATUS
      LEFT JOIN VPCMSTEE PRV
        ON P.PRD_VPC_TECH_KEY = PRV.VPC_TECH_KEY
      LEFT JOIN BASADREE DIR
        ON PRV.BAS_ADD_KEY = DIR.BAS_ADD_KEY
      LEFT JOIN TPPRDMST_UPC_TMP UPC
        ON P.PRD_LVL_CHILD = UPC.PRD_LVL_CHILD
      /*LEFT JOIN (SELECT J.PRD_LVL_CHILD
                   FROM (SELECT CONNECT_BY_ROOT P.PRD_LVL_CHILD PRD_LVL_CHILD,
                                CONNECT_BY_ROOT P.PRD_LVL_ID PRD_LVL_ID,
                                P.PRD_LVL_CHILD PRD_LVL_PARENT,
                                P.PRD_LVL_ID    PRD_LVL_ID_PARENT
                           FROM PRDMSTEE P
                         CONNECT BY PRIOR P.PRD_LVL_PARENT = P.PRD_LVL_CHILD) J
                  INNER JOIN TXSEXPEE T
                     ON J.PRD_LVL_PARENT = T.EXP_PRD_LVL_CHILD
                    AND J.PRD_LVL_ID_PARENT = T.PRD_LVL_ID
                    AND J.PRD_LVL_ID = 1
                    AND T.TXS_CODE_TECH_KEY = 45) AFE
        ON P.PRD_LVL_CHILD = AFE.PRD_LVL_CHILD*/
      LEFT JOIN (SELECT CP2.PRD_LVL_CHILD,
                        CP2.VPC_PRD_TECH_KEY,
                        CP2.VPC_CASE_PACK_ID,
                        CP2.VPC_CASE_QTY_UOM,
                        CP2.INV_UOM,
                        IP0.INNER_PK_TECH_KEY,
                        IP0.INNER_PACK_ID
                   FROM VPCPRDEE CP2
                  INNER JOIN (SELECT MAX(CP1.VPC_PRD_TECH_KEY) VPC_PRD_TECH_KEY
                               FROM VPCPRDEE CP1
                              WHERE CP1.VPC_PRIMARY_FLAG = 'T'
                              GROUP BY CP1.PRD_LVL_CHILD) CP3
                     ON CP2.VPC_PRD_TECH_KEY = CP3.VPC_PRD_TECH_KEY
                  LEFT JOIN PRDPCDEE IP0 ON IP0.INNER_PK_TECH_KEY = CP2.INNER_PK_TECH_KEY) CP
        ON P.PRD_LVL_CHILD = CP.PRD_LVL_CHILD
      /*LEFT JOIN (SELECT IP2.PRD_LVL_CHILD,
                        IP2.INNER_PK_TECH_KEY,
                        IP2.INNER_PACK_ID
                   FROM PRDPCDEE IP2
                  INNER JOIN (SELECT MAX(IP1.INNER_PK_TECH_KEY) INNER_PK_TECH_KEY
                               FROM PRDPCDEE IP1
                              WHERE IP1.LOOSE_PACK_FLAG = 'F'
                              GROUP BY IP1.PRD_LVL_CHILD) IP3
                     ON IP2.INNER_PK_TECH_KEY = IP3.INNER_PK_TECH_KEY) IP
        ON P.PRD_LVL_CHILD = IP.PRD_LVL_CHILD*/
      LEFT JOIN WHSPRDEE WHS
        ON P.PRD_LVL_CHILD = WHS.PRD_LVL_CHILD
       AND WHS.ORG_LVL_CHILD IN
           (SELECT PARAM_VALUE FROM CHLPARAM WHERE PARAM_CODE = 'CENTRODIS')
      LEFT JOIN PRDUOMEE UMV
        ON P.PRD_SLL_UOM = UMV.UOM_CODE
      LEFT JOIN PRDUOMEE UMC
        ON CP.VPC_CASE_QTY_UOM = UMC.UOM_CODE
      LEFT JOIN PRDUOMEE UMI
        ON CP.INV_UOM = UMI.UOM_CODE
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPMARCA', 'HDRMARCA')) T_MAR
        ON P.PRD_LVL_CHILD = T_MAR.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPCOMER', 'HDRPROC')) T_PROC
        ON P.PRD_LVL_CHILD = T_PROC.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPCOMER', 'HDRPTOPRE')) T_PTOP
        ON P.PRD_LVL_CHILD = T_PTOP.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPPROD', 'HDRTIPNEG')) T_TNEG
        ON P.PRD_LVL_CHILD = T_TNEG.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPPROD', 'HDRSERV')) T_TSER
        ON P.PRD_LVL_CHILD = T_TSER.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPOPER', 'HDRTIPMAN')) T_TMAN
        ON P.PRD_LVL_CHILD = T_TMAN.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPOPER', 'HDRBIGTIC')) T_BIGT
        ON P.PRD_LVL_CHILD = T_BIGT.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPMARCA', 'HDRTIPMAR')) T_TMAR
        ON P.PRD_LVL_CHILD = T_TMAR.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPOPER', 'HDRPRODFIS')) T_PRDF
        ON P.PRD_LVL_CHILD = T_PRDF.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPOPER', 'HDRPERCEP')) T_PERC
        ON P.PRD_LVL_CHILD = T_PERC.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPOPER', 'HDRCURTAL')) T_CUR
        ON P.PRD_LVL_CHILD = T_CUR.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPOPER', 'HDRCOMTAL')) T_TAL
        ON P.PRD_LVL_CHILD = T_TAL.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPPIEZAS', 'HDRPIEZAS')) T_PIEZ
        ON P.PRD_LVL_CHILD = T_PIEZ.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPATRLIQ', 'HDRATRLIQ')) T_LIQ
        ON P.PRD_LVL_CHILD = T_LIQ.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPATRPREZ', 'HDRATRPREZ')) T_PREZ
        ON P.PRD_LVL_CHILD = T_PREZ.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPATRDESP', 'HDRATRDESP')) T_DESP
        ON P.PRD_LVL_CHILD = T_DESP.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPATRDETR', 'HDRATRDETR')) T_DETR
        ON P.PRD_LVL_CHILD = T_DETR.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPOPER', 'HDRBTVTEX')) T_BIGT_V
        ON P.PRD_LVL_CHILD = T_BIGT_V.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPOPER', 'HDRPEREC')) T_PERE
        ON P.PRD_LVL_CHILD = T_PERE.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPOPER', 'HDRTIPSUR')) T_TSUR
        ON P.PRD_LVL_CHILD = T_TSUR.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPOPER', 'HDRATRERT')) T_ERT
        ON P.PRD_LVL_CHILD = T_ERT.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPOPER', 'HDRDESRAN')) T_RDES
        ON P.PRD_LVL_CHILD = T_RDES.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPOPER', 'HDRVTPRV')) T_FLG_E
        ON P.PRD_LVL_CHILD = T_FLG_E.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPCOMER', 'HDRTIPINF')) T_FLG_I
        ON P.PRD_LVL_CHILD = T_FLG_I.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPCOMER', 'HDRTIPLGT')) T_TLGT
        ON P.PRD_LVL_CHILD = T_TLGT.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPOPER', 'HDRMODDESP')) T_TMD
        ON P.PRD_LVL_CHILD = T_TMD.PRD_LVL_CHILD
      LEFT JOIN TABLE(F_GET_CURSOR_ATR_SKU('TYPCOMER', 'HDRTOP2K')) T_TOP2K
        ON P.PRD_LVL_CHILD = T_TOP2K.PRD_LVL_CHILD;
