SELECT * FROM ORGMSTEE;
SELECT org_lvl_child,org_lvl_number,ORG_NAME_FULL, org.* FROM orgmstee ORG WHERE ORG_LVL_NUMBER IN (851,101,102,103);
SELECT * FROM orgmstee WHERE org_lvl_child IN(420,419,423,425);
SELECT * FROM WMS_TIPO_INTEGRACION_ORG ORDER BY org_lvl_child;

/*
4	419
5	419
13	419
14	419
15	419
16	419
 */


SELECT * FROM  EDSR.WMS_MAPEO_MOV_INV WHERE FACILITY_CODE = '101' ORDER BY ACTIVITY_CODE;
SELECT * FROM  EDSR.WMS_MAPEO_MOV_INV WHERE FACILITY_CODE = '102' ORDER BY ACTIVITY_CODE;
SELECT * FROM  EDSR.WMS_MAPEO_MOV_INV WHERE FACILITY_CODE = '103' ORDER BY ACTIVITY_CODE;

INSERT INTO WMS_TIPO_INTEGRACION_ORG (ID_TIPO,ORG_LVL_CHILD) VALUES (4,423);
INSERT INTO WMS_TIPO_INTEGRACION_ORG (ID_TIPO,ORG_LVL_CHILD) VALUES (5,423);
INSERT INTO WMS_TIPO_INTEGRACION_ORG (ID_TIPO,ORG_LVL_CHILD) VALUES (13,423);
INSERT INTO WMS_TIPO_INTEGRACION_ORG (ID_TIPO,ORG_LVL_CHILD) VALUES (14,423);
INSERT INTO WMS_TIPO_INTEGRACION_ORG (ID_TIPO,ORG_LVL_CHILD) VALUES (15,423);
INSERT INTO WMS_TIPO_INTEGRACION_ORG (ID_TIPO,ORG_LVL_CHILD) VALUES (16,423);
COMMIT;

INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 17, 'DO', null, null, 1, -1, 'AJ', '13', 102, 'F', 'F', 1, 'DE', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 17, 'CT', null, null, 1, 1, 'AJ', '70', 102, 'F', 'T', 1, null, '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 23, null, null, 'CMM', 1, 1, 'TR', '20', 102, 'F', 'F', 1, 'CMM', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 23, null, null, 'CMM', 2, 1, 'TR', '30', 102, 'F', 'F', 1, 'CMM', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 23, null, null, 'ST', 1, 1, 'TR', '20', 102, 'F', 'F', 1, 'ST', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 23, null, null, 'ST', 2, 1, 'TR', '30', 102, 'F', 'F', 1, 'ST', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 23, null, null, 'PB', 1, 1, 'TR', '20', 102, 'F', 'F', 1, 'PB', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 23, null, null, 'PB', 2, 1, 'TR', '30', 102, 'F', 'F', 1, 'PB', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 23, null, null, 'MS', 1, 1, 'AJ', '86', 102, 'F', 'F', 1, 'MS', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 23, null, null, 'MS', 2, -1, 'AJ', '92', 102, 'F', 'F', 1, 'MS', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 23, null, null, 'MA', 1, 1, 'AJ', '86', 102, 'F', 'F', 1, 'MA', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 23, null, null, 'MA', 2, -1, 'AJ', '92', 102, 'F', 'F', 1, 'MA', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 23, null, null, 'NAV', 1, 1, 'TR', '30', 102, 'F', 'F', 1, 'NAV', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 23, null, null, 'NAV', 2, 1, 'TR', '20', 102, 'F', 'F', 1, 'NAV', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 23, null, null, 'MC', 1, 1, 'TR', '20', 102, 'F', 'F', 1, 'MC', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 23, null, null, 'MC', 2, 1, 'TR', '50', 102, 'F', 'F', 1, 'MC', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 25, null, 'CMM', null, 1, 1, 'TR', '40', 102, 'F', 'F', 1, 'CMM', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 25, null, 'CMM', null, 2, 1, 'TR', '10', 102, 'F', 'F', 1, 'CMM', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 25, null, 'ST', null, 1, 1, 'TR', '40', 102, 'F', 'F', 1, 'ST', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 25, null, 'ST', null, 2, 1, 'TR', '10', 102, 'F', 'F', 1, 'ST', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 25, null, 'PB', null, 1, 1, 'TR', '40', 102, 'F', 'F', 1, 'PB', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 25, null, 'PB', null, 2, 1, 'TR', '10', 102, 'F', 'F', 1, 'PB', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 25, null, 'MS', null, 1, -1, 'AJ', '86', 102, 'F', 'F', 1, 'MS', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 25, null, 'MS', null, 2, 1, 'AJ', '92', 102, 'F', 'F', 1, 'MS', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 25, null, 'MA', null, 1, -1, 'AJ', '86', 102, 'F', 'F', 1, 'MA', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 25, null, 'MA', null, 2, 1, 'AJ', '92', 102, 'F', 'F', 1, 'MA', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 25, null, 'NAV', null, 1, 1, 'TR', '10', 102, 'F', 'F', 1, 'NAV', '102');
INSERT INTO EDSR.WMS_MAPEO_MOV_INV (COMPANY_CODE, ACTIVITY_CODE, REASON_CODE, REF_VALUE_1, REF_VALUE_2, SEQ_INV, IND_EFECTO, COD_MAESTRO, COD_DETALLE, SUC_INV, IND_REQ_RCV, IND_SGN_WMS, ESTADO, LOCK_CODE, FACILITY_CODE) VALUES ('HESA', 25, null, 'NAV', null, 2, 1, 'TR', '40', 102, 'F', 'F', 1, 'NAV', '102');
COMMIT;
