/*
    sp_procesa_load;
    sp_proceso_cd;
    sp_proceso_tienda;
 */

SELECT L.ID_HISTORY_LOAD
      FROM EDSR.WMS_INV_HISTORY_LOAD L
      WHERE L.CH_DUPLICADO = '0';

SELECT * FROM WMS_INV_HISTORY ORDER BY DOWNLOAD_DATE_1  DESC FETCH FIRST 200 ROWS ONLY;
SELECT * FROM WMS_INV_HISTORY
WHERE VENDOR_CODE = '1079'
  --AND TO_DATE(DOWNLOAD_DATE_1, 'YYYY-MM-DD') = TO_DATE('2024-12-08', 'YYYY-MM-DD')
--GROUP BY VENDOR_CODE,DOWNLOAD_DATE_1
ORDER BY DOWNLOAD_DATE_1  DESC
FETCH FIRST 800 ROWS ONLY;

SELECT * FROM WMS_INV_HISTORY WHERE LPN_NBR = 'LPN85100005333';