-- Crear esquema CM
CREATE SCHEMA IF NOT EXISTS "CM"
AUTHORIZATION current_user;

-- Ejemplo opcional: cambiar el search_path para trabajar en él por defecto
SET search_path TO "CM";


CREATE TABLE "CM".customer_clubpro (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	surname varchar(255) NULL,
	nivel numeric(19) NULL,
	identificationtype numeric(19) NULL,
	identificationnumber varchar(50) NULL,
	gender varchar(255) NULL,
	estate varchar(255) NULL,
	city varchar(255) NULL,
	district varchar(255) NULL,
	streetname varchar(255) NULL,
	streetnumber varchar(255) NULL,
	apartmentnumber varchar(255) NULL,
	phone varchar(255) DEFAULT '0'::character varying NULL,
	mobile varchar(255) NULL,
	email varchar(255) NULL,
	active numeric NULL,
	reservedfield1 varchar(255) NULL,
	reservedfield2 varchar(255) NULL,
	reservedfield3 varchar(255) NULL,
	reservedfield4 varchar(255) NULL,
	reservedfield5 varchar(255) NULL,
	tradename varchar(255) NULL,
	creationdate date DEFAULT CURRENT_DATE NULL,
	modificationdate date DEFAULT CURRENT_DATE NULL,
	profession varchar(255) NULL,
	CONSTRAINT customer_clubpro_pkey PRIMARY KEY (id)
);

CREATE TABLE customer_invoice (
    invoice VARCHAR(50) PRIMARY KEY,     -- Número de factura (único)
    identitynumber VARCHAR(20)           -- Número de cédula
);