--Listar pendientes
SELECT
	HEAD.HEADID AS headId,
	PPLSERIALNUMBER,
	CASE
	    WHEN HEAD.DOCUMENTTYPE = 'TFC' THEN 1
		WHEN HEAD.DOCUMENTTYPE = 'NCR' THEN 4
    END AS documentType
FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
WHERE HEAD.FLGPPL = 0
     AND HEAD.STATUS IN ('P') -- ('P', 'V')
 AND HEAD.DOCUMENTTYPE IN ('TFC','NCR');

SELECT HEADID,PPLSERIALNUMBER,FLGPPL,STATUS,DOCUMENTTYPE,PPL_RET_CODE,PPL_RET_MESSAGE,
PPL_FEC_AUTORIZACION,PPL_NUM_AUTORIZACION,PPL_CLAVE_ACCESO,HEAD.* 
FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
--update EDSRCT2.PIV_TRX_BCT_HEAD set FLGPPL = '0',PPL_RET_CODE = null, PPL_RET_MESSAGE = null, PPL_FEC_AUTORIZACION = null, PPL_NUM_AUTORIZACION = null, PPL_CLAVE_ACCESO= null
--update EDSRCT2.PIV_TRX_BCT_HEAD set FLGPPL = '1'
--update EDSRCT2.PIV_TRX_BCT_HEAD set PPLSERIALNUMBER = '005-094-000000338'
WHERE PPLSERIALNUMBER IN ('005-094-000000333','005-094-000000338','005-094-000000335');--PPLSERIALNUMBER IS null;
--'005-094-000000334','005-094-000000335','005-094-000000336','005-094-000000337','005-094-000000338';
COMMIT;

SELECT PPLSERIALNUMBER,DATESAVED,ptbh.* FROM EDSRCT2.PIV_TRX_BCT_HEAD ptbh ORDER BY ptbh.DATESAVED DESC;
--UPDATE EDSRCT2.PIV_TRX_BCT_HEAD SET DATESAVED = TIMESTAMP '2025-12-01 16:01:22.000' WHERE HEADID = 94425;

--CONSULTA ESTADO
SELECT  HEAD.HEADID AS headid,
PPL_RET_CODE,PPL_RET_MESSAGE,
		COM.RUC AS RucEmpresa,
		CASE 
			WHEN HEAD.DOCUMENTTYPE = 'TFC' THEN '01'
			WHEN HEAD.DOCUMENTTYPE = 'NCR' THEN '04'
		END AS TipoDocumento,
		REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,1) AS Establecimiento,
    	REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,2) AS PtoEmision,
   		REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,3) AS Secuencial
FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
INNER JOIN EDSR.PIVOT_COMPANY COM ON HEAD.COMPANY = COM.COD_COMPANY
WHERE HEAD.PPL_RET_CODE IN ('1','3','8','9');



--ACTUALIZAR
SELECT HEADID,PPLSERIALNUMBER,FLGPPL,STATUS,DOCUMENTTYPE,PPL_RET_CODE,PPL_RET_MESSAGE,
PPL_FEC_AUTORIZACION,PPL_NUM_AUTORIZACION,PPL_CLAVE_ACCESO,HEAD.* 
FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
--UPDATE EDSRCT2.PIV_TRX_BCT_HEAD SET PPL_RET_CODE = '1',PPL_RET_MESSAGE = '' ,PPL_FEC_AUTORIZACION=null,PPL_NUM_AUTORIZACION=null,PPL_CLAVE_ACCESO=null --FLGPPL = 0 , STATUS = 'P'
WHERE HEADID IN (94420);
COMMIT;
ROLLBACK;

SELECT * FROM edsr.hp_vtex_picking
--UPDATE edsr.hp_vtex_picking pic SET DIRECCION = 'Pasaje Julio Moreno y Avenida 6 de diciembre  Edificio Naia La Carolina Junto al Megamaxi de la 6 Edificio NAIA  Estamos al final del pasaje julio moreno pasando el porton electrico, al final de la cuchara. Edificio NAIA  Departamento 3i  A nombre de Andrea Pilo'
WHERE id_picking = 15102;
/*
 * Antiguas CAJA EXPRESS 1/12/2025
005-094-000000329
005-094-000000328
005-094-000000327
005-094-000000326
005-094-000000325
005-094-000000324
005-094-000000323
005-094-000000322
005-094-000000321
005-094-000000320
 */

--EDSR.PKG_PIVOT_STUPENDO
SELECT HEADID,PPLSERIALNUMBER,FLGPPL,STATUS,DOCUMENTTYPE,PPL_RET_CODE,PPL_RET_MESSAGE,
PPL_FEC_AUTORIZACION,PPL_NUM_AUTORIZACION,PPL_CLAVE_ACCESO,HEAD.* 
FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
WHERE 
	PPLSERIALNUMBER = '005-094-000000329'
	--FLGPPL = 0;

/*
 * 2025-05-28
 */

SELECT DISTINCT CUSTOMERDOCUMENTTYPE FROM EDSRCT2.PIV_TRX_BCT_HEAD ptbh ;

DECLARE 
	CUSTOMERDOCUMENTTYPE VARCHAR2;
BEGIN
	SELECT
		CASE CUSTOMERDOCUMENTTYPE WHEN
		END CASE
	FROM DUAL;
END;

SELECT DISTINCT DOCUMENTTYPE FROM EDSRCT2.PIV_TRX_BCT_HEAD;
SELECT DISTINCT POSID FROM EDSRCT2.PIV_TRX_BCT_HEAD;

--CONSULTAR DOCUMENTO POR TIPO
SELECT HEADID,PPLSERIALNUMBER,FLGPPL,STATUS,DOCUMENTTYPE,PPL_RET_CODE,PPL_RET_MESSAGE,
PPL_FEC_AUTORIZACION,PPL_NUM_AUTORIZACION,PPL_CLAVE_ACCESO,HEAD.* FROM EDSRCT2.PIV_TRX_BCT_HEAD head
WHERE DOCUMENTTYPE = 'TFC' -- Factura:TFC | NotaCredito:NCR
	AND POSID != 80 -- Ecommerce: 80 | Caja Express: 20 al 25
ORDER BY head.DATESAVED DESC, AMOUNT DESC 
FETCH FIRST 150 ROWS ONLY;

SELECT HEADID,PPLSERIALNUMBER,FLGPPL,STATUS,DOCUMENTTYPE,PPL_RET_CODE,PPL_RET_MESSAGE,
PPL_FEC_AUTORIZACION,PPL_NUM_AUTORIZACION,PPL_CLAVE_ACCESO,HEAD.* FROM EDSRCT2.PIV_TRX_BCT_HEAD head
WHERE DOCUMENTTYPE = 'TFC' 
	and PPLSERIALNUMBER IN ('005-094-000000320');

SELECT HEADID, PPLSERIALNUMBER,UNAFFECTEDTOTALAMOUNT,AFFECTEDTOTALAMOUNT,IGVTOTALAMOUNT,
UNAFFECTEDTOTALAMOUNT + AFFECTEDTOTALAMOUNT + IGVTOTALAMOUNT AS TotalCalculado
, FLGPPL, STATUS,DOCUMENTTYPE, PPL_RET_CODE, PPL_RET_MESSAGE, HEAD.*
FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
--UPDATE EDSRCT2.PIV_TRX_BCT_HEAD SET FLGPPL = 0
--WHERE HEADID IN (93364)
WHERE 
	--HEADID IN (93352,93354,93363,93364,92993,92994)
	HEADID IN (93364)
	--PPLSERIALNUMBER = '002-094-000000064'
--ORDER BY HEAD.HEADID DESC
;
COMMIT;

-- PENDIENTES
SELECT
    HEAD.HEADID AS headId,
    CASE
        WHEN HEAD.DOCUMENTTYPE = 'TFC' THEN 1
        WHEN HEAD.DOCUMENTTYPE = 'NCR' THEN 4
    END AS documentType
FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
WHERE HEAD.FLGPPL = 0
 AND HEAD.STATUS IN ('P') -- ('P', 'V')
 AND HEAD.DOCUMENTTYPE IN ('TFC','NCR');

--DESCUENTO
SELECT * FROM EDSRCT2.PIV_TRX_BCT_DSCTO WHERE HEADID = 93124;
SELECT SUM( ROUND( NVL( AMOUNT/( (FNU_GET_PRODUCTO_IVA(PRD.PRD_LVL_CHILD)/100) + 1 ), 0.00),2) )
FROM EDSRCT2.PIV_TRX_BCT_DSCTO DSCTO
    INNER JOIN EDSR.TPPRDMST PRD ON PRD.PRD_LVL_NUMBER = DSCTO.ITEMSKU
WHERE DSCTO.HEADID = 93157;



--FACTURA
SELECT
			pic.id_picking,
		    COM.RAZON_SOCIAL as razonSocial,
		    'PROMART' AS nombreComercial,
		    COM.RUC AS ruc,
		    '01' codDoc,
		    REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,1) AS estab,
		    REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,2) AS ptoEmi,
		    REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,3) AS secuencial,
		    COM.DIRECCION_MATRIZ AS dirMatriz,
		    TO_CHAR(HEAD.TRXDATE,'DD/MM/YYYY') AS fechaEmision,
		    EST.VC_DIRECCION AS dirEstablecimiento,
		    'SI' AS obligadoContabilidad,
		    CASE
		        WHEN HEAD.CUSTOMERBUSINESSDOCNUMBER IS NULL THEN '05'
		        WHEN LENGTH(HEAD.CUSTOMERBUSINESSDOCNUMBER) = 0 THEN '05'
		        ELSE '04'
		    END AS tipoIdentificacionComprador,
		    CASE
		        WHEN HEAD.CUSTOMERBUSINESSDOCNUMBER IS NULL THEN HEAD.CUSTOMERNAME || ' ' || HEAD.CUSTOMERSURNAME
		        WHEN LENGTH(HEAD.CUSTOMERBUSINESSDOCNUMBER) = 0 THEN  HEAD.CUSTOMERNAME || ' ' || HEAD.CUSTOMERSURNAME
		        ELSE HEAD.CUSTOMERBUSINESSNAME
		    END AS razonSocialComprador,
		    CASE
		        WHEN HEAD.CUSTOMERBUSINESSDOCNUMBER IS NULL THEN HEAD.CUSTOMERDOCUMENTNUMBER
		        WHEN LENGTH(HEAD.CUSTOMERBUSINESSDOCNUMBER) = 0 THEN HEAD.CUSTOMERDOCUMENTNUMBER
		        ELSE HEAD.CUSTOMERBUSINESSDOCNUMBER
		    END AS identificacionComprador,
		    nvl(pic.direccion, 'SN') AS direccionComprador,
		    HEAD.AFFECTEDTOTALAMOUNT + HEAD.UNAFFECTEDTOTALAMOUNT AS totalSinImpuestos,
		    NVL('V_TOTALDESCUENTO',0.00) AS totalDescuento,
		    2 AS codigo,
		    2 AS codigoPorcentaje,
		    HEAD.AFFECTEDTOTALAMOUNT AS baseImponible,
		    HEAD.IGVPERCENTAGE AS tarifa,
		    HEAD.IGVTOTALAMOUNT AS valor,
		    '0.00' AS propina,
		    HEAD.AMOUNT AS importeTotal,
		    'DOLAR' AS moneda,
		    MEDIOPAGO.COD_SRI AS formaPago,
		    HEAD.AMOUNT AS total,
		    PAYMENT.CUOTAS*30 AS plazo,
		    'dias' AS unidadTiempo,
		    HEAD.CUSTOMEREMAIL AS email,
		    HEAD.CUSTOMERPHONE AS telefono,
		    'Estimado cliente, de acuerdo al Art. 50 de la Ley de Regimen Tributario Interno, Los agentes de retencion estan obligados a entregar el respectivo comprobante de retencion, dentro del termino no mayor de cinco dias de recibido el comprobante de venta' AS disclaimer
		FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
			INNER JOIN EDSR.PIVOT_COMPANY COM ON HEAD.COMPANY = COM.COD_COMPANY
			INNER JOIN EDSR.PIVOT_ESTABLECIMIENTO EST ON (HEAD.BRANCHID = EST.BRANCHID AND COM.COD_COMPANY = EST.COD_COMPANY)
			LEFT JOIN EDSRCT2.PIV_TRX_BCT_DSCTO  DSCTO  ON HEAD.HEADID = DSCTO.HEADID
			LEFT JOIN EDSRCT2.PIV_TRX_BCT_PAYMENT PAYMENT ON PAYMENT.HEADID = HEAD.HEADID
			LEFT JOIN EDSR.HP_VTEX_MEDIO_PAGO MEDIOPAGO ON MEDIOPAGO.IDVTEX = PAYMENT.PAYMENTMETHODCODE
    		LEFT JOIN edsr.hp_vtex_picking pic on pic.id_picking = head.originid and head.origintrx = 1
		WHERE
		    COM.COD_COMPANY = 'HE'
		   -- AND PAYMENT.PAYMENTMETHODCODE IN (1,401,2,3,4,5)
		    AND HEAD.HEADID = 15422;
--
--DETALLE
SELECT * FROM EDSRCT2.SRI_IVA_PORCENTAJE;
SELECT * FROM EDSRCT2.PIV_TRX_BCT_ITEM WHERE HEADID = 93157;

SELECT
    ITEM.SKU AS codigoPrincipal,
    ITEM.PRODUCTNAME AS descripcion,
    TO_NUMBER(ITEM.QUANTITY,'9999.99') AS cantidad,
    ROUND(NVL(ITEM.PRICE/( (IVA.PORC_IVA/100) + 1 ),0.00),2) AS precioUnitario,
    ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2) AS descuento,
    ROUND(NVL( ITEM.QUANTITY*(ITEM.PRICE/( (IVA.PORC_IVA/100) + 1 )) - ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2), 0.00) ,2) AS precioTotalSinImpuesto,
    2 AS codigo,
    IVA.COD_IVA AS codigoPorcentaje,
    DECODE(IVA.PORC_IVA,0.00,'0.00',TRIM(TO_CHAR(IVA.PORC_IVA,'999.99'))) AS tarifa,
    ROUND(NVL( ITEM.QUANTITY*(ITEM.PRICE/( (IVA.PORC_IVA/100) + 1 )) - ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2), 0.00) ,2) AS baseImponible,
    ROUND( (NVL( ITEM.QUANTITY*(ITEM.PRICE/( (IVA.PORC_IVA/100) + 1 )) - ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2), 0.00))*(IVA.PORC_IVA/100)  ,2) AS valor
FROM EDSRCT2.PIV_TRX_BCT_ITEM ITEM
    INNER JOIN EDSRCT2.SRI_IVA_PORCENTAJE IVA ON IVA.ID_IVA = ITEM.ID_IVA
    INNER JOIN  EDSRCT2.PIV_TRX_BCT_HEAD HEAD ON HEAD.HEADID = ITEM.HEADID
    INNER JOIN EDSR.PIVOT_COMPANY COM ON HEAD.COMPANY = COM.COD_COMPANY
    INNER JOIN EDSR.PIVOT_ESTABLECIMIENTO EST ON (HEAD. BRANCHID = EST.BRANCHID AND COM.COD_COMPANY = EST.COD_COMPANY)
    LEFT JOIN EDSRCT2.PIV_TRX_BCT_DSCTO  DSCTO  ON (HEAD.HEADID = DSCTO.HEADID AND ITEM.SEQUENCE = DSCTO.ITEMSEQUENCE)
WHERE
    COM.COD_COMPANY = 'HE'
    AND HEAD.HEADID = 93364;

--TotalConImpuestos
SELECT
    2 AS codigo,
    IVA.COD_IVA AS codigoPorcentaje,
    IVA.PORC_IVA AS tarifa,
    ROUND(NVL( SUM( (ITEM.QUANTITY * ITEM.PRICE) /( (IVA.PORC_IVA/100) + 1 ) - ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2) ), 0.00) ,2) AS baseImponible,
	ROUND( (NVL( SUM( (ITEM.QUANTITY * ITEM.PRICE) /( (IVA.PORC_IVA/100) + 1 ) - ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2) ), 0.00))*(IVA.PORC_IVA/100) ,2) AS valor	
FROM EDSRCT2.PIV_TRX_BCT_ITEM ITEM
    INNER JOIN EDSRCT2.SRI_IVA_PORCENTAJE IVA ON IVA.ID_IVA = ITEM.ID_IVA
    INNER JOIN  EDSRCT2.PIV_TRX_BCT_HEAD HEAD ON HEAD.HEADID = ITEM.HEADID
    INNER JOIN EDSR.PIVOT_COMPANY COM ON HEAD.COMPANY = COM.COD_COMPANY
    INNER JOIN EDSR.PIVOT_ESTABLECIMIENTO EST ON (HEAD. BRANCHID = EST.BRANCHID AND COM.COD_COMPANY = EST.COD_COMPANY)
    LEFT JOIN EDSRCT2.PIV_TRX_BCT_DSCTO  DSCTO  ON (HEAD.HEADID = DSCTO.HEADID AND ITEM.SEQUENCE = DSCTO.ITEMSEQUENCE)
WHERE
    COM.COD_COMPANY = 'HE'
    AND HEAD.HEADID = 93364
GROUP BY IVA.COD_IVA,IVA.PORC_IVA--,ITEM.SKU
;