
/*
93124

93159	002-090-000000159
93158	002-090-000000160
93157	002-090-000000161
93156	002-090-000000157
93154	002-090-000000156
93153	002-090-000000155
 */

--EDSR.PKG_PIVOT_STUPENDO
SELECT HEADID, PPLSERIALNUMBER,FLGPPL, STATUS,DOCUMENTTYPE, PPL_RET_CODE, PPL_RET_MESSAGE, HEAD.* FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD WHERE FLGPPL = 0;

SELECT HEADID, PPLSERIALNUMBER,UNAFFECTEDTOTALAMOUNT,AFFECTEDTOTALAMOUNT, FLGPPL, STATUS,DOCUMENTTYPE, PPL_RET_CODE, PPL_RET_MESSAGE, HEAD.*
FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
--UPDATE EDSRCT2.PIV_TRX_BCT_HEAD SET FLGPPL = 0
--WHERE HEADID IN (93157)
WHERE HEADID IN (93352,93354,93363,93364,92993,92994)
--ORDER BY HEAD.HEADID DESC
;
COMMIT;

-- PENDIENTES
SELECT
    HEAD.HEADID AS headId,
    CASE
        WHEN HEAD.DOCUMENTTYPE = 'TFC' THEN 1
        WHEN HEAD.DOCUMENTTYPE = 'NCR' THEN 4
    END AS documentType
FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
WHERE HEAD.FLGPPL = 0
 AND HEAD.STATUS IN ('P') -- ('P', 'V')
 AND HEAD.DOCUMENTTYPE IN ('TFC','NCR');

--DESCUENTO
SELECT * FROM EDSRCT2.PIV_TRX_BCT_DSCTO WHERE HEADID = 93124;
SELECT SUM( ROUND( NVL( AMOUNT/( (FNU_GET_PRODUCTO_IVA(PRD.PRD_LVL_CHILD)/100) + 1 ), 0.00),2) )
FROM EDSRCT2.PIV_TRX_BCT_DSCTO DSCTO
    INNER JOIN EDSR.TPPRDMST PRD ON PRD.PRD_LVL_NUMBER = DSCTO.ITEMSKU
WHERE DSCTO.HEADID = 93157;

--FACTURA
SELECT
		    COM.RAZON_SOCIAL as razonSocial,
		    'PROMART' AS nombreComercial,
		    COM.RUC AS ruc,
		    '01' codDoc,
		    REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,1) AS estab,
		    REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,2) AS ptoEmi,
		    REGEXP_SUBSTR(HEAD.PPLSERIALNUMBER, '[^-]+',1,3) AS secuencial,
		    COM.DIRECCION_MATRIZ AS dirMatriz,

		    TO_CHAR(HEAD.TRXDATE,'DD/MM/YYYY') AS fechaEmision,
		    EST.VC_DIRECCION AS dirEstablecimiento,
		    'SI' AS obligadoContabilidad,
		    CASE
		        WHEN HEAD.CUSTOMERBUSINESSDOCNUMBER IS NULL THEN '05'
		        WHEN LENGTH(HEAD.CUSTOMERBUSINESSDOCNUMBER) = 0 THEN '05'
		        ELSE '04'
		    END AS tipoIdentificacionComprador,
		    CASE
		        WHEN HEAD.CUSTOMERBUSINESSDOCNUMBER IS NULL THEN HEAD.CUSTOMERNAME || ' ' || HEAD.CUSTOMERSURNAME
		        WHEN LENGTH(HEAD.CUSTOMERBUSINESSDOCNUMBER) = 0 THEN  HEAD.CUSTOMERNAME || ' ' || HEAD.CUSTOMERSURNAME
		        ELSE HEAD.CUSTOMERBUSINESSNAME
		    END AS razonSocialComprador,
		    CASE
		        WHEN HEAD.CUSTOMERBUSINESSDOCNUMBER IS NULL THEN HEAD.CUSTOMERDOCUMENTNUMBER
		        WHEN LENGTH(HEAD.CUSTOMERBUSINESSDOCNUMBER) = 0 THEN HEAD.CUSTOMERDOCUMENTNUMBER
		        ELSE HEAD.CUSTOMERBUSINESSDOCNUMBER
		    END AS identificacionComprador,
		    nvl(pic.direccion, 'SN') AS direccionComprador,

		    HEAD.AFFECTEDTOTALAMOUNT + HEAD.UNAFFECTEDTOTALAMOUNT AS totalSinImpuestos,

		    NVL('V_TOTALDESCUENTO',0.00) AS totalDescuento,

		    2 AS codigo,
		    2 AS codigoPorcentaje,
		    HEAD.AFFECTEDTOTALAMOUNT AS baseImponible,
		    HEAD.IGVPERCENTAGE AS tarifa,
		    HEAD.IGVTOTALAMOUNT AS valor,

		    '0.00' AS propina,
		    HEAD.AMOUNT AS importeTotal,
		    'DOLAR' AS moneda,

		    MEDIOPAGO.COD_SRI AS formaPago,
		    HEAD.AMOUNT AS total,
		    PAYMENT.CUOTAS*30 AS plazo,
		    'dias' AS unidadTiempo,

		    HEAD.CUSTOMEREMAIL AS email,
		    HEAD.CUSTOMERPHONE AS telefono,
		    'Estimado cliente, de acuerdo al Art. 50 de la Ley de Regimen Tributario Interno, Los agentes de retencion estan obligados a entregar el respectivo comprobante de retencion, dentro del termino no mayor de cinco dias de recibido el comprobante de venta' AS disclaimer

		FROM EDSRCT2.PIV_TRX_BCT_HEAD HEAD
			INNER JOIN EDSR.PIVOT_COMPANY COM ON HEAD.COMPANY = COM.COD_COMPANY
			INNER JOIN EDSR.PIVOT_ESTABLECIMIENTO EST ON (HEAD.BRANCHID = EST.BRANCHID AND COM.COD_COMPANY = EST.COD_COMPANY)
			LEFT JOIN EDSRCT2.PIV_TRX_BCT_DSCTO  DSCTO  ON HEAD.HEADID = DSCTO.HEADID
			LEFT JOIN EDSRCT2.PIV_TRX_BCT_PAYMENT PAYMENT ON PAYMENT.HEADID = HEAD.HEADID
			LEFT JOIN EDSR.HP_VTEX_MEDIO_PAGO MEDIOPAGO ON MEDIOPAGO.IDVTEX = PAYMENT.PAYMENTMETHODCODE
    		LEFT JOIN edsr.hp_vtex_picking pic on pic.id_picking = head.originid and head.origintrx = 1
		WHERE
		    COM.COD_COMPANY = 'HE'
		   -- AND PAYMENT.PAYMENTMETHODCODE IN (1,401,2,3,4,5)
		    AND HEAD.HEADID = 93284;
--
--DETALLE
SELECT * FROM EDSRCT2.SRI_IVA_PORCENTAJE;
SELECT * FROM EDSRCT2.PIV_TRX_BCT_ITEM WHERE HEADID = 93157;
SELECT
    ITEM.SKU AS codigoPrincipal,
    ITEM.PRODUCTNAME AS descripcion,
    TO_NUMBER(ITEM.QUANTITY,'9999.99') AS cantidad,
    ROUND(NVL(ITEM.PRICE/( (IVA.PORC_IVA/100) + 1 ),0.00),2) AS precioUnitario,
    ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2) AS descuento,
    ROUND(NVL( ITEM.QUANTITY*(ITEM.PRICE/( (IVA.PORC_IVA/100) + 1 )) - ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2), 0.00) ,2) AS precioTotalSinImpuesto,

    2 AS codigo,
    IVA.COD_IVA AS codigoPorcentaje,
    DECODE(IVA.PORC_IVA,0.00,'0.00',TRIM(TO_CHAR(IVA.PORC_IVA,'999.99'))) AS tarifa,
    ROUND(NVL( ITEM.QUANTITY*(ITEM.PRICE/( (IVA.PORC_IVA/100) + 1 )) - ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2), 0.00) ,2) AS baseImponible,
    ROUND( (NVL( ITEM.QUANTITY*(ITEM.PRICE/( (IVA.PORC_IVA/100) + 1 )) - ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2), 0.00))*(IVA.PORC_IVA/100)  ,2) AS valor

FROM EDSRCT2.PIV_TRX_BCT_ITEM ITEM
    INNER JOIN EDSRCT2.SRI_IVA_PORCENTAJE IVA ON IVA.ID_IVA = ITEM.ID_IVA
    INNER JOIN  EDSRCT2.PIV_TRX_BCT_HEAD HEAD ON HEAD.HEADID = ITEM.HEADID
    INNER JOIN EDSR.PIVOT_COMPANY COM ON HEAD.COMPANY = COM.COD_COMPANY
    INNER JOIN EDSR.PIVOT_ESTABLECIMIENTO EST ON (HEAD. BRANCHID = EST.BRANCHID AND COM.COD_COMPANY = EST.COD_COMPANY)
    LEFT JOIN EDSRCT2.PIV_TRX_BCT_DSCTO  DSCTO  ON (HEAD.HEADID = DSCTO.HEADID AND ITEM.SEQUENCE = DSCTO.ITEMSEQUENCE)
WHERE
    COM.COD_COMPANY = 'HE'
    AND HEAD.HEADID = 93157;

--TotalConImpuestos
SELECT
    2 AS codigo,
    IVA.COD_IVA AS codigoPorcentaje,
    IVA.PORC_IVA AS tarifa,
    ROUND(NVL( SUM(ITEM.QUANTITY * ( ITEM.PRICE /( (IVA.PORC_IVA/100) + 1 ) - ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2) )), 0.00) ,2) AS baseImponible,
    ROUND( (NVL( SUM(ITEM.QUANTITY * ( ITEM.PRICE /( (IVA.PORC_IVA/100) + 1 ) - ROUND(NVL(DSCTO.AMOUNT/( (IVA.PORC_IVA/100) + 1 ),0.00),2) )), 0.00))*(IVA.PORC_IVA/100) ,2) AS valor

FROM EDSRCT2.PIV_TRX_BCT_ITEM ITEM
    INNER JOIN EDSRCT2.SRI_IVA_PORCENTAJE IVA ON IVA.ID_IVA = ITEM.ID_IVA
    INNER JOIN  EDSRCT2.PIV_TRX_BCT_HEAD HEAD ON HEAD.HEADID = ITEM.HEADID
    INNER JOIN EDSR.PIVOT_COMPANY COM ON HEAD.COMPANY = COM.COD_COMPANY
    INNER JOIN EDSR.PIVOT_ESTABLECIMIENTO EST ON (HEAD. BRANCHID = EST.BRANCHID AND COM.COD_COMPANY = EST.COD_COMPANY)
    LEFT JOIN EDSRCT2.PIV_TRX_BCT_DSCTO  DSCTO  ON (HEAD.HEADID = DSCTO.HEADID AND ITEM.SEQUENCE = DSCTO.ITEMSEQUENCE)
WHERE
    COM.COD_COMPANY = 'HE'
    AND HEAD.HEADID = 93157
GROUP BY IVA.COD_IVA,IVA.PORC_IVA
;