--Monitor
SELECT 
	--HEADID,PPL_RET_MESSAGE
	--DISTINCT PPL_RET_MESSAGE
DATESAVED,HEADID,PPL_RET_CODE,PPL_RET_MESSAGE, H.*
FROM EDSRCT2.PIV_TRX_BCT_HEAD H
WHERE
	FLGPPL = 1
    AND PPL_RET_CODE != 5
    AND PPL_REVIEWED_FLAG = 0 --= -1 =>  10
ORDER BY H.DATESAVED DESC;

SELECT DATESAVED, HEADID ,PPL_RET_CODE,PPLSERIALNUMBER,PPL_RET_MESSAGE, PPL_REVIEWED_FLAG, PPL_REVIEW_COMMENT, PPL_REVIEWED_BY
FROM EDSRCT2.PIV_TRX_BCT_HEAD
WHERE FLGPPL = 1  AND PPL_RET_CODE NOT IN (5)  AND PPL_REVIEWED_FLAG = 0;

SELECT HEADID,
       PPL_RET_CODE,
       PPLSERIALNUMBER,
       PPL_RET_MESSAGE
FROM EDSRCT2.PIV_TRX_BCT_HEAD
WHERE FLGPPL = 1
  AND PPL_RET_CODE NOT IN (5)
  AND PPL_REVIEWED_FLAG = 0
;

SELECT * FROM EDSR.HP_SMTP_ALERTA H WHERE H.IDSMTP = 2;

--validar roles
SELECT grantee,owner, table_name, privilege, grantor
FROM dba_tab_privs
WHERE grantee = UPPER('SOMS')
 /* AND owner = 'EDSRCT2'
  AND table_name = 'PIV_TRX_BCT_HEAD'*/
ORDER BY table_name
;
